// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "A professor lived here and died",
    "character": "",
    "audioUrl": "audio/old-school/004_a_professor_lived_here_for_like_30_years_and_then_he_died.mp3"
  },
  {
    "text": "Look at the baby",
    "character": "",
    "audioUrl": "audio/old-school/025_always_smiling_hi_honey_judging_watching_look_at_the_baby.mp3"
  },
  {
    "text": "The vault competition",
    "character": "",
    "audioUrl": "audio/old-school/035_and_for_the_vault_competition_oh_i_don_t_know.mp3"
  },
  {
    "text": "What color her underpants might be",
    "character": "",
    "audioUrl": "audio/old-school/040_and_i_found_myself_wondering_what_color_her_underpants_might.mp3"
  },
  {
    "text": "A little something called herpes",
    "character": "",
    "audioUrl": "audio/old-school/078_barry_oral_sex_instructor_he_left_me_with_a_little_something.mp3"
  },
  {
    "text": "Grab your vegetables!",
    "character": "",
    "audioUrl": "audio/old-school/079_barry_oral_sex_instructor_the_secret_to_a_good_bj_is_focus_i.mp3"
  },
  {
    "text": "Whose lives are ruined?",
    "character": "",
    "audioUrl": "audio/old-school/082_beanie_after_finding_out_that_it_s_in_the_bylaw_that_the_onl.mp3"
  },
  {
    "text": "It takes a man to give away an angel",
    "character": "",
    "audioUrl": "audio/old-school/083_beanie_to_frank_s_father_in_law_it_takes_a_man_to_give_away.mp3"
  },
  {
    "text": "A very big idea",
    "character": "",
    "audioUrl": "audio/old-school/084_beanie_because_this_is_a_very_big_idea_my_friends_we_re_talk.mp3"
  },
  {
    "text": "Blue was old",
    "character": "",
    "audioUrl": "audio/old-school/085_beanie_don_t_beat_yourself_up_over_this_mitch_it_s_not_your.mp3"
  },
  {
    "text": "Say it to the baby",
    "character": "",
    "audioUrl": "audio/old-school/086_beanie_don_t_say_sorry_to_me_frank_say_it_to_the_baby_frank.mp3"
  },
  {
    "text": "Earmuff it for me",
    "character": "",
    "audioUrl": "audio/old-school/087_beanie_don_t_say_sorry_to_me_you_let_down_frank_you_let_down.mp3"
  },
  {
    "text": "You're on the rebound",
    "character": "",
    "audioUrl": "audio/old-school/088_beanie_girls_love_a_guy_who_s_in_your_situation_mitch_what_s.mp3"
  },
  {
    "text": "See you around campus",
    "character": "",
    "audioUrl": "audio/old-school/089_beanie_good_luck_to_everybody_nice_to_know_you_all_and_i_ll.mp3"
  },
  {
    "text": "The Godfather himself",
    "character": "",
    "audioUrl": "audio/old-school/090_beanie_guys_this_is_a_very_special_occasion_the_godfather_hi.mp3"
  },
  {
    "text": "Do I seem like a happy guy?",
    "character": "",
    "audioUrl": "audio/old-school/091_beanie_i_have_a_wife_and_kids_do_i_seem_like_a_happy_guy_to.mp3"
  },
  {
    "text": "Mitch Martin Freedom Festival",
    "character": "",
    "audioUrl": "audio/old-school/092_beanie_i_d_like_to_welcome_you_all_to_the_mitch_martin_freed.mp3"
  },
  {
    "text": "Crazy boy band ass",
    "character": "",
    "audioUrl": "audio/old-school/093_beanie_max_can_you_earmuff_for_me_we_are_going_to_get_so_muc.mp3"
  },
  {
    "text": "Mitch is a lawyer",
    "character": "",
    "audioUrl": "audio/old-school/094_beanie_mitch_is_a_lawyer_buddy_he_ll_find_a_way_out_for_us.mp3"
  },
  {
    "text": "That's a piece of crap",
    "character": "",
    "audioUrl": "audio/old-school/095_beanie_no_that_s_a_piece_of_crap_we_stopped_selling_that_six.mp3"
  },
  {
    "text": "Put your head back on",
    "character": "",
    "audioUrl": "audio/old-school/096_beanie_spanish_what_the_hell_are_you_doing_spanish_i_m_just.mp3"
  },
  {
    "text": "A lot of street cred",
    "character": "",
    "audioUrl": "audio/old-school/097_beanie_that_party_that_we_had_last_night_has_given_us_a_lot.mp3"
  },
  {
    "text": "Whose life is ruined?",
    "character": "",
    "audioUrl": "audio/old-school/098_beanie_whose_life_is_ruined_mitch_let_s_see_blue_s_dead_fran.mp3"
  },
  {
    "text": "The guy who won't get in",
    "character": "",
    "audioUrl": "audio/old-school/099_beanie_yeah_from_the_guy_who_probably_won_t_get_in_jerry_i_g.mp3"
  },
  {
    "text": "I own six Speaker Cities",
    "character": "",
    "audioUrl": "audio/old-school/100_beanie_yeah_that_s_it_i_got_a_student_alt_rock_band_coming_o.mp3"
  },
  {
    "text": "Avoiding my wife and kids",
    "character": "",
    "audioUrl": "audio/old-school/101_beanie_you_think_i_like_avoiding_my_wife_and_kids_to_hangout.mp3"
  },
  {
    "text": "You're the lady, Marissa",
    "character": "",
    "audioUrl": "audio/old-school/102_beanie_you_re_the_lady_marissa_high_five.mp3"
  },
  {
    "text": "True love is blind",
    "character": "",
    "audioUrl": "audio/old-school/104_because_i_think_what_mitch_is_trying_to_say_is_that_true_lov.mp3"
  },
  {
    "text": "Waiting all semester",
    "character": "",
    "audioUrl": "audio/old-school/116_booker_we_ve_been_waiting_all_semester_for_you_to_ask_us.mp3"
  },
  {
    "text": "Put a hot tub anywhere",
    "character": "",
    "audioUrl": "audio/old-school/174_couple_la_z_boys_to_fill_it_out_a_smarter_couch_you_could_pu.mp3"
  },
  {
    "text": "This is me leaving",
    "character": "",
    "audioUrl": "audio/old-school/182_dean_pritchard_are_you_a_comedian_now_this_is_me_leaving_thi.mp3"
  },
  {
    "text": "Please welcome James Carville",
    "character": "",
    "audioUrl": "audio/old-school/183_dean_pritchard_ladies_and_gentleman_please_welcome_the_co_ho.mp3"
  },
  {
    "text": "Once it hits your lips, it's so good!",
    "character": "",
    "audioUrl": "audio/old-school/236_frank_after_funneling_a_beer_fill_it_up_again_fill_it_up_aga.mp3"
  },
  {
    "text": "It's got three speeds",
    "character": "",
    "audioUrl": "audio/old-school/237_frank_offering_a_bread_maker_as_a_gift_what_do_you_think_max.mp3"
  },
  {
    "text": "Blue, you're my boy!",
    "character": "",
    "audioUrl": "audio/old-school/238_frank_spanish_do_you_trust_that_we_have_provided_you_with_en.mp3"
  },
  {
    "text": "A little housewarming gift",
    "character": "",
    "audioUrl": "audio/old-school/239_frank_a_little_housewarming_gift_mitch_i_actually_gave_this.mp3"
  },
  {
    "text": "Have at it, hoss",
    "character": "",
    "audioUrl": "audio/old-school/240_frank_actually_i_d_like_to_jump_in_and_take_that_one_jimmy_i.mp3"
  },
  {
    "text": "Dust in the wind",
    "character": "",
    "audioUrl": "audio/old-school/241_frank_all_we_are_is_dust_in_the_wind.mp3"
  },
  {
    "text": "Drop and give me ten",
    "character": "",
    "audioUrl": "audio/old-school/242_frank_blue_how_come_there_s_no_ice_in_my_lemonade_throws_the.mp3"
  },
  {
    "text": "Dear Mitch, the house has been boarded up",
    "character": "",
    "audioUrl": "audio/old-school/243_frank_dear_mitch_if_you_re_holding_this_letter_you_already_k.mp3"
  },
  {
    "text": "Is KFC still open?",
    "character": "",
    "audioUrl": "audio/old-school/244_frank_honey_you_think_kfc_is_still_open.mp3"
  },
  {
    "text": "I see Blue, he looks glorious",
    "character": "",
    "audioUrl": "audio/old-school/245_frank_i_see_blue_he_looks_glorious.mp3"
  },
  {
    "text": "A pretty nice little Saturday",
    "character": "",
    "audioUrl": "audio/old-school/246_frank_i_told_my_wife_i_wouldn_t_drink_tonight_besides_i_got.mp3"
  },
  {
    "text": "A whole meal of food",
    "character": "",
    "audioUrl": "audio/old-school/247_frank_i_ll_be_in_the_neighborhood_later_on_and_i_was_wonderi.mp3"
  },
  {
    "text": "Now I look like a jackass",
    "character": "",
    "audioUrl": "audio/old-school/248_frank_jerry_are_you_a_statistics_major_or_something_jerry_ac.mp3"
  },
  {
    "text": "Bring your green hat!",
    "character": "",
    "audioUrl": "audio/old-school/249_frank_no_it_s_cool_man_bring_your_green_hat.mp3"
  },
  {
    "text": "Nurse or cheerleader?",
    "character": "",
    "audioUrl": "audio/old-school/250_frank_so_what_do_you_guys_like_better_nurse_or_cheerleader_o.mp3"
  },
  {
    "text": "That's how you debate",
    "character": "",
    "audioUrl": "audio/old-school/251_frank_that_s_how_you_do_it_that_s_how_you_debate.mp3"
  },
  {
    "text": "I have to run it by Marissa",
    "character": "",
    "audioUrl": "audio/old-school/252_frank_yea_i_m_cool_either_way_i_just_have_to_run_it_by_maris.mp3"
  },
  {
    "text": "I'm here for the gangbang",
    "character": "",
    "audioUrl": "audio/old-school/261_gang_bang_guy_hello_mitch_yeah_gang_bang_guy_i_m_here_for_th.mp3"
  },
  {
    "text": "Why I have a lazy eye",
    "character": "",
    "audioUrl": "audio/old-school/262_garry_oh_that_s_funny_to_you_you_won_t_be_laughing_when_some.mp3"
  },
  {
    "text": "I saw a waitress taking an order",
    "character": "",
    "audioUrl": "audio/old-school/435_i_happened_to_look_over_during_the_meal_and_see_a_waitress_t.mp3"
  },
  {
    "text": "Still think I'm cool?",
    "character": "",
    "audioUrl": "audio/old-school/441_i_hope_you_ll_still_think_i_m_cool_even_without_all_this.mp3"
  },
  {
    "text": "Forget all the normal rules",
    "character": "",
    "audioUrl": "audio/old-school/542_in_other_words_forget_all_the_normal_rules_that_apply_to_bot.mp3"
  },
  {
    "text": "So we're screwed",
    "character": "",
    "audioUrl": "audio/old-school/546_industrial_size_cans_will_take_up_to_3_to_4_business_days_so.mp3"
  },
  {
    "text": "A loose affiliation",
    "character": "",
    "audioUrl": "audio/old-school/592_jerry_what_sort_of_actual_association_will_you_have_with_the.mp3"
  },
  {
    "text": "We're going streaking!",
    "character": "",
    "audioUrl": "audio/old-school/647_marissa_after_seeing_frank_running_naked_along_the_streets_s.mp3"
  },
  {
    "text": "You forgot your own birthday",
    "character": "",
    "audioUrl": "audio/old-school/648_marissa_listen_i_m_sorry_i_didn_t_call_you_on_your_birthday.mp3"
  },
  {
    "text": "Took the restrictor plate off",
    "character": "",
    "audioUrl": "audio/old-school/649_marissa_that_s_really_loud_frank_yeah_thanks_took_the_restri.mp3"
  },
  {
    "text": "It's guy code",
    "character": "",
    "audioUrl": "audio/old-school/650_mark_what_are_you_gonna_do_tell_on_me_you_know_you_can_t_bud.mp3"
  },
  {
    "text": "The answer, ladies, is trust",
    "character": "",
    "audioUrl": "audio/old-school/664_mitch_martin_at_this_point_you_may_be_asking_yourself_why_am.mp3"
  },
  {
    "text": "Denver, the sunshine state",
    "character": "",
    "audioUrl": "audio/old-school/665_mitch_martin_denver_the_sunshine_state_gorgeous.mp3"
  },
  {
    "text": "True love is hard to find",
    "character": "",
    "audioUrl": "audio/old-school/666_mitch_martin_true_love_is_hard_to_find_sometimes_you_think_y.mp3"
  },
  {
    "text": "I just want some sleep",
    "character": "",
    "audioUrl": "audio/old-school/673_mitch_all_i_want_to_do_is_get_some_fucking_sleep.mp3"
  },
  {
    "text": "Locked you in the dumpster",
    "character": "",
    "audioUrl": "audio/old-school/674_mitch_beanie_you_remember_cheese_beanie_oh_yeah_cheeeeese_di.mp3"
  },
  {
    "text": "Columbus wasn't looking for America",
    "character": "",
    "audioUrl": "audio/old-school/675_mitch_i_wasn_t_looking_for_a_girl_like_that_beanie_well_colu.mp3"
  },
  {
    "text": "Just say earmuffs",
    "character": "",
    "audioUrl": "audio/old-school/676_mitch_i_ve_had_a_hell_of_a_day_and_even_worse_week_and_all_i.mp3"
  },
  {
    "text": "Is this the first time?",
    "character": "",
    "audioUrl": "audio/old-school/677_mitch_please_be_honest_with_me_tell_me_this_is_the_first_tim.mp3"
  },
  {
    "text": "I'm the Dean",
    "character": "",
    "audioUrl": "audio/old-school/678_mitch_so_what_are_you_campus_security_dean_pritchard_try_aga.mp3"
  },
  {
    "text": "I'm 30 years old",
    "character": "",
    "audioUrl": "audio/old-school/679_mitch_this_is_my_house_i_live_here_beanie_i_m_30_years_old_n.mp3"
  },
  {
    "text": "That's Blue",
    "character": "",
    "audioUrl": "audio/old-school/680_mitch_who_s_this_guy_beanie_oh_that_s_blue_an_old_navy_vet_w.mp3"
  },
  {
    "text": "Cheese, is that you?",
    "character": "",
    "audioUrl": "audio/old-school/681_mitch_wow_cheese_is_that_you_dean_pritchard_hello_mitch_bern.mp3"
  },
  {
    "text": "Some hot sailor from TGI Friday's",
    "character": "",
    "audioUrl": "audio/old-school/767_or_some_hot_sailor_you_met_at_tgi_friday_s_a_couple_months_a.mp3"
  },
  {
    "text": "Teach a blow job class",
    "character": "",
    "audioUrl": "audio/old-school/769_our_friend_ashley_had_this_guy_come_over_and_teach_a_blow_jo.mp3"
  },
  {
    "text": "The most powerful tranq gun",
    "character": "",
    "audioUrl": "audio/old-school/774_peppers_she_s_a_beauty_ain_t_she_frank_yeah_what_kind_of_gun.mp3"
  },
  {
    "text": "You got a dart in your neck",
    "character": "",
    "audioUrl": "audio/old-school/775_peppers_you_should_pull_that_out_frank_wait_pull_what_out_pe.mp3"
  },
  {
    "text": "End up workin' at Red Lobster",
    "character": "",
    "audioUrl": "audio/old-school/846_spanish_damn_i_gonna_end_up_workin_at_red_lobster_frat_broth.mp3"
  },
  {
    "text": "Can't have anyone freak out",
    "character": "",
    "audioUrl": "audio/old-school/889_that_s_right_we_can_t_have_anyone_freak_out_out_there_okay.mp3"
  },
  {
    "text": "A great shock to me",
    "character": "",
    "audioUrl": "audio/old-school/897_the_actions_taken_by_the_student_council_have_come_as_a_grea.mp3"
  },
  {
    "text": "Last I heard, you'd moved",
    "character": "",
    "audioUrl": "audio/old-school/908_the_last_time_that_i_had_heard_you_had_moved_to.mp3"
  },
  {
    "text": "A nest in a tree of trust",
    "character": "",
    "audioUrl": "audio/old-school/917_therapist_frank_this_is_a_safe_place_a_place_where_we_can_fe.mp3"
  },
  {
    "text": "For the Godfather, it's on the house",
    "character": "",
    "audioUrl": "audio/old-school/985_waiter_and_don_t_worry_for_the_godfather_it_s_always_on_the.mp3"
  },
  {
    "text": "Love, it's a motherfucker, huh?",
    "character": "",
    "audioUrl": "audio/old-school/986_waiter_love_it_s_a_motherfucker_huh.mp3"
  },
  {
    "text": "Pie and coffee with a living legend",
    "character": "",
    "audioUrl": "audio/old-school/987_waiter_you_are_beautiful_but_no_offense_he_he_is_the_king_yo.mp3"
  },
  {
    "text": "This prom committee thing",
    "character": "",
    "audioUrl": "audio/old-school/1001_we_gotta_run_cause_we_got_this_prom_committee_thing_so_i_ll.mp3"
  },
  {
    "text": "Streaking through the quad",
    "character": "",
    "audioUrl": "audio/old-school/1016_we_re_going_streaking_through_the_quad_and_into_the_gymnasiu.mp3"
  },
  {
    "text": "Every now and then I fall apart",
    "character": "",
    "audioUrl": "audio/old-school/1030_wedding_singer_singing_fuckin_every_now_and_then_i_fall_apar.mp3"
  },
  {
    "text": "My mom's gonna kill me",
    "character": "",
    "audioUrl": "audio/old-school/1031_weensie_after_learning_he_s_going_to_be_expelled_listen_this.mp3"
  },
  {
    "text": "Feeling a little confused",
    "character": "",
    "audioUrl": "audio/old-school/1039_well_i_guess_i_deep_down_i_m_feeling_a_little_confused.mp3"
  },
  {
    "text": "She showed me the knife",
    "character": "",
    "audioUrl": "audio/old-school/1088_when_i_left_she_said_weensie_if_you_screw_this_up_i_ll_kill.mp3"
  },
  {
    "text": "Why does the cinderblock have a string?",
    "character": "",
    "audioUrl": "audio/old-school/1109_why_does_this_cinderblock_have_a_long_piece_of_string.mp3"
  },
  {
    "text": "I'll fucking kill you. I'm kidding",
    "character": "",
    "audioUrl": "audio/old-school/1118_woman_holding_a_grocery_bag_what_s_going_on_frank_you_tell_a.mp3"
  },
  {
    "text": "Intense mental and physical strain",
    "character": "",
    "audioUrl": "audio/old-school/1220_you_re_all_going_to_experience_intense_mental_and_physical_s.mp3"
  },
  {
    "text": "See you tomorrow night",
    "character": "",
    "audioUrl": "audio/old-school/1330_that_sounds_awesome_see_you_tomorrow_night.mp3"
  },
  {
    "text": "Keeping busy",
    "character": "",
    "audioUrl": "audio/old-school/1343_what_have_you_been_doing_i_ve_been_keeping_busy.mp3"
  },
  {
    "text": "Just ring the bell, you pansy",
    "character": "",
    "audioUrl": "audio/old-school/1365_two_girls_are_topless_in_the_pool_of_ky_jelly_frank_are_you.mp3"
  },
  {
    "text": "Ah ah ah!",
    "character": "",
    "audioUrl": "audio/old-school/1367_ah_ah_ah.mp3"
  },
  {
    "text": "And the moment's gone",
    "character": "",
    "audioUrl": "audio/old-school/1408_only_for_a_moment_and_the_moment_s_gone.mp3"
  },
  {
    "text": "Sparkling, clear and lovely",
    "character": "",
    "audioUrl": "audio/old-school/1413_sparkling_clear_and_lovely.mp3"
  },
  {
    "text": "Within the sound of silence",
    "character": "",
    "audioUrl": "audio/old-school/1417_within_the_sound_of_silence.mp3"
  }
];
