// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "Both of my best friends",
    "character": "",
    "audioUrl": "audio/pineapple-express/005_both_of_my_best_friends.mp3"
  },
  {
    "text": "Everyone Should Smoke It",
    "character": "",
    "audioUrl": "audio/pineapple-express/009_everyone_should_smoke_it.mp3"
  },
  {
    "text": "Heard that, wish I didn't",
    "character": "",
    "audioUrl": "audio/pineapple-express/014_heard_that_wish_i_didn_t.mp3"
  },
  {
    "text": "High as a fucking kite",
    "character": "",
    "audioUrl": "audio/pineapple-express/017_high_as_a_fucking_kite.mp3"
  },
  {
    "text": "I Don't Trust Him",
    "character": "",
    "audioUrl": "audio/pineapple-express/018_i_don_t_trust_him.mp3"
  },
  {
    "text": "I Don't Wanna Do This",
    "character": "",
    "audioUrl": "audio/pineapple-express/019_i_don_t_wanna_do_this.mp3"
  },
  {
    "text": "I feel like a slice of butter",
    "character": "",
    "audioUrl": "audio/pineapple-express/020_i_feel_like_a_slice_of_butter.mp3"
  },
  {
    "text": "I made a mistake",
    "character": "",
    "audioUrl": "audio/pineapple-express/021_i_made_a_mistake.mp3"
  },
  {
    "text": "I Still Don't Understand",
    "character": "",
    "audioUrl": "audio/pineapple-express/023_i_still_don_t_understand.mp3"
  },
  {
    "text": "I wanna be inside you homes",
    "character": "",
    "audioUrl": "audio/pineapple-express/024_i_wanna_be_inside_you_homes.mp3"
  },
  {
    "text": "I'm Taking These With Me",
    "character": "",
    "audioUrl": "audio/pineapple-express/025_i_m_taking_these_with_me.mp3"
  },
  {
    "text": "It's a cold sore",
    "character": "",
    "audioUrl": "audio/pineapple-express/027_it_s_a_cold_sore.mp3"
  },
  {
    "text": "It's Like God's ******",
    "character": "",
    "audioUrl": "audio/pineapple-express/028_it_s_like_god_s.mp3"
  },
  {
    "text": "It's my cat's birthday today",
    "character": "",
    "audioUrl": "audio/pineapple-express/029_it_s_my_cat_s_birthday_today.mp3"
  },
  {
    "text": "It's my cats birthday today",
    "character": "",
    "audioUrl": "audio/pineapple-express/030_it_s_my_cats_birthday_today.mp3"
  },
  {
    "text": "Kill You And Some",
    "character": "",
    "audioUrl": "audio/pineapple-express/031_kill_you_and_some.mp3"
  },
  {
    "text": "Mature for her age",
    "character": "",
    "audioUrl": "audio/pineapple-express/034_mature_for_her_age.mp3"
  },
  {
    "text": "Monkey's out of the bottle",
    "character": "",
    "audioUrl": "audio/pineapple-express/035_monkey_s_out_of_the_bottle.mp3"
  },
  {
    "text": "Not Ready For Marriage",
    "character": "",
    "audioUrl": "audio/pineapple-express/036_not_ready_for_marriage.mp3"
  },
  {
    "text": "Oh I Made A Mistake",
    "character": "",
    "audioUrl": "audio/pineapple-express/037_oh_i_made_a_mistake.mp3"
  },
  {
    "text": "Pineapple express come on down",
    "character": "",
    "audioUrl": "audio/pineapple-express/040_pineapple_express_come_on_down.mp3"
  },
  {
    "text": "Pineapple Express prostitute gun",
    "character": "",
    "audioUrl": "audio/pineapple-express/041_pineapple_express_prostitute_gun.mp3"
  },
  {
    "text": "Safety First, then Teamwork",
    "character": "",
    "audioUrl": "audio/pineapple-express/042_safety_first_then_teamwork.mp3"
  },
  {
    "text": "Special Time With Me",
    "character": "",
    "audioUrl": "audio/pineapple-express/049_special_time_with_me.mp3"
  },
  {
    "text": "Stuff your sorries in a sack bro",
    "character": "",
    "audioUrl": "audio/pineapple-express/050_stuff_your_sorries_in_a_sack_bro.mp3"
  },
  {
    "text": "That is good weed!",
    "character": "",
    "audioUrl": "audio/pineapple-express/052_that_is_good_weed.mp3"
  },
  {
    "text": "The answer I'm looking for",
    "character": "",
    "audioUrl": "audio/pineapple-express/054_the_answer_i_m_looking_for.mp3"
  },
  {
    "text": "Threw Up On My Printer",
    "character": "",
    "audioUrl": "audio/pineapple-express/056_threw_up_on_my_printer.mp3"
  },
  {
    "text": "Thumb is My ****",
    "character": "",
    "audioUrl": "audio/pineapple-express/058_thumb_is_my.mp3"
  },
  {
    "text": "Time to suck today's dick",
    "character": "",
    "audioUrl": "audio/pineapple-express/059_time_to_suck_today_s_dick.mp3"
  },
  {
    "text": "Tryna get a motherfuckin scholarship",
    "character": "",
    "audioUrl": "audio/pineapple-express/060_tryna_get_a_motherfuckin_scholarship.mp3"
  },
  {
    "text": "What the fuck man?!",
    "character": "",
    "audioUrl": "audio/pineapple-express/063_what_the_fuck_man.mp3"
  },
  {
    "text": "Ya'll wanna buy some drugs?",
    "character": "",
    "audioUrl": "audio/pineapple-express/064_ya_ll_wanna_buy_some_drugs.mp3"
  },
  {
    "text": "You ain't got no style, motherfucker",
    "character": "",
    "audioUrl": "audio/pineapple-express/065_you_ain_t_got_no_style_motherfucker.mp3"
  },
  {
    "text": "You ate a box of nerds out of her butthole",
    "character": "",
    "audioUrl": "audio/pineapple-express/066_you_ate_a_box_of_nerds_out_of_her_butthole.mp3"
  },
  {
    "text": "You didn't even have herpes",
    "character": "",
    "audioUrl": "audio/pineapple-express/067_you_didn_t_even_have_herpes.mp3"
  },
  {
    "text": "You Killed Him Man",
    "character": "",
    "audioUrl": "audio/pineapple-express/068_you_killed_him_man.mp3"
  },
  {
    "text": "You know what today is?",
    "character": "",
    "audioUrl": "audio/pineapple-express/069_you_know_what_today_is.mp3"
  },
  {
    "text": "You Torch Me Please",
    "character": "",
    "audioUrl": "audio/pineapple-express/070_you_torch_me_please.mp3"
  },
  {
    "text": "Your Cats Going To Heaven",
    "character": "",
    "audioUrl": "audio/pineapple-express/073_your_cats_going_to_heaven.mp3"
  },
  {
    "text": "Your dick, my mouth",
    "character": "",
    "audioUrl": "audio/pineapple-express/074_your_dick_my_mouth.mp3"
  },
  {
    "text": "2 And A Half Girls",
    "character": "",
    "audioUrl": "audio/pineapple-express/075_2_and_a_half_girls.mp3"
  }
];
