// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "I cut that grass for free",
    "character": "",
    "audioUrl": "audio/forrest-gump/001_an_cause_i_was_in_gov_zillionaire_and_i_like_doing_it_so_muc.mp3"
  },
  {
    "text": "He was a mean dog",
    "character": "",
    "audioUrl": "audio/forrest-gump/002_and_scared_or_what_i_don_t_know_but_i_think_it_was_her_grand.mp3"
  },
  {
    "text": "One less thing",
    "character": "",
    "audioUrl": "audio/forrest-gump/003_and_so_then_i_got_a_call_from_him_saying_we_don_t_have_to_wo.mp3"
  },
  {
    "text": "And that's all I had to say about that",
    "character": "",
    "audioUrl": "audio/forrest-gump/004_and_that_s_all_i_had_to_say_about_that.mp3"
  },
  {
    "text": "He had to go pee",
    "character": "",
    "audioUrl": "audio/forrest-gump/005_arthur_congratulations_how_do_you_feel_i_gotta_pay_i_believe.mp3"
  },
  {
    "text": "Not raccoons, you idiot",
    "character": "",
    "audioUrl": "audio/forrest-gump/006_at_the_moment_you_chase_him_off_with_the_group_not_raccoons.mp3"
  },
  {
    "text": "Bit me directly in the buttocks",
    "character": "",
    "audioUrl": "audio/forrest-gump/007_bit_me_directly_in_the_buttocks.mp3"
  },
  {
    "text": "Black Panther party",
    "character": "",
    "audioUrl": "audio/forrest-gump/008_black_panther_party.mp3"
  },
  {
    "text": "Come on Forrest, you can do it",
    "character": "",
    "audioUrl": "audio/forrest-gump/009_come_on_forrest_you_can_do_it.mp3"
  },
  {
    "text": "A million and a half of these",
    "character": "",
    "audioUrl": "audio/forrest-gump/010_do_you_want_a_chocolate_i_could_eat_about_a_million_and_a_ha.mp3"
  },
  {
    "text": "Swinging my hips",
    "character": "",
    "audioUrl": "audio/forrest-gump/011_doing_nothing_but_i_like_that_guitar_it_sounded_good_i_start.mp3"
  },
  {
    "text": "Done, drill sergeant",
    "character": "",
    "audioUrl": "audio/forrest-gump/012_done_drill_sergeant.mp3"
  },
  {
    "text": "Dr Peppers",
    "character": "",
    "audioUrl": "audio/forrest-gump/013_dr_peppers.mp3"
  },
  {
    "text": "Mama was a real smart lady",
    "character": "",
    "audioUrl": "audio/forrest-gump/014_every_place_like_that_that_s_how_me_and_momma_got_money_mama.mp3"
  },
  {
    "text": "Running for no reason",
    "character": "",
    "audioUrl": "audio/forrest-gump/015_firm_offer_animals_they_just_couldn_t_believe_that_somebody.mp3"
  },
  {
    "text": "Ping pong came natural to me",
    "character": "",
    "audioUrl": "audio/forrest-gump/016_for_some_reason_ping_pong_canberra_natural_to_me_nvidia_comp.mp3"
  },
  {
    "text": "Talkin shrimp",
    "character": "",
    "audioUrl": "audio/forrest-gump/017_forrest_and_bubba_talkin_shrimp.mp3"
  },
  {
    "text": "Graduates",
    "character": "",
    "audioUrl": "audio/forrest-gump/018_forrest_gump_graduates.mp3"
  },
  {
    "text": "Sneaking in",
    "character": "",
    "audioUrl": "audio/forrest-gump/020_forrest_gump_sneaking_in.mp3"
  },
  {
    "text": "Forrest! Run!",
    "character": "",
    "audioUrl": "audio/forrest-gump/021_forrest_run.mp3"
  },
  {
    "text": "Nice, you got air conditioning",
    "character": "",
    "audioUrl": "audio/forrest-gump/022_got_off_work_it_s_nice_you_got_air_conditioning.mp3"
  },
  {
    "text": "Happy New Year, Lieutenant Dan!",
    "character": "",
    "audioUrl": "audio/forrest-gump/023_happy_new_year_lieutenant_dan.mp3"
  },
  {
    "text": "Have a nice day",
    "character": "",
    "audioUrl": "audio/forrest-gump/024_have_a_nice_day.mp3"
  },
  {
    "text": "Have you found Jesus yet, Gump?",
    "character": "",
    "audioUrl": "audio/forrest-gump/025_have_you_found_jesus_yet_gump.mp3"
  },
  {
    "text": "Have you found Jesus yet?",
    "character": "",
    "audioUrl": "audio/forrest-gump/026_have_you_found_jesus_yet_no_i_don_t_know_if_suppose_be_looki.mp3"
  },
  {
    "text": "He's stupid but he sure is fast!",
    "character": "",
    "audioUrl": "audio/forrest-gump/027_he_s_stupid_but_he_sure_is_fast.mp3"
  },
  {
    "text": "That's an order",
    "character": "",
    "audioUrl": "audio/forrest-gump/029_here_goddamnit_that_s_an_order_hot_guy_at_5_baba.mp3"
  },
  {
    "text": "I gotta pee",
    "character": "",
    "audioUrl": "audio/forrest-gump/031_i_gotta_pee.mp3"
  },
  {
    "text": "I gotta pee",
    "character": "",
    "audioUrl": "audio/forrest-gump/033_i_gotta_pee.mp3"
  },
  {
    "text": "I know what love is",
    "character": "",
    "audioUrl": "audio/forrest-gump/034_i_know_what_love_is.mp3"
  },
  {
    "text": "I like that guitar",
    "character": "",
    "audioUrl": "audio/forrest-gump/035_i_like_that_guitar_it_sounded_good.mp3"
  },
  {
    "text": "I miss you, Jenny",
    "character": "",
    "audioUrl": "audio/forrest-gump/036_i_miss_you_jenny.mp3"
  },
  {
    "text": "I even played in my sleep",
    "character": "",
    "audioUrl": "audio/forrest-gump/038_i_played_ping_pong_so_much_i_even_played_it_in_my_sleep.mp3"
  },
  {
    "text": "I played all the time",
    "character": "",
    "audioUrl": "audio/forrest-gump/039_i_played_thankful_even_when_i_didn_t_have_anyone_to_play_pin.mp3"
  },
  {
    "text": "Go home to Greenbow Alabama",
    "character": "",
    "audioUrl": "audio/forrest-gump/040_i_think_i_think_you_should_go_home_to_greenbow_alabama.mp3"
  },
  {
    "text": "Fight the Communists with ping pong",
    "character": "",
    "audioUrl": "audio/forrest-gump/041_i_thought_i_was_going_back_to_vietnam_but_instead_they_decid.mp3"
  },
  {
    "text": "Where were you hit?",
    "character": "",
    "audioUrl": "audio/forrest-gump/042_i_understand_you_were_woon_did_where_were_you_hit_in_the_but.mp3"
  },
  {
    "text": "I wanted to be your boyfriend",
    "character": "",
    "audioUrl": "audio/forrest-gump/043_i_wanted_to_be_your_boyfriend.mp3"
  },
  {
    "text": "He liked the F word a lot",
    "character": "",
    "audioUrl": "audio/forrest-gump/045_i_m_going_to_bring_up_some_soldier_and_he_liked_to_say_the_f.mp3"
  },
  {
    "text": "I'm not a smart man",
    "character": "",
    "audioUrl": "audio/forrest-gump/046_i_m_not_a_smart_man.mp3"
  },
  {
    "text": "I'm pretty tired",
    "character": "",
    "audioUrl": "audio/forrest-gump/047_i_m_pretty_tired.mp3"
  },
  {
    "text": "I think I'll go home now",
    "character": "",
    "audioUrl": "audio/forrest-gump/048_i_m_pretty_tired_i_think_i_ll_go_home_now.mp3"
  },
  {
    "text": "I think I'll go home now",
    "character": "",
    "audioUrl": "audio/forrest-gump/049_i_m_pretty_tired_think_i_ll_go_home_now.mp3"
  },
  {
    "text": "Sorry I ruined your party",
    "character": "",
    "audioUrl": "audio/forrest-gump/050_i_m_sorry_i_ruined_your_new_year_eve_party_lieutenant_dan.mp3"
  },
  {
    "text": "Sorry I ruined your party",
    "character": "",
    "audioUrl": "audio/forrest-gump/051_i_m_sorry_i_ruined_your_new_years_eve_party.mp3"
  },
  {
    "text": "My first pair of shoes",
    "character": "",
    "audioUrl": "audio/forrest-gump/052_i_ve_won_a_lot_too_shoes_i_bet_if_i_think_about_it_real_hard.mp3"
  },
  {
    "text": "Ice cream",
    "character": "",
    "audioUrl": "audio/forrest-gump/053_ice_cream.mp3"
  },
  {
    "text": "Ice cream",
    "character": "",
    "audioUrl": "audio/forrest-gump/054_ice_cream_forrest_gump.mp3"
  },
  {
    "text": "Maybe it's both",
    "character": "",
    "audioUrl": "audio/forrest-gump/055_if_it_s_lieutenant_dan_i_don_t_know_if_we_each_have_a_destin.mp3"
  },
  {
    "text": "Rain coming straight up",
    "character": "",
    "audioUrl": "audio/forrest-gump/056_in_sideways_and_sometimes_rain_even_seem_to_come_straight_up.mp3"
  },
  {
    "text": "Got me right in the buttocks",
    "character": "",
    "audioUrl": "audio/forrest-gump/057_it_was_a_bullet_1a_bullet_that_jumped_up_in_bitch_oh_yes_sir.mp3"
  },
  {
    "text": "I was a national celebrity",
    "character": "",
    "audioUrl": "audio/forrest-gump/058_it_was_quite_bank_palm_when_i_got_home_i_was_a_national_cele.mp3"
  },
  {
    "text": "It's a household name",
    "character": "",
    "audioUrl": "audio/forrest-gump/059_it_s_a_household_name.mp3"
  },
  {
    "text": "It's a household name",
    "character": "",
    "audioUrl": "audio/forrest-gump/060_it_s_a_household_name.mp3"
  },
  {
    "text": "Jumped up and bit me",
    "character": "",
    "audioUrl": "audio/forrest-gump/061_jumped_up_and_bit_me.mp3"
  },
  {
    "text": "I like using my own paddle",
    "character": "",
    "audioUrl": "audio/forrest-gump/062_king_kong_stuff_one_man_even_left_a_check_for_25_000_if_you.mp3"
  },
  {
    "text": "Lieutenant Dan",
    "character": "",
    "audioUrl": "audio/forrest-gump/064_lieutenant_dan.mp3"
  },
  {
    "text": "Life is like a box of chocolates",
    "character": "",
    "audioUrl": "audio/forrest-gump/065_life_is_like_a_box_of_chocolates.mp3"
  },
  {
    "text": "Life is like a box of chocolates",
    "character": "",
    "audioUrl": "audio/forrest-gump/066_life_is_like_a_box_of_chocolates.mp3"
  },
  {
    "text": "Just a little white lie",
    "character": "",
    "audioUrl": "audio/forrest-gump/067_like_so_like_ping_pong_paddle_which_everybody_knows_is_true.mp3"
  },
  {
    "text": "Long run",
    "character": "",
    "audioUrl": "audio/forrest-gump/068_long_run.mp3"
  },
  {
    "text": "Long enough for the stars",
    "character": "",
    "audioUrl": "audio/forrest-gump/069_love_sometimes_it_will_stop_raining_long_enough_for_the_star.mp3"
  },
  {
    "text": "Dying is a part of life",
    "character": "",
    "audioUrl": "audio/forrest-gump/070_mama_always_said_diane_was_it_part_of_life_i_sure_wish_it_wa.mp3"
  },
  {
    "text": "Tell a lot by their shoes",
    "character": "",
    "audioUrl": "audio/forrest-gump/071_mom_always_said_there_s_an_awful_lot_you_could_tell_about_a.mp3"
  },
  {
    "text": "Must be hard being brothers",
    "character": "",
    "audioUrl": "audio/forrest-gump/072_must_be_hard_being_brothers_i_would_know.mp3"
  },
  {
    "text": "Must be hard being brothers",
    "character": "",
    "audioUrl": "audio/forrest-gump/073_must_be_hard_being_brothers_i_wouldnt_know.mp3"
  },
  {
    "text": "Never know what you're gonna get",
    "character": "",
    "audioUrl": "audio/forrest-gump/074_my_mom_always_said_life_was_like_a_box_of_chocolates_you_nev.mp3"
  },
  {
    "text": "Put the past behind you",
    "character": "",
    "audioUrl": "audio/forrest-gump/075_my_mom_always_said_you_got_to_put_the_past_behind_you_before.mp3"
  },
  {
    "text": "People call me Forrest Gump",
    "character": "",
    "audioUrl": "audio/forrest-gump/076_my_name_s_forrest_gump_people_call_me_forrest_gump.mp3"
  },
  {
    "text": "New legs",
    "character": "",
    "audioUrl": "audio/forrest-gump/077_new_legs.mp3"
  },
  {
    "text": "Glad we were here together",
    "character": "",
    "audioUrl": "audio/forrest-gump/078_no_what_what_i_m_glad_we_were_here_together_in_our_nation_s.mp3"
  },
  {
    "text": "Shrimpin is tough",
    "character": "",
    "audioUrl": "audio/forrest-gump/079_now_mother_told_me_everything_he_knew_about_shrimping_but_yo.mp3"
  },
  {
    "text": "Okay",
    "character": "",
    "audioUrl": "audio/forrest-gump/080_okay.mp3"
  },
  {
    "text": "Didn't quit for four months",
    "character": "",
    "audioUrl": "audio/forrest-gump/081_one_day_it_started_raining_and_it_didn_t_quit_for_four_month.mp3"
  },
  {
    "text": "Felt like running",
    "character": "",
    "audioUrl": "audio/forrest-gump/082_particular_reason_why_are_you_doing_this_felt_like_running.mp3"
  },
  {
    "text": "Run Forrest, run!",
    "character": "",
    "audioUrl": "audio/forrest-gump/084_run_forrest_run.mp3"
  },
  {
    "text": "Meeting the president",
    "character": "",
    "audioUrl": "audio/forrest-gump/085_say_now_the_really_good_thing_about_meeting_the_president_of.mp3"
  },
  {
    "text": "Seat's taken",
    "character": "",
    "audioUrl": "audio/forrest-gump/086_seat_s_taken.mp3"
  },
  {
    "text": "She tastes like cigarettes",
    "character": "",
    "audioUrl": "audio/forrest-gump/088_she_tastes_like_cigarettes.mp3"
  },
  {
    "text": "I'm going to beat me",
    "character": "",
    "audioUrl": "audio/forrest-gump/089_so_i_m_going_to_be_on_i_m_going_to_beat_me.mp3"
  },
  {
    "text": "Had himself a heart attack",
    "character": "",
    "audioUrl": "audio/forrest-gump/090_some_years_later_that_handsome_young_man_who_they_called_the.mp3"
  },
  {
    "text": "Somebody shot him",
    "character": "",
    "audioUrl": "audio/forrest-gump/091_some_years_later_that_nice_young_man_from_england_was_on_his.mp3"
  },
  {
    "text": "Must be hard being a King",
    "character": "",
    "audioUrl": "audio/forrest-gump/092_something_must_be_hard_being_a_king.mp3"
  },
  {
    "text": "Just aren't enough rocks",
    "character": "",
    "audioUrl": "audio/forrest-gump/093_sometimes_i_guess_there_just_aren_t_enough_rocks.mp3"
  },
  {
    "text": "Wait for the stars",
    "character": "",
    "audioUrl": "audio/forrest-gump/094_sometimes_we_just_sit_out_wait_for_the_stars.mp3"
  },
  {
    "text": "Sorry about your Black Panther party",
    "character": "",
    "audioUrl": "audio/forrest-gump/095_sorry_i_had_a_fight_in_the_middle_of_your_black_panther_part.mp3"
  },
  {
    "text": "Stupid is as stupid does",
    "character": "",
    "audioUrl": "audio/forrest-gump/096_stupid_is_as_stupid_does.mp3"
  },
  {
    "text": "That's all I have to say about that",
    "character": "",
    "audioUrl": "audio/forrest-gump/097_that_s_all_i_have_to_say_about_that.mp3"
  },
  {
    "text": "That's all I have to say about that",
    "character": "",
    "audioUrl": "audio/forrest-gump/098_that_s_all_i_have_to_say_about_that.mp3"
  },
  {
    "text": "That's all I have to say about that",
    "character": "",
    "audioUrl": "audio/forrest-gump/099_that_s_all_i_have_to_say_about_that.mp3"
  },
  {
    "text": "That's my boat",
    "character": "",
    "audioUrl": "audio/forrest-gump/100_that_s_my_boat.mp3"
  },
  {
    "text": "That's all I have to say about that",
    "character": "",
    "audioUrl": "audio/forrest-gump/101_thats_all_i_have_to_say_about_that.mp3"
  },
  {
    "text": "All the ice cream I could eat",
    "character": "",
    "audioUrl": "audio/forrest-gump/102_the_only_good_thing_about_being_woon_did_in_the_butt_talks_i.mp3"
  },
  {
    "text": "The sun come out",
    "character": "",
    "audioUrl": "audio/forrest-gump/103_this_one_day_we_was_out_walking_like_always_and_then_just_li.mp3"
  },
  {
    "text": "Those must be comfortable shoes",
    "character": "",
    "audioUrl": "audio/forrest-gump/104_those_must_be_comfortable_shoes_i_ll_bet_you_could_walk_all.mp3"
  },
  {
    "text": "Where the hell is this God of yours?",
    "character": "",
    "audioUrl": "audio/forrest-gump/105_tramp_where_the_hell_is_this_god_of_yours.mp3"
  },
  {
    "text": "You ran through dog shit",
    "character": "",
    "audioUrl": "audio/forrest-gump/106_wanna_help_me_jump_into_hello_man_you_just_ran_through_a_big.mp3"
  },
  {
    "text": "Waving Forrest Gump",
    "character": "",
    "audioUrl": "audio/forrest-gump/107_waving_forrest_gump.mp3"
  },
  {
    "text": "Every kind of rain there is",
    "character": "",
    "audioUrl": "audio/forrest-gump/108_we_been_through_every_kind_of_rain_there_is_little_better_st.mp3"
  },
  {
    "text": "No more worry about money",
    "character": "",
    "audioUrl": "audio/forrest-gump/109_we_don_t_have_to_worry_about_money_no_more.mp3"
  },
  {
    "text": "You got a cold?",
    "character": "",
    "audioUrl": "audio/forrest-gump/110_what_do_you_have_a_cough_due_to_cold.mp3"
  },
  {
    "text": "When I had to go, I went",
    "character": "",
    "audioUrl": "audio/forrest-gump/111_when_i_had_to_go_y_know_i_went.mp3"
  },
  {
    "text": "Will you marry me?",
    "character": "",
    "audioUrl": "audio/forrest-gump/112_will_you_marry_me_i_would_make_a_good_husband.mp3"
  },
  {
    "text": "You ain't got no legs, Lieutenant Dan",
    "character": "",
    "audioUrl": "audio/forrest-gump/114_you_aint_got_no_legs_lieutenant_dan.mp3"
  },
  {
    "text": "You call this a storm?",
    "character": "",
    "audioUrl": "audio/forrest-gump/115_you_call_this_a_storm.mp3"
  },
  {
    "text": "You call this a storm?",
    "character": "",
    "audioUrl": "audio/forrest-gump/116_you_call_this_a_storm.mp3"
  }
];
