// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "All you have to do is cosign",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/001_all_you_have_to_do_is_cosign_as_you_are_the_one_with_the_inc.mp3"
  },
  {
    "text": "Any responses?",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/002_any_responses.mp3"
  },
  {
    "text": "Anyone?",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/003_anyone.mp3"
  },
  {
    "text": "Anything?",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/004_anything.mp3"
  },
  {
    "text": "Bobby surprised sound",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/005_bobby_surprised_sound.mp3"
  },
  {
    "text": "Bobby, television.",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/006_bobby_television.mp3"
  },
  {
    "text": "Look in the adventure section",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/007_bobby_why_don_t_you_go_look_in_the_adventure_section_anythin.mp3"
  },
  {
    "text": "Can I sell guns here?",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/008_can_i_sell_guns_in_this_location.mp3"
  },
  {
    "text": "Let's get a dialog going",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/009_come_on_let_s_get_a_dialog_going.mp3"
  },
  {
    "text": "Cream cheese is cheese Bill",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/010_cream_cheese_is_cheese_bill.mp3"
  },
  {
    "text": "Bang bang bang",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/011_get_me_something_that_shoots_like_this_bang_bang_bang.mp3"
  },
  {
    "text": "Gun cocks",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/012_gun_cocks.mp3"
  },
  {
    "text": "I don't know",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/013_i_don_t_know.mp3"
  },
  {
    "text": "Raking in money",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/014_i_will_be_raking_in_money_with_one_hand_and_reading_my_book.mp3"
  },
  {
    "text": "Your thickest book please",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/015_i_d_like_your_thickest_book_please.mp3"
  },
  {
    "text": "In the mood for stimulating conversation",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/016_i_m_kind_of_in_the_mood_for_some_stimulating_conversation.mp3"
  },
  {
    "text": "In theory I reject this money",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/017_in_theory_i_reject_this_money_it_is_only_in_practice_that_i.mp3"
  },
  {
    "text": "Morning officer",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/018_morning_officer.mp3"
  },
  {
    "text": "No it's not, it's butter",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/019_no_it_s_not_it_s_butter.mp3"
  },
  {
    "text": "Oh",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/020_oh.mp3"
  },
  {
    "text": "Oh I can, and I will",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/021_oh_i_can_and_i_will.mp3"
  },
  {
    "text": "It's so juicy!",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/022_oh_my_god_it_s_so_juicy.mp3"
  },
  {
    "text": "What about my weekends?",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/023_oh_i_can_t_believe_it_what_am_i_going_to_do_with_my_weekends.mp3"
  },
  {
    "text": "Mind if I join you?",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/024_oh_mind_if_i_join_you.mp3"
  },
  {
    "text": "OK",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/025_ok.mp3"
  },
  {
    "text": "So that's it?",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/026_so_that_s_it.mp3"
  },
  {
    "text": "Shot off the gas valve",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/027_sometimes_the_boys_like_to_go_down_in_the_basement_and_test.mp3"
  },
  {
    "text": "Straight in back",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/028_straight_in_back.mp3"
  },
  {
    "text": "Hell of a weird sound",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/029_that_s_a_hell_of_a_weird_sound_i_never_made_that_before.mp3"
  },
  {
    "text": "Justice of the Unicorn",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/030_that_s_what_the_elves_call_justice_of_the_unicorn.mp3"
  },
  {
    "text": "Thatherton",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/031_thatherton.mp3"
  },
  {
    "text": "Well I... (weird sound)",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/032_well_i_weird_sound.mp3"
  },
  {
    "text": "Weird sound, never made that before",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/033_well_i_weird_sound_that_s_a_hell_of_a_weird_sound_i_never_ma.mp3"
  },
  {
    "text": "Ambience, right, ambience",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/034_what_do_you_call_it_peggy_ambience_right_ambience.mp3"
  },
  {
    "text": "What I sell is a lifestyle",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/035_what_i_sell_is_a_lifestyle.mp3"
  },
  {
    "text": "Take my word for it",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/036_why_won_t_you_take_my_word_for_this.mp3"
  },
  {
    "text": "Yep",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/037_yep.mp3"
  },
  {
    "text": "Yep",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/038_yep.mp3"
  },
  {
    "text": "Yes, yes",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/039_yes_yes.mp3"
  },
  {
    "text": "You can't do that",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/040_you_can_t_do_that.mp3"
  },
  {
    "text": "Perfect gun selling location",
    "character": "",
    "audioUrl": "audio/king-of-the-hill/041_you_know_this_is_a_perfect_gun_selling_location.mp3"
  }
];
