// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "ALRIGHT!",
    "character": "",
    "audioUrl": "audio/big-daddy/001_alright.mp3"
  },
  {
    "text": "Bring it on woman",
    "character": "",
    "audioUrl": "audio/big-daddy/002_bring_it_on_woman.mp3"
  },
  {
    "text": "Doing the Hibbity Dibbity",
    "character": "",
    "audioUrl": "audio/big-daddy/003_doing_the_hibbity_dibbity.mp3"
  },
  {
    "text": "Hell yes",
    "character": "",
    "audioUrl": "audio/big-daddy/004_hell_yes.mp3"
  },
  {
    "text": "Hey, I love you",
    "character": "",
    "audioUrl": "audio/big-daddy/005_hey_i_love_you.mp3"
  },
  {
    "text": "Hip Hop Anonymous",
    "character": "",
    "audioUrl": "audio/big-daddy/006_hip_hop_anonymous.mp3"
  },
  {
    "text": "I don't want to study",
    "character": "",
    "audioUrl": "audio/big-daddy/007_i_don_t_want_to_study.mp3"
  },
  {
    "text": "I wipe my own ass",
    "character": "",
    "audioUrl": "audio/big-daddy/008_i_wipe_my_own_ass.mp3"
  },
  {
    "text": "Loose skin and old balls. Gross",
    "character": "",
    "audioUrl": "audio/big-daddy/009_loose_skin_and_old_balls_gross.mp3"
  },
  {
    "text": "Not proposing are you?",
    "character": "",
    "audioUrl": "audio/big-daddy/010_not_proposing_are_you.mp3"
  },
  {
    "text": "Old Man River, zip it or I'll break your hip",
    "character": "",
    "audioUrl": "audio/big-daddy/011_old_man_river_zip_it_or_i_ll_break_your_hip.mp3"
  },
  {
    "text": "Please Don't Do This To Me",
    "character": "",
    "audioUrl": "audio/big-daddy/012_please_don_t_do_this_to_me.mp3"
  },
  {
    "text": "Prove it!",
    "character": "",
    "audioUrl": "audio/big-daddy/013_prove_it.mp3"
  },
  {
    "text": "Sausage McMuffin",
    "character": "",
    "audioUrl": "audio/big-daddy/014_sausage_mcmuffin.mp3"
  },
  {
    "text": "Scuba Steve, Damn You!",
    "character": "",
    "audioUrl": "audio/big-daddy/015_scuba_steve_damn_you.mp3"
  },
  {
    "text": "Stop yelling at me",
    "character": "",
    "audioUrl": "audio/big-daddy/016_stop_yelling_at_me.mp3"
  },
  {
    "text": "The Goddamn Jets",
    "character": "",
    "audioUrl": "audio/big-daddy/017_the_goddamn_jets.mp3"
  },
  {
    "text": "We wasted the good surprise on you",
    "character": "",
    "audioUrl": "audio/big-daddy/018_we_wasted_the_good_surprise_on_you.mp3"
  },
  {
    "text": "We're both losing weight",
    "character": "",
    "audioUrl": "audio/big-daddy/019_we_re_both_losing_weight.mp3"
  },
  {
    "text": "You gave him the easy ones",
    "character": "",
    "audioUrl": "audio/big-daddy/020_you_gave_him_the_easy_ones.mp3"
  },
  {
    "text": "You Give Him the Easy Ones",
    "character": "",
    "audioUrl": "audio/big-daddy/021_you_give_him_the_easy_ones.mp3"
  },
  {
    "text": "5 Year Plan: Don't Die",
    "character": "",
    "audioUrl": "audio/big-daddy/022_5_year_plan_don_t_die.mp3"
  }
];
