// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "All religion is a foolish answer to a foolish question",
    "character": "",
    "audioUrl": "audio/peaky-blinders/001_all_religion_is_a_foolish_answer_to_a_foolish_question.mp3"
  },
  {
    "text": "Because you are a fucking wop, mate",
    "character": "",
    "audioUrl": "audio/peaky-blinders/002_because_you_are_a_fucking_wop_mate.mp3"
  },
  {
    "text": "By order of the Peaky Blinders",
    "character": "",
    "audioUrl": "audio/peaky-blinders/003_by_order_of_the_peaky_blinders.mp3"
  },
  {
    "text": "Despite the temptation, no hoarding",
    "character": "",
    "audioUrl": "audio/peaky-blinders/004_despite_the_temptation_no_hoarding.mp3"
  },
  {
    "text": "Everyone's a whore, Grace",
    "character": "",
    "audioUrl": "audio/peaky-blinders/005_everyone_s_a_whore_grace.mp3"
  },
  {
    "text": "Gipsy scum",
    "character": "",
    "audioUrl": "audio/peaky-blinders/006_gipsy_scum.mp3"
  },
  {
    "text": "I am Billy Kimber",
    "character": "",
    "audioUrl": "audio/peaky-blinders/007_i_am_billy_kimber.mp3"
  },
  {
    "text": "I know what I know",
    "character": "",
    "audioUrl": "audio/peaky-blinders/008_i_know_what_i_know.mp3"
  },
  {
    "text": "I will remember everything",
    "character": "",
    "audioUrl": "audio/peaky-blinders/009_i_will_remember_everything.mp3"
  },
  {
    "text": "I'll tell on you to mum",
    "character": "",
    "audioUrl": "audio/peaky-blinders/010_if_you_try_to_sneak_out_i_ll_tell_on_you_to_mum.mp3"
  },
  {
    "text": "I'll tell mum (short)",
    "character": "",
    "audioUrl": "audio/peaky-blinders/011_if_you_try_to_sneak_out_i_ll_tell_on_you_to_mum_short.mp3"
  },
  {
    "text": "Intelligence is a valuable thing, my friend",
    "character": "",
    "audioUrl": "audio/peaky-blinders/012_intelligence_is_a_valuable_thing_my_friend.mp3"
  },
  {
    "text": "It is fucking awful, that stuff",
    "character": "",
    "audioUrl": "audio/peaky-blinders/013_it_is_fucking_awful_that_stuff.mp3"
  },
  {
    "text": "It was fucking biblical, mate",
    "character": "",
    "audioUrl": "audio/peaky-blinders/014_it_was_fucking_biblical_mate.mp3"
  },
  {
    "text": "Men and their cocks",
    "character": "",
    "audioUrl": "audio/peaky-blinders/015_men_and_their_cocks_never_seize_to_amaze_me.mp3"
  },
  {
    "text": "Today I'm gonna kill a man",
    "character": "",
    "audioUrl": "audio/peaky-blinders/016_my_name_is_thomas_shelby_and_today_im_gonna_kill_a_man.mp3"
  },
  {
    "text": "My suits are on the house",
    "character": "",
    "audioUrl": "audio/peaky-blinders/017_my_suits_are_on_the_house.mp3"
  },
  {
    "text": "No fighting",
    "character": "",
    "audioUrl": "audio/peaky-blinders/018_no_fighting.mp3"
  },
  {
    "text": "No fucking fighting",
    "character": "",
    "audioUrl": "audio/peaky-blinders/019_no_fucking_fighting.mp3"
  },
  {
    "text": "No fucking going out!",
    "character": "",
    "audioUrl": "audio/peaky-blinders/020_no_fucking_going_out.mp3"
  },
  {
    "text": "No fucking going out! (short)",
    "character": "",
    "audioUrl": "audio/peaky-blinders/021_no_fucking_going_out_short.mp3"
  },
  {
    "text": "Peaky Blinders",
    "character": "",
    "audioUrl": "audio/peaky-blinders/022_peaky_blinders.mp3"
  },
  {
    "text": "Stop fooking whingeing!",
    "character": "",
    "audioUrl": "audio/peaky-blinders/023_stop_fooking_whingeing.mp3"
  },
  {
    "text": "There's God, and the Peaky Blinders",
    "character": "",
    "audioUrl": "audio/peaky-blinders/024_there_is_god_and_there_are_the_peaky_blinders.mp3"
  },
  {
    "text": "Under new management",
    "character": "",
    "audioUrl": "audio/peaky-blinders/025_this_place_is_under_new_management.mp3"
  },
  {
    "text": "Wanted man",
    "character": "",
    "audioUrl": "audio/peaky-blinders/026_wanted_man.mp3"
  },
  {
    "text": "We are all quarantined",
    "character": "",
    "audioUrl": "audio/peaky-blinders/027_we_are_now_all_quarantined.mp3"
  },
  {
    "text": "Were you a man?",
    "character": "",
    "audioUrl": "audio/peaky-blinders/028_were_you_a_man.mp3"
  },
  {
    "text": "Whisky is good proofing water",
    "character": "",
    "audioUrl": "audio/peaky-blinders/029_whisky_is_good_proofing_water.mp3"
  },
  {
    "text": "Who is the boss?",
    "character": "",
    "audioUrl": "audio/peaky-blinders/030_who_is_the_boss.mp3"
  },
  {
    "text": "Who wants to be in heaven?",
    "character": "",
    "audioUrl": "audio/peaky-blinders/031_who_wants_to_be_in_heaven.mp3"
  },
  {
    "text": "A deal without negotiation",
    "character": "",
    "audioUrl": "audio/peaky-blinders/032_you_just_made_a_deal_without_a_negotiation_didn_t_ya.mp3"
  },
  {
    "text": "You need to be a man",
    "character": "",
    "audioUrl": "audio/peaky-blinders/033_you_need_to_be_a_man.mp3"
  },
  {
    "text": "And we're the Peaky Blinders",
    "character": "",
    "audioUrl": "audio/peaky-blinders/034_and_we_re_the_peaky_blinders.mp3"
  },
  {
    "text": "Thank me for saving your life",
    "character": "",
    "audioUrl": "audio/peaky-blinders/036_are_you_not_going_to_thank_me_for_saving_your_life_pass_me_c.mp3"
  },
  {
    "text": "Where's Tommy?",
    "character": "",
    "audioUrl": "audio/peaky-blinders/038_arthur_michael_michael_michael_arth_u_r_arthur_john_where_s.mp3"
  },
  {
    "text": "By order of the Peaky Blinders",
    "character": "",
    "audioUrl": "audio/peaky-blinders/041_by_order_of_the_peaky_blinders.mp3"
  },
  {
    "text": "By order of the Peaky Blinders",
    "character": "",
    "audioUrl": "audio/peaky-blinders/042_by_order_of_the_peaky_blinders.mp3"
  },
  {
    "text": "Cushion, Poll. Right.",
    "character": "",
    "audioUrl": "audio/peaky-blinders/043_cushion_poll_right.mp3"
  },
  {
    "text": "Door opens",
    "character": "",
    "audioUrl": "audio/peaky-blinders/045_door_opens_sniffling.mp3"
  },
  {
    "text": "Go! Go! Go!",
    "character": "",
    "audioUrl": "audio/peaky-blinders/046_go_go_go_speaking_in_italian.mp3"
  },
  {
    "text": "Good morning, Mrs Ross",
    "character": "",
    "audioUrl": "audio/peaky-blinders/047_good_morning_mrs_ross_have_a_seat.mp3"
  },
  {
    "text": "Good morning, sisters. Let us pray.",
    "character": "",
    "audioUrl": "audio/peaky-blinders/048_good_morning_sisters_let_us_pray.mp3"
  },
  {
    "text": "Goodbye, Mrs Ross",
    "character": "",
    "audioUrl": "audio/peaky-blinders/049_goodbye_mrs_ross_chair_creaks_footsteps_recede_th_eme_music.mp3"
  },
  {
    "text": "Now he has no face",
    "character": "",
    "audioUrl": "audio/peaky-blinders/051_he_just_listened_and_now_he_has_no_face_may_you_peaky_blinde.mp3"
  },
  {
    "text": "He was in a tunnel collapse",
    "character": "",
    "audioUrl": "audio/peaky-blinders/052_he_was_in_the_war_he_was_in_a_tunnel_collapse_gasping_he_won.mp3"
  },
  {
    "text": "Time to get off the stage",
    "character": "",
    "audioUrl": "audio/peaky-blinders/055_i_think_it_s_about_time_we_got_off_the_stage_old_man_the_chi.mp3"
  },
  {
    "text": "Just point and pull the trigger",
    "character": "",
    "audioUrl": "audio/peaky-blinders/057_i_will_shoot_him_myself_tommy_just_teach_me_how_to_shoot_sco.mp3"
  },
  {
    "text": "It starts when you stop",
    "character": "",
    "audioUrl": "audio/peaky-blinders/060_i_ve_been_to_a_doctor_on_your_behalf_it_starts_when_you_stop.mp3"
  },
  {
    "text": "If I die, you die",
    "character": "",
    "audioUrl": "audio/peaky-blinders/061_i_ve_made_arrangements_with_men_i_trust_if_i_should_die_then.mp3"
  },
  {
    "text": "In the bleak midwinter",
    "character": "",
    "audioUrl": "audio/peaky-blinders/063_in_the_bleak_midwinter.mp3"
  },
  {
    "text": "Revenge on Tommy Shelby",
    "character": "",
    "audioUrl": "audio/peaky-blinders/067_it_was_the_ambitions_and_strategies_of_one_man_that_caused_t.mp3"
  },
  {
    "text": "Stay inside, don't come out",
    "character": "",
    "audioUrl": "audio/peaky-blinders/068_it_s_all_right_love_it_s_all_right_come_inside_come_inside_c.mp3"
  },
  {
    "text": "I need to walk",
    "character": "",
    "audioUrl": "audio/peaky-blinders/070_let_s_let_s_go_inside_we_ll_work_it_out_have_a_drink_i_need.mp3"
  },
  {
    "text": "No rest in this world",
    "character": "",
    "audioUrl": "audio/peaky-blinders/072_mr_shelby_you_re_meant_to_be_resting_i_have_learnt_something.mp3"
  },
  {
    "text": "My bullets ache for your head",
    "character": "",
    "audioUrl": "audio/peaky-blinders/074_mr_shelby_my_bullets_ache_to_get_inside_your_tinker_head.mp3"
  },
  {
    "text": "My name is not Shelby!",
    "character": "",
    "audioUrl": "audio/peaky-blinders/075_no_no_it_s_all_right_miss_shelby_we_work_with_tommy_we_re_pe.mp3"
  },
  {
    "text": "You're not afraid of me",
    "character": "",
    "audioUrl": "audio/peaky-blinders/076_nutley_your_brothers_came_to_my_house_they_said_the_peaky_bl.mp3"
  },
  {
    "text": "Clean up when I come back",
    "character": "",
    "audioUrl": "audio/peaky-blinders/077_polly_clean_up_when_i_come_back_when_i_come_backi_gotta_be_c.mp3"
  },
  {
    "text": "We don't open for two hours",
    "character": "",
    "audioUrl": "audio/peaky-blinders/082_service_knocking_we_don_t_open_two_more_hours_you_come_back.mp3"
  },
  {
    "text": "The girl who tells fortunes",
    "character": "",
    "audioUrl": "audio/peaky-blinders/083_sir_this_is_her_the_girl_who_tells_fortunes.mp3"
  },
  {
    "text": "What do you want? Fear",
    "character": "",
    "audioUrl": "audio/peaky-blinders/084_so_what_is_it_you_want_from_a_simple_working_man_fear.mp3"
  },
  {
    "text": "The man I can't defeat",
    "character": "",
    "audioUrl": "audio/peaky-blinders/085_talk_to_me_maybe_i_ve_found_him_arthur_the_man_i_can_t_defea.mp3"
  },
  {
    "text": "Grace Shelby Institute is acceptable",
    "character": "",
    "audioUrl": "audio/peaky-blinders/086_tell_the_counsellor_the_name_grace_shelby_institute_is_accep.mp3"
  },
  {
    "text": "The horse is Monaghan Boy",
    "character": "",
    "audioUrl": "audio/peaky-blinders/087_the_horse_s_name_is_monaghan_boy_kempton_3_00_monday_you_lad.mp3"
  },
  {
    "text": "Introduce themselves",
    "character": "",
    "audioUrl": "audio/peaky-blinders/089_they_say_they_haven_t_even_heard_of_us_so_tell_aberama_and_i.mp3"
  },
  {
    "text": "A magic spell to win",
    "character": "",
    "audioUrl": "audio/peaky-blinders/090_they_re_doing_a_magic_spell_to_make_it_win_a_race.mp3"
  },
  {
    "text": "A list of things I want done",
    "character": "",
    "audioUrl": "audio/peaky-blinders/091_this_is_a_list_on_the_other_things_iwant_doing_that_s_all_cl.mp3"
  },
  {
    "text": "This letter says Dad's dead",
    "character": "",
    "audioUrl": "audio/peaky-blinders/092_this_letter_says_that_dad_s_dead.mp3"
  },
  {
    "text": "Tommy coughs",
    "character": "",
    "audioUrl": "audio/peaky-blinders/094_tommy_grunts_and_retches_he_coughs.mp3"
  },
  {
    "text": "A woman who I love",
    "character": "",
    "audioUrl": "audio/peaky-blinders/095_tommy_0h_there_s_a_woman_yeah_a_woman_who_i_love_and_i_got_c.mp3"
  },
  {
    "text": "On his own doorstep",
    "character": "",
    "audioUrl": "audio/peaky-blinders/096_tommy_is_it_him_arthur_yeah_on_his_own_doorstep_his_own_fuck.mp3"
  },
  {
    "text": "Who are we? Let's go.",
    "character": "",
    "audioUrl": "audio/peaky-blinders/100_who_are_we_let_s_go.mp3"
  },
  {
    "text": "Who takes the throne?",
    "character": "",
    "audioUrl": "audio/peaky-blinders/101_who_s_going_to_take_the_throne_eh_black_cat_dreams_are_never.mp3"
  },
  {
    "text": "You will be king",
    "character": "",
    "audioUrl": "audio/peaky-blinders/102_you_and_i_will_be_done_thomas_and_you_will_be_king.mp3"
  },
  {
    "text": "You look unsteady, Mr Shelby",
    "character": "",
    "audioUrl": "audio/peaky-blinders/103_you_look_a_little_unsteady_mr_shelby_take_a_seat.mp3"
  },
  {
    "text": "Your surprises have just begun",
    "character": "",
    "audioUrl": "audio/peaky-blinders/104_you_might_think_this_is_a_curious_place_for_me_to_suggest_a.mp3"
  },
  {
    "text": "You want me to go away?",
    "character": "",
    "audioUrl": "audio/peaky-blinders/105_you_want_me_to_go_away_yes_i_lljust_leave_these.mp3"
  },
  {
    "text": "It's all over, hold her",
    "character": "",
    "audioUrl": "audio/peaky-blinders/106_you_re_all_right_you_re_all_right_it_s_all_over_hold_her.mp3"
  },
  {
    "text": "Clear that shit, take her",
    "character": "",
    "audioUrl": "audio/peaky-blinders/107_clear_that_shit_clear_it_all_right_take_her.mp3"
  },
  {
    "text": "It's your mother. Oh, fuck.",
    "character": "",
    "audioUrl": "audio/peaky-blinders/109_footsteps_approach_door_opens_mr_gray_yeah_send_him_in_it_s.mp3"
  },
  {
    "text": "Give him peace. Amen.",
    "character": "",
    "audioUrl": "audio/peaky-blinders/110_and_give_him_peace_amen_amen.mp3"
  },
  {
    "text": "For thine is the kingdom",
    "character": "",
    "audioUrl": "audio/peaky-blinders/111_for_thine_is_the_kingdom_the_power_and_the_glory_for_ever_a.mp3"
  }
];
