// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "Because of my mistake six men didn't return from that raid",
    "character": "",
    "audioUrl": "audio/airplane/001_because_of_my_mistake_six_men_didn_t_return_from_that_raid.mp3"
  },
  {
    "text": "Bob is getting thicker and lyons getting larger",
    "character": "",
    "audioUrl": "audio/airplane/002_bob_is_getting_thicker_and_lyons_getting_larger.mp3"
  },
  {
    "text": "By twelve nine now arriving gate based in",
    "character": "",
    "audioUrl": "audio/airplane/003_by_twelve_nine_now_arriving_gate_based_in.mp3"
  },
  {
    "text": "Captains and maybe we ought to turn on the searchlights now",
    "character": "",
    "audioUrl": "audio/airplane/004_captains_and_maybe_we_ought_to_turn_on_the_searchlights_now.mp3"
  },
  {
    "text": "Do you like something to read do you have anything light how about this leaflet famous jewish sports legends",
    "character": "",
    "audioUrl": "audio/airplane/005_do_you_like_something_to_read_do_you_have_anything_light_how.mp3"
  },
  {
    "text": "Excuse me this is the operator captain over I have an emergency call for you on line five from a mister ham alright give me ham on five old male",
    "character": "",
    "audioUrl": "audio/airplane/006_excuse_me_this_is_the_operator_captain_over_i_have_an_emerge.mp3"
  },
  {
    "text": "Get angles blood she could catch up and be bad mentor big mama mama",
    "character": "",
    "audioUrl": "audio/airplane/007_get_angles_blood_she_could_catch_up_and_be_bad_mentor_big_ma.mp3"
  },
  {
    "text": "Get that finger out of your ear you don't know that fingers pen",
    "character": "",
    "audioUrl": "audio/airplane/008_get_that_finger_out_of_your_ear_you_don_t_know_that_fingers.mp3"
  },
  {
    "text": "Going have you ever been enough",
    "character": "",
    "audioUrl": "audio/airplane/009_going_have_you_ever_been_enough.mp3"
  },
  {
    "text": "Guess I picked the wrong week to quit sniffing glue",
    "character": "",
    "audioUrl": "audio/airplane/010_guess_i_picked_the_wrong_week_to_quit_sniffing_glue.mp3"
  },
  {
    "text": "I've been little problem in the cockpit what is it little room in the front of the plane where the pilot said that's not important right now",
    "character": "",
    "audioUrl": "audio/airplane/011_i_ve_been_little_problem_in_the_cockpit_what_is_it_little_ro.mp3"
  },
  {
    "text": "Join ever hang around the gymnasium",
    "character": "",
    "audioUrl": "audio/airplane/012_join_ever_hang_around_the_gymnasium.mp3"
  },
  {
    "text": "Joy",
    "character": "",
    "audioUrl": "audio/airplane/013_joy.mp3"
  },
  {
    "text": "Like I picked the wrong week to quit amphetamines",
    "character": "",
    "audioUrl": "audio/airplane/014_like_i_picked_the_wrong_week_to_quit_amphetamines.mp3"
  },
  {
    "text": "Like I picked the wrong week to quit smoking",
    "character": "",
    "audioUrl": "audio/airplane/015_like_i_picked_the_wrong_week_to_quit_smoking.mp3"
  },
  {
    "text": "Name sounds you know this small lady running whole upside down his head",
    "character": "",
    "audioUrl": "audio/airplane/016_name_sounds_you_know_this_small_lady_running_whole_upside_do.mp3"
  },
  {
    "text": "No this like to fall in the mud and get kicked in the head",
    "character": "",
    "audioUrl": "audio/airplane/017_no_this_like_to_fall_in_the_mud_and_get_kicked_in_the_head.mp3"
  },
  {
    "text": "Passengers certain to die",
    "character": "",
    "audioUrl": "audio/airplane/018_passengers_certain_to_die.mp3"
  },
  {
    "text": "Please no thank you I take it black like my men",
    "character": "",
    "audioUrl": "audio/airplane/019_please_no_thank_you_i_take_it_black_like_my_men.mp3"
  },
  {
    "text": "So one yourself anymore and immediate locus download passengers only",
    "character": "",
    "audioUrl": "audio/airplane/020_so_one_yourself_anymore_and_immediate_locus_download_passeng.mp3"
  },
  {
    "text": "Surely you can't be serious I am serious and don't call me shirley",
    "character": "",
    "audioUrl": "audio/airplane/021_surely_you_can_t_be_serious_i_am_serious_and_don_t_call_me_s.mp3"
  },
  {
    "text": "That they slide a piece of deported franks tire on the job I can big reason to put those in butter and dragon fruit guards",
    "character": "",
    "audioUrl": "audio/airplane/022_that_they_slide_a_piece_of_deported_franks_tire_on_the_job_i.mp3"
  },
  {
    "text": "This woman has to be got into a hospital hospital what is it it's a big building with patients but that's not important right now",
    "character": "",
    "audioUrl": "audio/airplane/023_this_woman_has_to_be_got_into_a_hospital_hospital_what_is_it.mp3"
  },
  {
    "text": "We have clearance clarence roger roger what's our vector victor",
    "character": "",
    "audioUrl": "audio/airplane/024_we_have_clearance_clarence_roger_roger_what_s_our_vector_vic.mp3"
  },
  {
    "text": "You ever been in a cockpit before i've never been up in a plane before you ever seen a grown man naked",
    "character": "",
    "audioUrl": "audio/airplane/025_you_ever_been_in_a_cockpit_before_i_ve_never_been_up_in_a_pl.mp3"
  }
];
