// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "A little help please",
    "character": "",
    "audioUrl": "audio/rick-and-morty/001_a_little_help_please.mp3"
  },
  {
    "text": "A lot of Vodka",
    "character": "",
    "audioUrl": "audio/rick-and-morty/002_a_lot_of_vodka.mp3"
  },
  {
    "text": "Almost always dressed as Superman",
    "character": "",
    "audioUrl": "audio/rick-and-morty/004_almost_always_dressed_as_superman.mp3"
  },
  {
    "text": "Alternative Interrogation",
    "character": "",
    "audioUrl": "audio/rick-and-morty/005_alternative_interrogation.mp3"
  },
  {
    "text": "And that's how we play hands",
    "character": "",
    "audioUrl": "audio/rick-and-morty/006_and_that_s_how_we_play_hands.mp3"
  },
  {
    "text": "Ants in my eyes Johnson",
    "character": "",
    "audioUrl": "audio/rick-and-morty/008_ants_in_my_eyes_johnson.mp3"
  },
  {
    "text": "Are you a simulation!?",
    "character": "",
    "audioUrl": "audio/rick-and-morty/009_are_you_a_simulation.mp3"
  },
  {
    "text": "Are you hungry for apples",
    "character": "",
    "audioUrl": "audio/rick-and-morty/010_are_you_hungry_for_apples.mp3"
  },
  {
    "text": "Back to the drawing board",
    "character": "",
    "audioUrl": "audio/rick-and-morty/011_back_to_the_drawing_board.mp3"
  },
  {
    "text": "Banana rick",
    "character": "",
    "audioUrl": "audio/rick-and-morty/012_banana_rick.mp3"
  },
  {
    "text": "Bigot Attack",
    "character": "",
    "audioUrl": "audio/rick-and-morty/017_bigot_attack.mp3"
  },
  {
    "text": "Blips and Chitz",
    "character": "",
    "audioUrl": "audio/rick-and-morty/019_blips_and_chitz.mp3"
  },
  {
    "text": "Bully Attack",
    "character": "",
    "audioUrl": "audio/rick-and-morty/020_bully_attack.mp3"
  },
  {
    "text": "Can do!",
    "character": "",
    "audioUrl": "audio/rick-and-morty/022_can_do.mp3"
  },
  {
    "text": "Christmas Drums",
    "character": "",
    "audioUrl": "audio/rick-and-morty/024_christmas_drums.mp3"
  },
  {
    "text": "Christmas is a special time",
    "character": "",
    "audioUrl": "audio/rick-and-morty/025_christmas_is_a_special_time.mp3"
  },
  {
    "text": "Closet Superman",
    "character": "",
    "audioUrl": "audio/rick-and-morty/026_closet_superman.mp3"
  },
  {
    "text": "Coin Value",
    "character": "",
    "audioUrl": "audio/rick-and-morty/027_coin_value.mp3"
  },
  {
    "text": "Come on football!",
    "character": "",
    "audioUrl": "audio/rick-and-morty/028_come_on_football.mp3"
  },
  {
    "text": "Crying and drinking wine",
    "character": "",
    "audioUrl": "audio/rick-and-morty/031_crying_and_drinking_wine.mp3"
  },
  {
    "text": "Da Doi",
    "character": "",
    "audioUrl": "audio/rick-and-morty/033_da_doi.mp3"
  },
  {
    "text": "Death Stranding",
    "character": "",
    "audioUrl": "audio/rick-and-morty/034_death_stranding.mp3"
  },
  {
    "text": "Do you know what wubba lubba dub dub means?",
    "character": "",
    "audioUrl": "audio/rick-and-morty/035_do_you_know_what_wubba_lubba_dub_dub_means.mp3"
  },
  {
    "text": "Eat Shit",
    "character": "",
    "audioUrl": "audio/rick-and-morty/038_eat_shit.mp3"
  },
  {
    "text": "Evil Morty theme earrape",
    "character": "",
    "audioUrl": "audio/rick-and-morty/041_evil_morty_theme_earrape.mp3"
  },
  {
    "text": "Fart",
    "character": "",
    "audioUrl": "audio/rick-and-morty/042_fart.mp3"
  },
  {
    "text": "Fuck you I'm through here",
    "character": "",
    "audioUrl": "audio/rick-and-morty/043_fuck_you_i_m_through_here.mp3"
  },
  {
    "text": "Fuck you Summer, and fuck the government",
    "character": "",
    "audioUrl": "audio/rick-and-morty/044_fuck_you_summer_and_fuck_the_government.mp3"
  },
  {
    "text": "Get in the Shower",
    "character": "",
    "audioUrl": "audio/rick-and-morty/045_get_in_the_shower.mp3"
  },
  {
    "text": "Get Schwifty",
    "character": "",
    "audioUrl": "audio/rick-and-morty/046_get_schwifty.mp3"
  },
  {
    "text": "Get Schwifty",
    "character": "",
    "audioUrl": "audio/rick-and-morty/047_get_schwifty.mp3"
  },
  {
    "text": "Get Schwiftyyy",
    "character": "",
    "audioUrl": "audio/rick-and-morty/048_get_schwiftyyy.mp3"
  },
  {
    "text": "Get Some",
    "character": "",
    "audioUrl": "audio/rick-and-morty/049_get_some.mp3"
  },
  {
    "text": "Get up on outta here",
    "character": "",
    "audioUrl": "audio/rick-and-morty/050_get_up_on_outta_here.mp3"
  },
  {
    "text": "Get your shit together",
    "character": "",
    "audioUrl": "audio/rick-and-morty/051_get_your_shit_together.mp3"
  },
  {
    "text": "Get your shit together",
    "character": "",
    "audioUrl": "audio/rick-and-morty/052_get_your_shit_together.mp3"
  },
  {
    "text": "Get your shit together",
    "character": "",
    "audioUrl": "audio/rick-and-morty/053_get_your_shit_together.mp3"
  },
  {
    "text": "Giant Feet",
    "character": "",
    "audioUrl": "audio/rick-and-morty/054_giant_feet.mp3"
  },
  {
    "text": "Giant Prison",
    "character": "",
    "audioUrl": "audio/rick-and-morty/055_giant_prison.mp3"
  },
  {
    "text": "Going to make love to my wife",
    "character": "",
    "audioUrl": "audio/rick-and-morty/056_going_to_make_love_to_my_wife.mp3"
  },
  {
    "text": "Good Breakfast",
    "character": "",
    "audioUrl": "audio/rick-and-morty/057_good_breakfast.mp3"
  },
  {
    "text": "Good job",
    "character": "",
    "audioUrl": "audio/rick-and-morty/058_good_job.mp3"
  },
  {
    "text": "Goodbye",
    "character": "",
    "audioUrl": "audio/rick-and-morty/059_goodbye.mp3"
  },
  {
    "text": "Goodbye",
    "character": "",
    "audioUrl": "audio/rick-and-morty/060_goodbye.mp3"
  },
  {
    "text": "Gotta take it real serious",
    "character": "",
    "audioUrl": "audio/rick-and-morty/062_gotta_take_it_real_serious.mp3"
  },
  {
    "text": "Grass taste bad",
    "character": "",
    "audioUrl": "audio/rick-and-morty/063_grass_taste_bad.mp3"
  },
  {
    "text": "Gross",
    "character": "",
    "audioUrl": "audio/rick-and-morty/065_gross.mp3"
  },
  {
    "text": "Help me I'm gonna die",
    "character": "",
    "audioUrl": "audio/rick-and-morty/068_help_me_i_m_gonna_die.mp3"
  },
  {
    "text": "Hi, I am Mr",
    "character": "",
    "audioUrl": "audio/rick-and-morty/072_hi_i_am_mr.mp3"
  },
  {
    "text": "High IQ to understand rick and morty",
    "character": "",
    "audioUrl": "audio/rick-and-morty/073_high_iq_to_understand_rick_and_morty.mp3"
  },
  {
    "text": "Holy shit, thanks kids you figured it out",
    "character": "",
    "audioUrl": "audio/rick-and-morty/074_holy_shit_thanks_kids_you_figured_it_out.mp3"
  },
  {
    "text": "I choose to get C's",
    "character": "",
    "audioUrl": "audio/rick-and-morty/077_i_choose_to_get_c_s.mp3"
  },
  {
    "text": "I don't feel safe",
    "character": "",
    "audioUrl": "audio/rick-and-morty/078_i_don_t_feel_safe.mp3"
  },
  {
    "text": "Shake that ass",
    "character": "",
    "audioUrl": "audio/rick-and-morty/079_i_don_t_give_a_fuck_just_shake_that_ass_and_see_what_you_got.mp3"
  },
  {
    "text": "I stand by it",
    "character": "",
    "audioUrl": "audio/rick-and-morty/080_i_dunno_why_i_said_that_but_i_stand_by_it.mp3"
  },
  {
    "text": "I just want to die!",
    "character": "",
    "audioUrl": "audio/rick-and-morty/081_i_just_want_to_die.mp3"
  },
  {
    "text": "I love morty",
    "character": "",
    "audioUrl": "audio/rick-and-morty/082_i_love_morty.mp3"
  },
  {
    "text": "I love trash",
    "character": "",
    "audioUrl": "audio/rick-and-morty/083_i_love_trash.mp3"
  },
  {
    "text": "I never go back to the carpet store",
    "character": "",
    "audioUrl": "audio/rick-and-morty/084_i_never_go_back_to_the_carpet_store.mp3"
  },
  {
    "text": "I say, lets do it!",
    "character": "",
    "audioUrl": "audio/rick-and-morty/085_i_say_lets_do_it.mp3"
  },
  {
    "text": "I want that Mulan McNugget sauce",
    "character": "",
    "audioUrl": "audio/rick-and-morty/086_i_want_that_mulan_mcnugget_sauce.mp3"
  },
  {
    "text": "I was not in control of that situation",
    "character": "",
    "audioUrl": "audio/rick-and-morty/087_i_was_not_in_control_of_that_situation.mp3"
  },
  {
    "text": "I'm Cool Rick",
    "character": "",
    "audioUrl": "audio/rick-and-morty/090_i_m_cool_rick_you_re_outnumbered.mp3"
  },
  {
    "text": "I'm in, you son of a bitch",
    "character": "",
    "audioUrl": "audio/rick-and-morty/092_i_m_in_you_son_of_a_bitch.mp3"
  },
  {
    "text": "I'm Jerry Smith",
    "character": "",
    "audioUrl": "audio/rick-and-morty/093_i_m_jerry_smith.mp3"
  },
  {
    "text": "I'm late to class b*tch",
    "character": "",
    "audioUrl": "audio/rick-and-morty/094_i_m_late_to_class_b_tch.mp3"
  },
  {
    "text": "I'm peeing on your guns",
    "character": "",
    "audioUrl": "audio/rick-and-morty/096_i_m_peeing_on_your_guns.mp3"
  },
  {
    "text": "I'm Scary Terry",
    "character": "",
    "audioUrl": "audio/rick-and-morty/098_i_m_scary_terry.mp3"
  },
  {
    "text": "Interdimensional Cable II",
    "character": "",
    "audioUrl": "audio/rick-and-morty/101_interdimensional_cable_ii.mp3"
  },
  {
    "text": "Is this organic?",
    "character": "",
    "audioUrl": "audio/rick-and-morty/102_is_this_organic.mp3"
  },
  {
    "text": "Judge Morty",
    "character": "",
    "audioUrl": "audio/rick-and-morty/106_judge_morty.mp3"
  },
  {
    "text": "Just stick with me",
    "character": "",
    "audioUrl": "audio/rick-and-morty/108_just_stick_with_me.mp3"
  },
  {
    "text": "King of Shit",
    "character": "",
    "audioUrl": "audio/rick-and-morty/110_king_of_shit.mp3"
  },
  {
    "text": "Left the portal gun at home",
    "character": "",
    "audioUrl": "audio/rick-and-morty/111_left_the_portal_gun_at_home.mp3"
  },
  {
    "text": "Leslie Wai Remixrick",
    "character": "",
    "audioUrl": "audio/rick-and-morty/112_leslie_wai_remixrick.mp3"
  },
  {
    "text": "Let me out acoustic",
    "character": "",
    "audioUrl": "audio/rick-and-morty/113_let_me_out_acoustic.mp3"
  },
  {
    "text": "Let me out dance",
    "character": "",
    "audioUrl": "audio/rick-and-morty/114_let_me_out_dance.mp3"
  },
  {
    "text": "Let's do this as a team",
    "character": "",
    "audioUrl": "audio/rick-and-morty/115_let_s_do_this_as_a_team.mp3"
  },
  {
    "text": "Look through my eye holes!",
    "character": "",
    "audioUrl": "audio/rick-and-morty/118_look_through_my_eye_holes.mp3"
  },
  {
    "text": "Love",
    "character": "",
    "audioUrl": "audio/rick-and-morty/119_love.mp3"
  },
  {
    "text": "Lust and Greed",
    "character": "",
    "audioUrl": "audio/rick-and-morty/120_lust_and_greed.mp3"
  },
  {
    "text": "Matrix Forty",
    "character": "",
    "audioUrl": "audio/rick-and-morty/121_matrix_forty.mp3"
  },
  {
    "text": "Meeting Mr",
    "character": "",
    "audioUrl": "audio/rick-and-morty/122_meeting_mr.mp3"
  },
  {
    "text": "Morty killed the Simpsons",
    "character": "",
    "audioUrl": "audio/rick-and-morty/125_morty_killed_the_simpsons.mp3"
  },
  {
    "text": "Mr",
    "character": "",
    "audioUrl": "audio/rick-and-morty/127_mr.mp3"
  },
  {
    "text": "Mr",
    "character": "",
    "audioUrl": "audio/rick-and-morty/128_mr.mp3"
  },
  {
    "text": "Mr",
    "character": "",
    "audioUrl": "audio/rick-and-morty/129_mr.mp3"
  },
  {
    "text": "Mr",
    "character": "",
    "audioUrl": "audio/rick-and-morty/130_mr.mp3"
  },
  {
    "text": "Mr",
    "character": "",
    "audioUrl": "audio/rick-and-morty/131_mr.mp3"
  },
  {
    "text": "Mr poopy",
    "character": "",
    "audioUrl": "audio/rick-and-morty/133_mr_poopy.mp3"
  },
  {
    "text": "Neo Nazi attack",
    "character": "",
    "audioUrl": "audio/rick-and-morty/135_neo_nazi_attack.mp3"
  },
  {
    "text": "New situations",
    "character": "",
    "audioUrl": "audio/rick-and-morty/136_new_situations.mp3"
  },
  {
    "text": "Nobody exists on purpose",
    "character": "",
    "audioUrl": "audio/rick-and-morty/137_nobody_exists_on_purpose.mp3"
  },
  {
    "text": "Nobody exists on purpose..",
    "character": "",
    "audioUrl": "audio/rick-and-morty/138_nobody_exists_on_purpose.mp3"
  },
  {
    "text": "Noob Noob's first mission",
    "character": "",
    "audioUrl": "audio/rick-and-morty/141_noob_noob_s_first_mission.mp3"
  },
  {
    "text": "Now is the time for action",
    "character": "",
    "audioUrl": "audio/rick-and-morty/143_now_is_the_time_for_action.mp3"
  },
  {
    "text": "Oh fuck",
    "character": "",
    "audioUrl": "audio/rick-and-morty/146_oh_fuck.mp3"
  },
  {
    "text": "Oh man, oh jeez",
    "character": "",
    "audioUrl": "audio/rick-and-morty/148_oh_man_oh_jeez.mp3"
  },
  {
    "text": "Oh no, I'm not wearing any pants!",
    "character": "",
    "audioUrl": "audio/rick-and-morty/150_oh_no_i_m_not_wearing_any_pants.mp3"
  },
  {
    "text": "Oh shit, we got tiny people",
    "character": "",
    "audioUrl": "audio/rick-and-morty/151_oh_shit_we_got_tiny_people.mp3"
  },
  {
    "text": "Oh yeah I want you!",
    "character": "",
    "audioUrl": "audio/rick-and-morty/152_oh_yeah_i_want_you.mp3"
  },
  {
    "text": "Oh yeah! Fight! Pickle Rick!",
    "character": "",
    "audioUrl": "audio/rick-and-morty/153_oh_yeah_fight_pickle_rick.mp3"
  },
  {
    "text": "Oh my god are you drunk?!",
    "character": "",
    "audioUrl": "audio/rick-and-morty/155_omg_are_you_drunk.mp3"
  },
  {
    "text": "Oh my god caught wanking it",
    "character": "",
    "audioUrl": "audio/rick-and-morty/156_omg_caught_wanking_it.mp3"
  },
  {
    "text": "Ooo weee long",
    "character": "",
    "audioUrl": "audio/rick-and-morty/157_ooo_weee_long.mp3"
  },
  {
    "text": "OooWeee",
    "character": "",
    "audioUrl": "audio/rick-and-morty/158_oooweee.mp3"
  },
  {
    "text": "Pat on the back",
    "character": "",
    "audioUrl": "audio/rick-and-morty/159_pat_on_the_back.mp3"
  },
  {
    "text": "Pickle rick",
    "character": "",
    "audioUrl": "audio/rick-and-morty/162_pickle_rick.mp3"
  },
  {
    "text": "Pickle Rick escapes the sewer!",
    "character": "",
    "audioUrl": "audio/rick-and-morty/163_pickle_rick_escapes_the_sewer.mp3"
  },
  {
    "text": "Pickle Rick transformation",
    "character": "",
    "audioUrl": "audio/rick-and-morty/164_pickle_rick_transformation.mp3"
  },
  {
    "text": "Pluto is a planet",
    "character": "",
    "audioUrl": "audio/rick-and-morty/166_pluto_is_a_planet.mp3"
  },
  {
    "text": "Put your burka on",
    "character": "",
    "audioUrl": "audio/rick-and-morty/167_put_your_burka_on.mp3"
  },
  {
    "text": "Reality is Poison",
    "character": "",
    "audioUrl": "audio/rick-and-morty/168_reality_is_poison.mp3"
  },
  {
    "text": "Redgrin Grumble",
    "character": "",
    "audioUrl": "audio/rick-and-morty/169_redgrin_grumble.mp3"
  },
  {
    "text": "Rhetorical Question",
    "character": "",
    "audioUrl": "audio/rick-and-morty/170_rhetorical_question.mp3"
  },
  {
    "text": "Rick and Morty",
    "character": "",
    "audioUrl": "audio/rick-and-morty/172_rick_and_morty.mp3"
  },
  {
    "text": "Rick and Morty",
    "character": "",
    "audioUrl": "audio/rick-and-morty/173_rick_and_morty.mp3"
  },
  {
    "text": "Rick and Morty",
    "character": "",
    "audioUrl": "audio/rick-and-morty/174_rick_and_morty.mp3"
  },
  {
    "text": "Rick and morty",
    "character": "",
    "audioUrl": "audio/rick-and-morty/175_rick_and_morty.mp3"
  },
  {
    "text": "Red heads",
    "character": "",
    "audioUrl": "audio/rick-and-morty/178_rick_and_morty_red_heads.mp3"
  },
  {
    "text": "Shit",
    "character": "",
    "audioUrl": "audio/rick-and-morty/179_rick_and_morty_shit.mp3"
  },
  {
    "text": "Intro (loud)",
    "character": "",
    "audioUrl": "audio/rick-and-morty/181_rick_and_morty_intro_ear_rape.mp3"
  },
  {
    "text": "Leprechaun",
    "character": "",
    "audioUrl": "audio/rick-and-morty/182_rick_and_morty_leprechaun.mp3"
  },
  {
    "text": "S**t",
    "character": "",
    "audioUrl": "audio/rick-and-morty/183_rick_and_morty_s_t.mp3"
  },
  {
    "text": "Sad f",
    "character": "",
    "audioUrl": "audio/rick-and-morty/184_rick_and_morty_sad_f.mp3"
  },
  {
    "text": "Shake that ass",
    "character": "",
    "audioUrl": "audio/rick-and-morty/185_rick_and_morty_shake_that_ass.mp3"
  },
  {
    "text": "Song",
    "character": "",
    "audioUrl": "audio/rick-and-morty/187_rick_and_morty_song.mp3"
  },
  {
    "text": "Evil Morty's theme",
    "character": "",
    "audioUrl": "audio/rick-and-morty/188_rick_and_morty_soundtrack_evil_morty_s_theme_qua.mp3"
  },
  {
    "text": "Rick Fredie",
    "character": "",
    "audioUrl": "audio/rick-and-morty/191_rick_fredie.mp3"
  },
  {
    "text": "Rick Schwifty",
    "character": "",
    "audioUrl": "audio/rick-and-morty/193_rick_schwifty.mp3"
  },
  {
    "text": "Riggity riggity wrecked son",
    "character": "",
    "audioUrl": "audio/rick-and-morty/195_riggity_riggity_wrecked_son.mp3"
  },
  {
    "text": "Rise above focus on science",
    "character": "",
    "audioUrl": "audio/rick-and-morty/196_rise_above_focus_on_science.mp3"
  },
  {
    "text": "Save it for the semantics dome",
    "character": "",
    "audioUrl": "audio/rick-and-morty/197_save_it_for_the_semantics_dome.mp3"
  },
  {
    "text": "Scary Terry",
    "character": "",
    "audioUrl": "audio/rick-and-morty/198_scary_terry.mp3"
  },
  {
    "text": "Scary Terry",
    "character": "",
    "audioUrl": "audio/rick-and-morty/200_scary_terry.mp3"
  },
  {
    "text": "Schezwan sauce speech - Rick and Morty season 3",
    "character": "",
    "audioUrl": "audio/rick-and-morty/201_schezwan_sauce_speech_rick_and_morty_season_3.mp3"
  },
  {
    "text": "Screaming sun - Rick and Morty",
    "character": "",
    "audioUrl": "audio/rick-and-morty/202_screaming_sun_rick_and_morty.mp3"
  },
  {
    "text": "Scumbag Attack",
    "character": "",
    "audioUrl": "audio/rick-and-morty/203_scumbag_attack.mp3"
  },
  {
    "text": "See this?",
    "character": "",
    "audioUrl": "audio/rick-and-morty/204_see_this.mp3"
  },
  {
    "text": "Shake that ass",
    "character": "",
    "audioUrl": "audio/rick-and-morty/206_shake_that_ass.mp3"
  },
  {
    "text": "Shirt",
    "character": "",
    "audioUrl": "audio/rick-and-morty/207_shirt.mp3"
  },
  {
    "text": "Show me what you got",
    "character": "",
    "audioUrl": "audio/rick-and-morty/208_show_me_what_you_got.mp3"
  },
  {
    "text": "Show me what you got",
    "character": "",
    "audioUrl": "audio/rick-and-morty/209_show_me_what_you_got.mp3"
  },
  {
    "text": "Singing cowboy meme",
    "character": "",
    "audioUrl": "audio/rick-and-morty/210_singing_cowboy_meme.mp3"
  },
  {
    "text": "Songify this R and M",
    "character": "",
    "audioUrl": "audio/rick-and-morty/212_songify_this_r_and_m.mp3"
  },
  {
    "text": "Squanchy Culture",
    "character": "",
    "audioUrl": "audio/rick-and-morty/213_squanchy_culture.mp3"
  },
  {
    "text": "Stop Fighting",
    "character": "",
    "audioUrl": "audio/rick-and-morty/214_stop_fighting.mp3"
  },
  {
    "text": "Suck my dick",
    "character": "",
    "audioUrl": "audio/rick-and-morty/217_suck_my_dick.mp3"
  },
  {
    "text": "Syka",
    "character": "",
    "audioUrl": "audio/rick-and-morty/218_syka.mp3"
  },
  {
    "text": "Szechuan sauce",
    "character": "",
    "audioUrl": "audio/rick-and-morty/219_szechuan_sauce.mp3"
  },
  {
    "text": "Szechuan Sauce is delicious!",
    "character": "",
    "audioUrl": "audio/rick-and-morty/220_szechuan_sauce_is_delicious.mp3"
  },
  {
    "text": "Teenage mind is its own worst enemy",
    "character": "",
    "audioUrl": "audio/rick-and-morty/221_teenage_mind_is_its_own_worst_enemy.mp3"
  },
  {
    "text": "Thank You",
    "character": "",
    "audioUrl": "audio/rick-and-morty/222_thank_you.mp3"
  },
  {
    "text": "Thanks Mr",
    "character": "",
    "audioUrl": "audio/rick-and-morty/224_thanks_mr.mp3"
  },
  {
    "text": "That's a relief",
    "character": "",
    "audioUrl": "audio/rick-and-morty/226_that_s_a_relief.mp3"
  },
  {
    "text": "The 12 days of Rickmas",
    "character": "",
    "audioUrl": "audio/rick-and-morty/230_the_12_days_of_rickmas.mp3"
  },
  {
    "text": "The ghost train guy would've used a ghost train",
    "character": "",
    "audioUrl": "audio/rick-and-morty/231_the_ghost_train_guy_would_ve_used_a_ghost_train.mp3"
  },
  {
    "text": "The mental breakdown",
    "character": "",
    "audioUrl": "audio/rick-and-morty/232_the_mental_breakdown.mp3"
  },
  {
    "text": "The Rick dance",
    "character": "",
    "audioUrl": "audio/rick-and-morty/233_the_rick_dance.mp3"
  },
  {
    "text": "The Rick dance",
    "character": "",
    "audioUrl": "audio/rick-and-morty/234_the_rick_dance.mp3"
  },
  {
    "text": "This guys taking Roy off the grid!",
    "character": "",
    "audioUrl": "audio/rick-and-morty/235_this_guys_taking_roy_off_the_grid.mp3"
  },
  {
    "text": "This lawyer has made sexual advances on me",
    "character": "",
    "audioUrl": "audio/rick-and-morty/237_this_lawyer_has_made_sexual_advances_on_me.mp3"
  },
  {
    "text": "Tiny Rick hunting a vampire",
    "character": "",
    "audioUrl": "audio/rick-and-morty/240_tiny_rick_hunting_a_vampire.mp3"
  },
  {
    "text": "Two Brothers Rick and Morty",
    "character": "",
    "audioUrl": "audio/rick-and-morty/241_two_brothers_rick_and_morty.mp3"
  },
  {
    "text": "Two Brothers: The Movie",
    "character": "",
    "audioUrl": "audio/rick-and-morty/242_two_brothers_the_movie.mp3"
  },
  {
    "text": "Vasectomy",
    "character": "",
    "audioUrl": "audio/rick-and-morty/243_vasectomy.mp3"
  },
  {
    "text": "We are connecting this Christmas!",
    "character": "",
    "audioUrl": "audio/rick-and-morty/245_we_are_connecting_this_christmas.mp3"
  },
  {
    "text": "We need food when we're hungry",
    "character": "",
    "audioUrl": "audio/rick-and-morty/247_we_need_food_when_we_re_hungry.mp3"
  },
  {
    "text": "Weeping breakdown",
    "character": "",
    "audioUrl": "audio/rick-and-morty/250_weeping_breakdown.mp3"
  },
  {
    "text": "Welcome to your nightmare",
    "character": "",
    "audioUrl": "audio/rick-and-morty/251_welcome_to_your_nightmare.mp3"
  },
  {
    "text": "What is my purpose?",
    "character": "",
    "audioUrl": "audio/rick-and-morty/253_what_is_my_purpose.mp3"
  },
  {
    "text": "Whatever you say, Stone Cold Steve Austin",
    "character": "",
    "audioUrl": "audio/rick-and-morty/256_whatever_you_say_stone_cold_steve_austin.mp3"
  },
  {
    "text": "Where am I?!",
    "character": "",
    "audioUrl": "audio/rick-and-morty/258_where_am_i.mp3"
  },
  {
    "text": "Where is the anger coming from",
    "character": "",
    "audioUrl": "audio/rick-and-morty/259_where_is_the_anger_coming_from.mp3"
  },
  {
    "text": "Woolly Mammoths",
    "character": "",
    "audioUrl": "audio/rick-and-morty/264_woolly_mammoths.mp3"
  },
  {
    "text": "Woopie loopie doop doop",
    "character": "",
    "audioUrl": "audio/rick-and-morty/265_woopie_loopie_doop_doop.mp3"
  },
  {
    "text": "Wubba Lubba Dub Dub I am in great pain",
    "character": "",
    "audioUrl": "audio/rick-and-morty/268_wubba_lubba_dub_dub_i_am_in_great_pain.mp3"
  },
  {
    "text": "Wubba Lubba Dub Dub",
    "character": "",
    "audioUrl": "audio/rick-and-morty/270_wubba_lubba_dub_dub.mp3"
  },
  {
    "text": "Wubba Lubba Dub Dub fart",
    "character": "",
    "audioUrl": "audio/rick-and-morty/271_wubba_lubba_dub_dub_fart.mp3"
  },
  {
    "text": "X Gon' Give It To Ya",
    "character": "",
    "audioUrl": "audio/rick-and-morty/272_x_gon_give_it_to_ya.mp3"
  },
  {
    "text": "You aren't special",
    "character": "",
    "audioUrl": "audio/rick-and-morty/275_you_aren_t_special.mp3"
  },
  {
    "text": "You can be very inconsiderate sometimes",
    "character": "",
    "audioUrl": "audio/rick-and-morty/276_you_can_be_very_inconsiderate_sometimes.mp3"
  },
  {
    "text": "You f*cked with squirrels!",
    "character": "",
    "audioUrl": "audio/rick-and-morty/278_you_f_cked_with_squirrels.mp3"
  },
  {
    "text": "You're both pieces of shit, I can prove it mathematically",
    "character": "",
    "audioUrl": "audio/rick-and-morty/280_you_re_both_pieces_of_shit_i_can_prove_it_mathematically.mp3"
  },
  {
    "text": "You're killing the vibe in here",
    "character": "",
    "audioUrl": "audio/rick-and-morty/281_you_re_killing_the_vibe_in_here.mp3"
  },
  {
    "text": "3 Weeks Earlier",
    "character": "",
    "audioUrl": "audio/rick-and-morty/284_3_weeks_earlier.mp3"
  }
];
