// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "And those are hash bars Yeah it breaks down like this okay. It's legal to buy it it's legal to own it. and if you're the proprietor of a hash bar it's legal to sell it",
    "character": "",
    "audioUrl": "audio/pulp-fiction/001_and_those_are_hash_bars_yeah_it_breaks_down_like_this_okay_i.mp3"
  },
  {
    "text": "And you know what they call a quarter pounder with cheese in Paris. They don't call it a quarter pounder with cheese. Got the metric system there They wouldn't know what the fuck a quarter pounder is.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/002_and_you_know_what_they_call_a_quarter_pounder_with_cheese_in.mp3"
  },
  {
    "text": "And you know what they call a quarter pounder with cheese in Paris. They don't call it a quarter pounder with cheese. Got the metric system there They wouldn't know what the fuck a quarter pounder is. What do they call it. They call it a royale with cheese. Royale with cheese That's right. What do they call a big Mac. Well big Mac's a big Mac but they call it le big Mac. Le big Mac. What do they call a whopper. I don't know I didn't go into burger king. You know what they put on French...",
    "character": "",
    "audioUrl": "audio/pulp-fiction/003_and_you_know_what_they_call_a_quarter_pounder_with_cheese_in.mp3"
  },
  {
    "text": "And your ass ain't talking your way out of this shit No no no.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/004_and_your_ass_ain_t_talking_your_way_out_of_this_shit_no_no_n.mp3"
  },
  {
    "text": "But but I never got yours My name's pitt. and your ass ain't talking your way out of this shit No no no.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/005_but_but_i_never_got_yours_my_name_s_pitt_and_your_ass_ain_t.mp3"
  },
  {
    "text": "But I do love the taste of a good burger Mmm. You know what they call a quarter pounder with cheese in France.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/006_but_i_do_love_the_taste_of_a_good_burger_mmm_you_know_what_t.mp3"
  },
  {
    "text": "But painful as it may be. ability don't last And your days are just about over.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/007_but_painful_as_it_may_be_ability_don_t_last_and_your_days_ar.mp3"
  },
  {
    "text": "But you're saying a foot massage don't mean nothing. and I'm saying it does Now look I've given a million ladies. a million foot massages and they all meant something",
    "character": "",
    "audioUrl": "audio/pulp-fiction/008_but_you_re_saying_a_foot_massage_don_t_mean_nothing_and_i_m.mp3"
  },
  {
    "text": "Check out the big brain on Brett. You're a smart motherfucker That's right The metric system. What's in this. Sprite Sprite good. You mind if I have some of your tasty beverage.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/009_check_out_the_big_brain_on_brett_you_re_a_smart_motherfucker.mp3"
  },
  {
    "text": "Describe what marsellus Wallace looks like. What I. Say what again Say what again.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/010_describe_what_marsellus_wallace_looks_like_what_i_say_what_a.mp3"
  },
  {
    "text": "Does he look like a bitch. Then why you trying to fuck him like a bitch Brett. I didn't Yes you did.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/011_does_he_look_like_a_bitch_then_why_you_trying_to_fuck_him_li.mp3"
  },
  {
    "text": "Eating a bitch out and giving a bitch a foot massage. ain't even the same fucking thing It's not It's the same ballpark. Ain't no fucking ballpark neither.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/012_eating_a_bitch_out_and_giving_a_bitch_a_foot_massage_ain_t_e.mp3"
  },
  {
    "text": "Example All right. well you can walk into a movie theater in Amsterdam and buy a beer And I don't mean just like in no paper cup. I'm talking about a glass of beer.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/013_example_all_right_well_you_can_walk_into_a_movie_theater_in.mp3"
  },
  {
    "text": "Fuck you. You given 'em a lot. Fuck you. You know I'm kind of tired I could use a foot massage myself.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/014_fuck_you_you_given_em_a_lot_fuck_you_you_know_i_m_kind_of_ti.mp3"
  },
  {
    "text": "Fucking marsellus knew it. and Antwan should've fucking better known better I mean that's his fucking wife man. This ain't a man with a sense of humor about this shit.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/015_fucking_marsellus_knew_it_and_antwan_should_ve_fucking_bette.mp3"
  },
  {
    "text": "Garcon coffee. This place. Garcon means boy.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/016_garcon_coffee_this_place_garcon_means_boy.mp3"
  },
  {
    "text": "Goddamn. I've seen 'em do it man. They fucking drown 'em in that shit Ugh.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/017_goddamn_i_ve_seen_em_do_it_man_they_fucking_drown_em_in_that.mp3"
  },
  {
    "text": "Half black half Samoan used to call him Tony rocky horror. Yeah maybe Fat right. I wouldn't go so far as to call the brother fat.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/018_half_black_half_samoan_used_to_call_him_tony_rocky_horror_ye.mp3"
  },
  {
    "text": "Have you ever given a foot massage. Don't be telling me about foot massages. I'm the foot fucking master. You given a lot of 'em. Shit yeah Got my technique down and everything.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/019_have_you_ever_given_a_foot_massage_don_t_be_telling_me_about.mp3"
  },
  {
    "text": "He's he's black. Go on. He's bald. Does he look like a bitch. What. Does he look like a bitch. Then why you trying to fuck him like a bitch Brett. I didn't Yes you did. Yes you did Brett. You tried to fuck him No. Well marsellus Wallace don't like to be fucked. by anybody except Mrs Wallace You read the Bible Brett. Yes.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/020_he_s_he_s_black_go_on_he_s_bald_does_he_look_like_a_bitch_wh.mp3"
  },
  {
    "text": "He's he's black. Go on. He's bald. Does he look like a bitch. What. Gunshot Brett screams groans. Does he look like a bitch. Then why you trying to fuck him like a bitch Brett. I didn't Yes you did. Yes you did Brett. You tried to fuck him No. Well marsellus Wallace don't like to be fucked. by anybody except Mrs Wallace",
    "character": "",
    "audioUrl": "audio/pulp-fiction/021_he_s_he_s_black_go_on_he_s_bald_does_he_look_like_a_bitch_wh.mp3"
  },
  {
    "text": "Hey kids. How you boys doing. Hey keep chilling. You know who we are. We're associates of your business partner. marsellus Wallace You do remember your business partner don't you. Now let me take a wild guess here. You're Brett right. Yeah. Ithoughtso. You remember your business partner marsellus Wallace. don't you Brett Yeah I remember him Good. Looks like me and Vincent caught you boys at breakfast. Sorry about that What you having. Hamburgers. Hamburgers. The cornerstone of any...",
    "character": "",
    "audioUrl": "audio/pulp-fiction/022_hey_kids_how_you_boys_doing_hey_keep_chilling_you_know_who_w.mp3"
  },
  {
    "text": "I didn't mean to do that Please continue. You were saying something about best intentions.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/023_i_didn_t_mean_to_do_that_please_continue_you_were_saying_som.mp3"
  },
  {
    "text": "I don't know However people meet people. She used to be an actress. Oh really She do anything I'd have seen.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/024_i_don_t_know_however_people_meet_people_she_used_to_be_an_ac.mp3"
  },
  {
    "text": "I don't remember asking you a goddamn thing.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/025_i_don_t_remember_asking_you_a_goddamn_thing.mp3"
  },
  {
    "text": "I give my mother a foot massage. No it's laying hands in a familiar way on marsellus's new wife. I mean is it as bad as eating her pussy out. No but it's the same fucking ballpark.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/026_i_give_my_mother_a_foot_massage_no_it_s_laying_hands_in_a_fa.mp3"
  },
  {
    "text": "I just want you to know how sorry we are that that things got so fucked up. with us and and Mr Wallace We got into this thing. with the best intentions really",
    "character": "",
    "audioUrl": "audio/pulp-fiction/027_i_just_want_you_to_know_how_sorry_we_are_that_that_things_go.mp3"
  },
  {
    "text": "I love you pumpkin. I love you honey bunny. Everybody be cool This is a robbery. Any of you fucking pricks move. and I'll execute every motherfucking last one of you",
    "character": "",
    "audioUrl": "audio/pulp-fiction/028_i_love_you_pumpkin_i_love_you_honey_bunny_everybody_be_cool.mp3"
  },
  {
    "text": "I mean the way it is now. you're taking the same risk as when you Rob a bank Taking more of a risk Banks are easier. Federal banks ain't supposed to stop you in any way during a robbery. They're insured Why should they give a fuck. You don't even need a gun in a federal bank. I heard about this one bloke he walks into a bank with a portable phone. He gives the phone to the teller. bloke on the other end of the phone says we got this guy's little girl If you don't give him all your money we're...",
    "character": "",
    "audioUrl": "audio/pulp-fiction/029_i_mean_the_way_it_is_now_you_re_taking_the_same_risk_as_when.mp3"
  },
  {
    "text": "I mean they got the same shit over there. that they got here but it's just Just there it's a little different Example All right. well you can walk into a movie theater in Amsterdam and buy a beer",
    "character": "",
    "audioUrl": "audio/pulp-fiction/030_i_mean_they_got_the_same_shit_over_there_that_they_got_here.mp3"
  },
  {
    "text": "I mean they want you to smoke in your home or certain designated places. And those are hash bars Yeah it breaks down like this okay.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/031_i_mean_they_want_you_to_smoke_in_your_home_or_certain_design.mp3"
  },
  {
    "text": "I think her biggest deal was she starred in a pilot. Pilot What's a pilot. Well you know the shows on TV. I don't watch TV. Yeah but you are aware that there's an invention called television. and on this invention they show shows right Yeah. Well the way they pick TV shows is they make one show. That show's called a pilot. Then they show that one show to the people who pick shows. and on the strength of that one show they decide if they want to make more shows Some get chosen and become...",
    "character": "",
    "audioUrl": "audio/pulp-fiction/032_i_think_her_biggest_deal_was_she_starred_in_a_pilot_pilot_wh.mp3"
  },
  {
    "text": "I think you're gonna find yourself one smiling motherfucker. Thing is butch.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/033_i_think_you_re_gonna_find_yourself_one_smiling_motherfucker.mp3"
  },
  {
    "text": "I think you're gonna find. when all this shit is over and done I think you're gonna find yourself one smiling motherfucker. Thing is butch. right now you got ability But painful as it may be. ability don't last And your days are just about over. Now that's a hard motherfucking fact of life. but that's a fact of life your ass is gonna have to get realistic about See this business is filled to the brim with unrealistic motherfuckers. Motherfuckers who thought their ass would age like wine. If...",
    "character": "",
    "audioUrl": "audio/pulp-fiction/034_i_think_you_re_gonna_find_when_all_this_shit_is_over_and_don.mp3"
  },
  {
    "text": "I'm fucking going I know baby You'd dig it the most. But you know what the funniest thing about Europe is.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/035_i_m_fucking_going_i_know_baby_you_d_dig_it_the_most_but_you.mp3"
  },
  {
    "text": "If you get stopped by a cop in Amsterdam it's illegal for them to search you. I mean that's a right the cops in Amsterdam don't have. Oh man I'm going That's all there is to it.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/036_if_you_get_stopped_by_a_cop_in_amsterdam_it_s_illegal_for_th.mp3"
  },
  {
    "text": "It's legal to buy it it's legal to own it. and if you're the proprietor of a hash bar it's legal to sell it It's legal to carry it but that doesn't matter. 'Cause get a load of this all right",
    "character": "",
    "audioUrl": "audio/pulp-fiction/037_it_s_legal_to_buy_it_it_s_legal_to_own_it_and_if_you_re_the.mp3"
  },
  {
    "text": "It's not a date. It's definitely not a date.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/038_it_s_not_a_date_it_s_definitely_not_a_date.mp3"
  },
  {
    "text": "J jungle boogie j. j jungle boogie j j get it on j j jungle boogie j j jungle boogie j j gel if on j j jungle boogie j j get up with the boogie j j jungle boogie j j get up with the get down j j jungle boogie j j gel down with the boogie j j jungle boogie j j come and shake it around j",
    "character": "",
    "audioUrl": "audio/pulp-fiction/039_j_jungle_boogie_j_j_jungle_boogie_j_j_get_it_on_j_j_jungle_b.mp3"
  },
  {
    "text": "J let's sfa y fogez'berj. I think you're gonna find. when all this shit is over and done I think you're gonna find yourself one smiling motherfucker.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/040_j_let_s_sfa_y_fogez_berj_i_think_you_re_gonna_find_when_all.mp3"
  },
  {
    "text": "Jules: I'm not giving you that money. I'm buying something from you. Wanna know what I'm buyin' Ringo? Pumpkin: What? Jules: Your life. I'm givin' you that money so I don't have to kill your ass. You read the Bible? Pumpkin: Not regularly. Jules: There's a passage I got memorized. Ezekiel 25:17. \"The path of the righteous man is beset on all sides by the inequities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through...",
    "character": "",
    "audioUrl": "audio/pulp-fiction/041_jules_i_m_not_giving_you_that_money_i_m_buying_something_fro.mp3"
  },
  {
    "text": "Me I can't usually get 'em. 'cause my girlfriend's a vegetarian which pretty much makes me a vegetarian But I do love the taste of a good burger Mmm.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/042_me_i_can_t_usually_get_em_cause_my_girlfriend_s_a_vegetarian.mp3"
  },
  {
    "text": "Mia How did marsellus and her meet. I don't know However people meet people.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/043_mia_how_did_marsellus_and_her_meet_i_don_t_know_however_peop.mp3"
  },
  {
    "text": "Motherfucker do that shit to me. he better paralyze my ass 'cause I'd kill the motherfucker You know what I'm saying I ain't saying it's right. But you're saying a foot massage don't mean nothing.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/044_motherfucker_do_that_shit_to_me_he_better_paralyze_my_ass_ca.mp3"
  },
  {
    "text": "No it ain't quite time yet Come on Let's hang back.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/045_no_it_ain_t_quite_time_yet_come_on_let_s_hang_back.mp3"
  },
  {
    "text": "Now look I've given a million ladies. a million foot massages and they all meant something Now we act like they don't but they do. That's what's so fucking cool about 'em.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/046_now_look_i_ve_given_a_million_ladies_a_million_foot_massages.mp3"
  },
  {
    "text": "Now look just 'cause I wouldn't give no man a foot massage. don't make it right for marsellus to throw Antwan off a building into a glass motherfucking house fucking up the way the n***** talks That shit ain't right. Motherfucker do that shit to me. he better paralyze my ass 'cause I'd kill the motherfucker",
    "character": "",
    "audioUrl": "audio/pulp-fiction/047_now_look_just_cause_i_wouldn_t_give_no_man_a_foot_massage_do.mp3"
  },
  {
    "text": "Now look just 'cause I wouldn't give no man a foot massage. don't make it right for marsellus to throw Antwan off a building into a glass motherfucking house fucking up the way the n***** talks That shit ain't right. Motherfucker do that shit to me. he better paralyze my ass 'cause I'd kill the motherfucker You know what I'm saying I ain't saying it's right. But you're saying a foot massage don't mean nothing. and I'm saying it does Now look I've given a million ladies. a million foot...",
    "character": "",
    "audioUrl": "audio/pulp-fiction/048_now_look_just_cause_i_wouldn_t_give_no_man_a_foot_massage_do.mp3"
  },
  {
    "text": "Now look maybe your method of massage differs from mine. but you know touching his wife's feet and sticking your tongue in her holiest of holies ain't the same fucking ballpark It ain't the same league It ain't even the same fucking sport. Look foot massages don't mean shit.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/049_now_look_maybe_your_method_of_massage_differs_from_mine_but.mp3"
  },
  {
    "text": "Now that's a hard motherfucking fact of life. but that's a fact of life your ass is gonna have to get realistic about",
    "character": "",
    "audioUrl": "audio/pulp-fiction/050_now_that_s_a_hard_motherfucking_fact_of_life_but_that_s_a_fa.mp3"
  },
  {
    "text": "Okay so tell me again about the hash bars. Okay What you want to know. Hash is legal there right. Yeah it's legal but it ain't 100 legal. You just can't walk into a restaurant roll a joint and start puffing away. I mean they want you to smoke in your home or certain designated places. And those are hash bars Yeah it breaks down like this okay. It's legal to buy it it's legal to own it. and if you're the proprietor of a hash bar it's legal to sell it It's legal to carry it but that doesn't...",
    "character": "",
    "audioUrl": "audio/pulp-fiction/051_okay_so_tell_me_again_about_the_hash_bars_okay_what_you_want.mp3"
  },
  {
    "text": "So what'd he do fuck her. No no no Nothing that bad. Well then what then.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/052_so_what_d_he_do_fuck_her_no_no_no_nothing_that_bad_well_then.mp3"
  },
  {
    "text": "That hit the spot. You flock of seagulls.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/053_that_hit_the_spot_you_flock_of_seagulls.mp3"
  },
  {
    "text": "That's a damn shame. But still I have to say you play with matches you get burned. What do you mean. You don't be giving marsellus Wallace's new bride a foot massage.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/054_that_s_a_damn_shame_but_still_i_have_to_say_you_play_with_ma.mp3"
  },
  {
    "text": "Then they show that one show to the people who pick shows. and on the strength of that one show they decide if they want to make more shows Some get chosen and become television programs. Some don't become nothing.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/055_then_they_show_that_one_show_to_the_people_who_pick_shows_an.mp3"
  },
  {
    "text": "There's a sensuous thing going on where you know. you don't talk about it but you know it and she knows it Fucking marsellus knew it. and Antwan should've fucking better known better",
    "character": "",
    "audioUrl": "audio/pulp-fiction/056_there_s_a_sensuous_thing_going_on_where_you_know_you_don_t_t.mp3"
  },
  {
    "text": "They call it a royale with cheese. Royale with cheese That's right. What do they call a big Mac. Well big Mac's a big Mac but they call it le big Mac.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/057_they_call_it_a_royale_with_cheese_royale_with_cheese_that_s.mp3"
  },
  {
    "text": "They fucking drown 'em in that shit Ugh. We should have shotguns for this kind of deal.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/058_they_fucking_drown_em_in_that_shit_ugh_we_should_have_shotgu.mp3"
  },
  {
    "text": "They had a little garden down at the bottom. enclosed in glass like a greenhouse N***** fell through that. Since then he kind of developed a speech impediment.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/059_they_had_a_little_garden_down_at_the_bottom_enclosed_in_glas.mp3"
  },
  {
    "text": "They took him out on his patio threw his ass over the balcony. N***** fell four stories. They had a little garden down at the bottom.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/060_they_took_him_out_on_his_patio_threw_his_ass_over_the_balcon.mp3"
  },
  {
    "text": "Thing is butch. right now you got ability But painful as it may be.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/061_thing_is_butch_right_now_you_got_ability_but_painful_as_it_m.mp3"
  },
  {
    "text": "This place. A coffee shop. What's wrong with that. Nobody ever robs restaurants. Why not. Bars liquor stores gas stations. You'll get your head blown off sticking up one of them. Restaurants on the other hand. you catch with their pants down They're not expecting to get robbed. Not as expecting anyway. I bet you could cut down on the hero factor in a place like this. Correct. Same as banks these places are insured. Manager He don't give a fuck. He's just trying to get you out the door...",
    "character": "",
    "audioUrl": "audio/pulp-fiction/062_this_place_a_coffee_shop_what_s_wrong_with_that_nobody_ever.mp3"
  },
  {
    "text": "We got into this thing. with the best intentions really I never inten. Oh I'm sorry Did I break your concentration.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/063_we_got_into_this_thing_with_the_best_intentions_really_i_nev.mp3"
  },
  {
    "text": "We should have shotguns for this kind of deal. How many up there. Three or four. That's counting our guy. I'm not sure. So that means it could be up to five guys up there. It's possible. We should have fucking shotguns.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/064_we_should_have_shotguns_for_this_kind_of_deal_how_many_up_th.mp3"
  },
  {
    "text": "We should have shotguns for this kind of deal. How many up there. Three or four. That's counting our guy. I'm not sure. So that means it could be up to five guys up there. It's possible. We should have fucking shotguns. What's her name Mia. Mia How did marsellus and her meet.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/065_we_should_have_shotguns_for_this_kind_of_deal_how_many_up_th.mp3"
  },
  {
    "text": "We're associates of your business partner. marsellus Wallace You do remember your business partner don't you.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/066_we_re_associates_of_your_business_partner_marsellus_wallace.mp3"
  },
  {
    "text": "Well Antwan probably didn't expect marsellus. to react the way he did but he had to expect a reaction It was a foot massage A foot massage is nothing. I give my mother a foot massage.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/067_well_antwan_probably_didn_t_expect_marsellus_to_react_the_wa.mp3"
  },
  {
    "text": "Well big Mac's a big Mac but they call it le big Mac. Le big Mac. What do they call a whopper. I don't know I didn't go into burger king. You know what they put on French fries in Holland instead of ketchup.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/068_well_big_mac_s_a_big_mac_but_they_call_it_le_big_mac_le_big.mp3"
  },
  {
    "text": "Well he's going out of town Florida. and he asked me if I'd take care of her while he's gone Take care of her. No man Just take her out.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/069_well_he_s_going_out_of_town_florida_and_he_asked_me_if_i_d_t.mp3"
  },
  {
    "text": "Well marsellus fucked him up good. Word around the campfire is. it was on account of marsellus Wallace's wife So what'd he do fuck her. No no no Nothing that bad. Well then what then. Gave her a foot massage. A foot massage Mm hmm. That's it Mm hmm. Then what did marsellus do. Sent a couple of cats over to his place. They took him out on his patio threw his ass over the balcony. N***** fell four stories. They had a little garden down at the bottom. enclosed in glass like a greenhouse N*****...",
    "character": "",
    "audioUrl": "audio/pulp-fiction/070_well_marsellus_fucked_him_up_good_word_around_the_campfire_i.mp3"
  },
  {
    "text": "Well there's this passage I got memorized. Sort of fits this occasion. Ezekiel 25 17. The path of the righteous man is beset on all sides. by the inequities of the selfish and the tyranny of evil men Blessed is he who in the name of charity and good will. Shepherds the weak through the valley of darkness. for he is truly his brother's keeper and the finder of lost children And I will strike down upon thee. with great vengeance and furious anger those who attempt to poison and destroy my...",
    "character": "",
    "audioUrl": "audio/pulp-fiction/071_well_there_s_this_passage_i_got_memorized_sort_of_fits_this.mp3"
  },
  {
    "text": "Well you know the shows on TV. I don't watch TV. Yeah but you are aware that there's an invention called television. and on this invention they show shows right Yeah. Well the way they pick TV shows is they make one show.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/072_well_you_know_the_shows_on_tv_i_don_t_watch_tv_yeah_but_you.mp3"
  },
  {
    "text": "Whoa whoa whoa Stop right there. Eating a bitch out and giving a bitch a foot massage. ain't even the same fucking thing It's not It's the same ballpark. Ain't no fucking ballpark neither. Now look maybe your method of massage differs from mine. but you know touching his wife's feet and sticking your tongue in her holiest of holies ain't the same fucking ballpark It ain't the same league It ain't even the same fucking sport. Look foot massages don't mean shit. Have you ever given a foot...",
    "character": "",
    "audioUrl": "audio/pulp-fiction/073_whoa_whoa_whoa_stop_right_there_eating_a_bitch_out_and_givin.mp3"
  },
  {
    "text": "Why you so interested in big man's wife. Well he's going out of town Florida. and he asked me if I'd take care of her while he's gone Take care of her. No man Just take her out. You know show her a good time. Make sure she don't get lonely. You're gonna be taking Mia Wallace out on a date. It is not a date. You know it's just like if you were going to take. your buddy's wife to a movie or something It's just good company that's all. It's not a date. It's definitely not a date.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/074_why_you_so_interested_in_big_man_s_wife_well_he_s_going_out.mp3"
  },
  {
    "text": "Word around the campfire is. it was on account of marsellus Wallace's wife",
    "character": "",
    "audioUrl": "audio/pulp-fiction/075_word_around_the_campfire_is_it_was_on_account_of_marsellus_w.mp3"
  },
  {
    "text": "Yeah but you are aware that there's an invention called television. and on this invention they show shows right Yeah. Well the way they pick TV shows is they make one show.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/076_yeah_but_you_are_aware_that_there_s_an_invention_called_tele.mp3"
  },
  {
    "text": "You don't be giving marsellus Wallace's new bride a foot massage. You don't think he overreacted. Well Antwan probably didn't expect marsellus.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/077_you_don_t_be_giving_marsellus_wallace_s_new_bride_a_foot_mas.mp3"
  },
  {
    "text": "You flock of seagulls. You know why we're here. Why don't you tell my man Vince here where you got the shit hid at. It's over there. I don't remember asking you a goddamn thing. You were saying. It's in the cupboard. No The one by your knees. We happy. Vincent. We happy Yeah we happy. Look. I'm sorry I I didn't get your name. I got yours Uh Vincent right. But but I never got yours My name's pitt. and your ass ain't talking your way out of this shit No no no. I just want you to know how. I...",
    "character": "",
    "audioUrl": "audio/pulp-fiction/078_you_flock_of_seagulls_you_know_why_we_re_here_why_don_t_you.mp3"
  },
  {
    "text": "You just can't walk into a restaurant roll a joint and start puffing away. I mean they want you to smoke in your home or certain designated places.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/079_you_just_can_t_walk_into_a_restaurant_roll_a_joint_and_start.mp3"
  },
  {
    "text": "You know it's just like if you were going to take. your buddy's wife to a movie or something It's just good company that's all.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/080_you_know_it_s_just_like_if_you_were_going_to_take_your_buddy.mp3"
  },
  {
    "text": "You know what they call a quarter pounder with cheese in France. Tell him Vincent Royale with cheese. Royale with cheese. You know why they call it that. Uh because of the metric system. Check out the big brain on Brett. You're a smart motherfucker That's right The metric system.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/081_you_know_what_they_call_a_quarter_pounder_with_cheese_in_fra.mp3"
  },
  {
    "text": "You know what they put on French fries in Holland instead of ketchup. What Mayonnaise. Goddamn Laughs. I've seen 'em do it man. They fucking drown 'em in that shit Ugh.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/082_you_know_what_they_put_on_french_fries_in_holland_instead_of.mp3"
  },
  {
    "text": "You know what they put on French fries in Holland instead of ketchup. What Mayonnaise. Goddamn. I've seen 'em do it man. They fucking drown 'em in that shit Ugh. We should have shotguns for this kind of deal.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/083_you_know_what_they_put_on_french_fries_in_holland_instead_of.mp3"
  },
  {
    "text": "You mind if I have some of your tasty beverage. to wash this down with Go right ahead.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/084_you_mind_if_i_have_some_of_your_tasty_beverage_to_wash_this.mp3"
  },
  {
    "text": "You remember Antwan rockamora. Half black half Samoan used to call him Tony rocky horror. Yeah maybe Fat right. I wouldn't go so far as to call the brother fat. I mean he got a weight problem What's the n***** gonna do He's Samoan. Yeah I think I know who you mean What about him. Well marsellus fucked him up good.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/085_you_remember_antwan_rockamora_half_black_half_samoan_used_to.mp3"
  },
  {
    "text": "You remember your business partner marsellus Wallace. don't you Brett Yeah I remember him Good.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/086_you_remember_your_business_partner_marsellus_wallace_don_t_y.mp3"
  },
  {
    "text": "You want to Rob banks I'm not saying I want to Rob banks. I'm just illustrating if we did it'd be easier than what we been doing. And no more liquor stores. What we been talking about Yeah no more liquor stores. Besides it ain't the giggle it used to be. There's too many foreigners own liquor stores. Vietnamese Koreans they don't even speak fucking English. Tell 'em empty out the register they don't know what you're talking about. They make it too personal. We keep on one of these gook...",
    "character": "",
    "audioUrl": "audio/pulp-fiction/087_you_want_to_rob_banks_i_m_not_saying_i_want_to_rob_banks_i_m.mp3"
  },
  {
    "text": "You were saying something about best intentions. What's the matter. Oh you were finished. Well allow me to retort.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/088_you_were_saying_something_about_best_intentions_what_s_the_m.mp3"
  },
  {
    "text": "You're a smart motherfucker That's right The metric system. What's in this.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/089_you_re_a_smart_motherfucker_that_s_right_the_metric_system_w.mp3"
  },
  {
    "text": "[first lines] Pumpkin: Forget it. Too risky. I'm through doing that shit. Yolanda: You always say that. That same thing every time, \"I'm through, never again, too dangerous\". Pumpkin: I know that's what I always say. I'm always right, too. Yolanda: But you forget about it in a day or two. Pumpkin: Yeah, well the days of me forgetting are over, and the days of me remembering have just begun.",
    "character": "",
    "audioUrl": "audio/pulp-fiction/090_first_lines_pumpkin_forget_it_too_risky_i_m_through_doing_t.mp3"
  }
];
