// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "Baby back bitch",
    "character": "",
    "audioUrl": "audio/the-longest-yard/001_baby_back_bitch.mp3"
  },
  {
    "text": "Ball dawg",
    "character": "",
    "audioUrl": "audio/the-longest-yard/002_ball_dawg.mp3"
  },
  {
    "text": "Get ready for an ass kicking fiesta",
    "character": "",
    "audioUrl": "audio/the-longest-yard/003_get_ready_for_an_ass_kicking_fiesta.mp3"
  },
  {
    "text": "Group hug in the shower tonight!",
    "character": "",
    "audioUrl": "audio/the-longest-yard/004_group_hug_in_the_shower_tonight.mp3"
  },
  {
    "text": "He broke my nose",
    "character": "",
    "audioUrl": "audio/the-longest-yard/005_he_broked_ed_my_nose.mp3"
  },
  {
    "text": "I didn’t do it",
    "character": "",
    "audioUrl": "audio/the-longest-yard/006_i_didn_t_do_it.mp3"
  },
  {
    "text": "It ain't easy, being cheesy!",
    "character": "",
    "audioUrl": "audio/the-longest-yard/007_it_ain_t_easy_being_cheesy.mp3"
  },
  {
    "text": "Rejected!",
    "character": "",
    "audioUrl": "audio/the-longest-yard/008_rejected.mp3"
  },
  {
    "text": "Shit Happens",
    "character": "",
    "audioUrl": "audio/the-longest-yard/009_shit_happens.mp3"
  },
  {
    "text": "That was a bullshit call!",
    "character": "",
    "audioUrl": "audio/the-longest-yard/010_that_was_a_bullshit_call.mp3"
  },
  {
    "text": "Who drank all the damn Gatorade!?",
    "character": "",
    "audioUrl": "audio/the-longest-yard/011_who_drank_all_the_damn_gatorade.mp3"
  },
  {
    "text": "You actin like a real McAsshole",
    "character": "",
    "audioUrl": "audio/the-longest-yard/012_you_actin_like_a_real_mcasshole.mp3"
  },
  {
    "text": "You all american son of a bitch",
    "character": "",
    "audioUrl": "audio/the-longest-yard/013_you_all_american_son_of_a_bitch.mp3"
  },
  {
    "text": "You're white, smile!",
    "character": "",
    "audioUrl": "audio/the-longest-yard/014_you_re_white_smile.mp3"
  }
];
