// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "A frickin 12 gauge",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/001_a_frickin_12_gauge.mp3"
  },
  {
    "text": "Ate all the frickin chips, Kip!",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/004_ate_all_the_frickin_chips_kip.mp3"
  },
  {
    "text": "Throw a pigskin a quarter mile",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/005_back_in_eighty_two_i_used_to_be_able_to_throw_a_pigskin_a_qu.mp3"
  },
  {
    "text": "Bike",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/006_bike.mp3"
  },
  {
    "text": "Bow to your sensei",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/007_bow_to_your_sensei.mp3"
  },
  {
    "text": "Can I have your tots",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/010_can_i_have_your_tots.mp3"
  },
  {
    "text": "Can I try it really quick?",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/011_can_i_try_it_really_quick.mp3"
  },
  {
    "text": "Can you bring me my chapstick?",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/012_can_you_bring_me_my_chapstick.mp3"
  },
  {
    "text": "Pay you in change",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/013_can_t_find_my_checkbook_hope_you_don_t_mind_if_i_pay_you_in.mp3"
  },
  {
    "text": "Car problem",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/014_car_problem.mp3"
  },
  {
    "text": "Chap stick",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/015_chap_stick.mp3"
  },
  {
    "text": "Chickens",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/016_chickens.mp3"
  },
  {
    "text": "Chips kip",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/017_chips_kip.mp3"
  },
  {
    "text": "Computer hacking skills",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/018_computer_hacking_skills.mp3"
  },
  {
    "text": "Dance!",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/019_dance.mp3"
  },
  {
    "text": "Dang",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/020_dang.mp3"
  },
  {
    "text": "Do the chickens have large talons?",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/023_do_the_chickens_have_large_talons.mp3"
  },
  {
    "text": "Chatting online with babes all day",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/024_don_t_be_jealous_i_ve_been_chatting_online_with_babes_all_da.mp3"
  },
  {
    "text": "Dump in the bed",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/026_dump_in_the_bed.mp3"
  },
  {
    "text": "Freakin Idiot",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/028_freakin_idiot.mp3"
  },
  {
    "text": "Gibberish",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/030_gibberish.mp3"
  },
  {
    "text": "Happy hands club",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/038_happy_hands_club.mp3"
  },
  {
    "text": "Throw a football over the mountains",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/046_how_much_you_wanna_make_a_bet_i_can_throw_a_football_over_th.mp3"
  },
  {
    "text": "How to get my haircut at the cotton corral",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/047_how_to_get_my_haircut_at_the_cotton_corral.mp3"
  },
  {
    "text": "Hunting wolverines",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/050_hunting_wolverines.mp3"
  },
  {
    "text": "I don't feel very good",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/053_i_don_t_feel_very_good.mp3"
  },
  {
    "text": "I forgot to put in the crystals",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/055_i_forgot_to_put_in_the_crystals.mp3"
  },
  {
    "text": "I like your sleeves, they're real big",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/059_i_like_your_sleeves_they_re_real_big.mp3"
  },
  {
    "text": "I say love, it is a flower",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/061_i_say_love_it_is_a_flower.mp3"
  },
  {
    "text": "I see you're drinking 1%",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/062_i_see_you_re_drinking_1.mp3"
  },
  {
    "text": "I want that",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/063_i_want_that.mp3"
  },
  {
    "text": "I'm voting for Pedro Sanchez",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/066_i_m_voting_for_pedro_sanchez.mp3"
  },
  {
    "text": "Idiot!",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/068_idiot.mp3"
  },
  {
    "text": "Is grandma there",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/070_is_grandma_there.mp3"
  },
  {
    "text": "It's pretty cool, I guess",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/074_it_s_pretty_cool_i_guess.mp3"
  },
  {
    "text": "Just listen to your heart",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/076_just_listen_to_your_heart.mp3"
  },
  {
    "text": "Kip and LaFawnduh's first date",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/079_kip_and_lafawnduh_s_first_date.mp3"
  },
  {
    "text": "Kip goes bowling",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/080_kip_goes_bowling.mp3"
  },
  {
    "text": "Detonators to blow Nessie out of the water",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/082_last_week_japanese_scientist_six_place_place_explosive_deton.mp3"
  },
  {
    "text": "Mole",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/089_mole.mp3"
  },
  {
    "text": "Nunchuck skills",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/093_nunchuck_skills.mp3"
  },
  {
    "text": "Pedro's feeling hot",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/098_pedro_s_feeling_hot.mp3"
  },
  {
    "text": "Probably the best drawing I've ever done",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/099_probably_the_best_drawing_i_ve_ever_done.mp3"
  },
  {
    "text": "Pull me in",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/101_pull_me_in.mp3"
  },
  {
    "text": "Rex Kwon Do sales pitch",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/102_rex_kwon_do_sales_pitch.mp3"
  },
  {
    "text": "Round house",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/103_round_house.mp3"
  },
  {
    "text": "She doesn't want you here",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/105_she_said_she_doesn_t_want_you_here_when_she_gets_back_becaus.mp3"
  },
  {
    "text": "Slap fight",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/108_slap_fight.mp3"
  },
  {
    "text": "We're pretty much friends, right?",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/109_so_me_and_you_are_pretty_much_friends_by_now_right.mp3"
  },
  {
    "text": "Soaking up the sun",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/111_soaking_up_solely.mp3"
  },
  {
    "text": "Gonna come out really nice",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/114_that_was_the_one_i_think_that_s_gonna_come_out_really_nice.mp3"
  },
  {
    "text": "What would you do in that situation?",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/119_they_kept_trying_to_attack_my_cousins_what_the_heck_would_yo.mp3"
  },
  {
    "text": "This is a girl",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/120_this_is_a_girl.mp3"
  },
  {
    "text": "Three feet of air",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/123_three_feet_of_air.mp3"
  },
  {
    "text": "Time machine",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/124_time_machine.mp3"
  },
  {
    "text": "Tupperware demo fail",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/128_tupperware_demo_fail.mp3"
  },
  {
    "text": "Uncle Rico back in '82",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/131_uncle_rico_back_in_82.mp3"
  },
  {
    "text": "Uncle Rico glory days",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/132_uncle_rico_glory_days.mp3"
  },
  {
    "text": "Uncle Rico go back in time",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/133_uncle_rico_go_back_in_time.mp3"
  },
  {
    "text": "Uncle Rico go pro",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/134_uncle_rico_go_pro.mp3"
  },
  {
    "text": "Nobody's going to go out with me",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/137_well_nobody_s_going_to_go_out_with_me.mp3"
  },
  {
    "text": "What kind of bike do you have",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/141_what_kind_of_bike_do_you_have.mp3"
  },
  {
    "text": "Yes",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/151_yes.mp3"
  },
  {
    "text": "Yes! Yes! Yes! Yes!",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/153_yes_yes_yes_yes.mp3"
  },
  {
    "text": "You ever take it off any sweet jumps",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/159_you_ever_take_it_off_any_sweet_jumps.mp3"
  },
  {
    "text": "You just come get me",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/164_you_just_come_get_maine.mp3"
  },
  {
    "text": "You're good at hooking up with chicks",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/165_you_re_good_at_hooking_up_with_chicks.mp3"
  },
  {
    "text": "Your mom goes to college",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/167_your_mom_goes_to_college.mp3"
  },
  {
    "text": "1% Milk",
    "character": "",
    "audioUrl": "audio/napoleon-dynamite/168_1_milk.mp3"
  }
];
