// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "A baby on a seven hour flight.",
    "character": "",
    "audioUrl": "audio/itysl-s1/001_a_baby_on_a_seven_hour_flight.mp3"
  },
  {
    "text": "A man rushed in from a car accident",
    "character": "",
    "audioUrl": "audio/itysl-s1/008_a_man_is_rushed_in_cause_he_was_in_a_car_accident.mp3"
  },
  {
    "text": "Admit it yourself that you suck.",
    "character": "",
    "audioUrl": "audio/itysl-s1/011_admit_it_yourself_that_you_suck.mp3"
  },
  {
    "text": "Dump it. Trash it. This one's garbage.",
    "character": "",
    "audioUrl": "audio/itysl-s1/028_all_right_you_know_what_this_is_dumb_dump_it_trash_it_this_o.mp3"
  },
  {
    "text": "Bring snacks so it feels like a real party.",
    "character": "",
    "audioUrl": "audio/itysl-s1/037_and_bring_snacks_so_it_feels_like_a_real_party.mp3"
  },
  {
    "text": "In a tradition... In a tradition.",
    "character": "",
    "audioUrl": "audio/itysl-s1/042_and_friendship_in_a_in_a_tradition_in_a_tradition.mp3"
  },
  {
    "text": "A metal bolt through his head",
    "character": "",
    "audioUrl": "audio/itysl-s1/044_and_he_has_a_metal_bolt_through_his_head.mp3"
  },
  {
    "text": "Help him! You got to help him!",
    "character": "",
    "audioUrl": "audio/itysl-s1/046_and_he_says_help_him_you_got_to_help_him.mp3"
  },
  {
    "text": "He'd have been so happy to see you",
    "character": "",
    "audioUrl": "audio/itysl-s1/047_and_he_would_have_been_so_happy_to_see_all_of_you_here_today.mp3"
  },
  {
    "text": "He's taking care of catering",
    "character": "",
    "audioUrl": "audio/itysl-s1/048_and_he_s_gonna_take_care_of_catering_for_the_whole_thing.mp3"
  },
  {
    "text": "You know what you didn't say?",
    "character": "",
    "audioUrl": "audio/itysl-s1/052_and_how_it_s_all_i_talk_about_but_you_know_what_you_didn_t_s.mp3"
  },
  {
    "text": "I vowed to devote the rest of my life",
    "character": "",
    "audioUrl": "audio/itysl-s1/058_and_i_vowed_from_that_day_forward_that_i_would_devote_the_re.mp3"
  },
  {
    "text": "I was worried you'd get cold.",
    "character": "",
    "audioUrl": "audio/itysl-s1/059_and_i_was_worried_you_were_gonna_get_cold.mp3"
  },
  {
    "text": "He brought his own much larger organ",
    "character": "",
    "audioUrl": "audio/itysl-s1/063_and_i_m_now_seeing_that_he_brought_his_own_much_larger_organ.mp3"
  },
  {
    "text": "The hole in your toilet had shrunk",
    "character": "",
    "audioUrl": "audio/itysl-s1/067_and_it_looked_like_the_hole_in_your_toilet_had_shrunk.mp3"
  },
  {
    "text": "Too bad nobody has video or anything",
    "character": "",
    "audioUrl": "audio/itysl-s1/070_and_it_s_too_bad_we_can_t_figure_it_out_cause_nobody_has_vid.mp3"
  },
  {
    "text": "Jerked you off until nothing came out",
    "character": "",
    "audioUrl": "audio/itysl-s1/072_and_jerked_you_off_until_nothing_came_out.mp3"
  },
  {
    "text": "Big old mud pie on your butt",
    "character": "",
    "audioUrl": "audio/itysl-s1/077_and_not_have_a_big_old_mud_pie_on_the_bottom_of_your_butt.mp3"
  },
  {
    "text": "The son of the deceased, to sing",
    "character": "",
    "audioUrl": "audio/itysl-s1/079_and_now_to_sing_a_song_the_son_of_the_deceased.mp3"
  },
  {
    "text": "Now, I will exact my revenge.",
    "character": "",
    "audioUrl": "audio/itysl-s1/083_and_now_i_will_exact_my_revenge.mp3"
  },
  {
    "text": "Raise the kids till they're grown",
    "character": "",
    "audioUrl": "audio/itysl-s1/085_and_raise_the_kids_until_they_re_out_of_the_house.mp3"
  },
  {
    "text": "Beet red for my family photo",
    "character": "",
    "audioUrl": "audio/itysl-s1/086_and_rest_up_so_my_face_isn_t_beet_red_for_my_family_photo_to.mp3"
  },
  {
    "text": "Santa and his elves worked so hard",
    "character": "",
    "audioUrl": "audio/itysl-s1/087_and_santa_and_all_his_elves_must_have_worked_so_hard_on_it.mp3"
  },
  {
    "text": "There's a lot of other stuff, too.",
    "character": "",
    "audioUrl": "audio/itysl-s1/105_and_there_s_a_lot_of_other_stuff_too.mp3"
  },
  {
    "text": "Running around the house as fast as they can",
    "character": "",
    "audioUrl": "audio/itysl-s1/107_and_they_both_start_running_around_the_house_as_fast_as_they.mp3"
  },
  {
    "text": "Bought you the entire dessert menu",
    "character": "",
    "audioUrl": "audio/itysl-s1/110_and_tried_to_make_it_up_to_you_by_buying_you_the_entire_dess.mp3"
  },
  {
    "text": "That little blue shirt",
    "character": "",
    "audioUrl": "audio/itysl-s1/114_and_why_would_it_be_wearing_that_little_blue_shirt.mp3"
  },
  {
    "text": "A cold front moving in",
    "character": "",
    "audioUrl": "audio/itysl-s1/115_and_with_a_cold_front_moving_in_from_the_northeast_it_s_goin.mp3"
  },
  {
    "text": "You never bothered to learn my name.",
    "character": "",
    "audioUrl": "audio/itysl-s1/116_and_you_all_never_bothered_to_learn_my_name.mp3"
  },
  {
    "text": "Attaboy! Good bone crushing.",
    "character": "",
    "audioUrl": "audio/itysl-s1/141_attaboy_that_s_good_bone_crushing.mp3"
  },
  {
    "text": "Baby Fubbins, 90th percentile in weight",
    "character": "",
    "audioUrl": "audio/itysl-s1/144_baby_fubbins_is_also_90th_percentile_in_weight.mp3"
  },
  {
    "text": "Baby Porkins is 99th percentile",
    "character": "",
    "audioUrl": "audio/itysl-s1/145_baby_porkins_is_99th_percentile.mp3"
  },
  {
    "text": "Beautiful words, Kyle.",
    "character": "",
    "audioUrl": "audio/itysl-s1/151_beautiful_words_kyle_your_father_would_have_been_so_proud.mp3"
  },
  {
    "text": "Too tired to do anything funny!",
    "character": "",
    "audioUrl": "audio/itysl-s1/155_because_of_you_i_was_too_tired_to_do_anything_funny.mp3"
  },
  {
    "text": "That's Bozo's voice.",
    "character": "",
    "audioUrl": "audio/itysl-s1/170_bozo_is_that_s_bozo_s_voice.mp3"
  },
  {
    "text": "Brown pie in my undies",
    "character": "",
    "audioUrl": "audio/itysl-s1/173_brown_pie_in_my_undies_make_it_look_like_i_shit_my_pants.mp3"
  },
  {
    "text": "Just for anyone who's concerned...",
    "character": "",
    "audioUrl": "audio/itysl-s1/175_but_first_i_do_want_to_say_just_for_anyone_who_s_concerned.mp3"
  },
  {
    "text": "Guest on The Colgate Comedy Hour",
    "character": "",
    "audioUrl": "audio/itysl-s1/177_but_he_was_also_a_frequent_guest_on_the_colgate_comedy_hour.mp3"
  },
  {
    "text": "The dog shouldn't get put down",
    "character": "",
    "audioUrl": "audio/itysl-s1/179_but_i_don_t_think_the_dog_should_get_put_down.mp3"
  },
  {
    "text": "Our gracious host didn't wipe properly.",
    "character": "",
    "audioUrl": "audio/itysl-s1/184_but_i_m_afraid_our_gracious_host_didn_t_wipe_properly.mp3"
  },
  {
    "text": "But if Melissa doesn't get sick,",
    "character": "",
    "audioUrl": "audio/itysl-s1/188_but_if_melissa_doesn_t_get_sick.mp3"
  },
  {
    "text": "But most of the time, I don't.",
    "character": "",
    "audioUrl": "audio/itysl-s1/190_but_most_of_the_time_i_don_t.mp3"
  },
  {
    "text": "TC Tuggers has this little knob",
    "character": "",
    "audioUrl": "audio/itysl-s1/191_but_tc_tuggers_has_this_little_knob_on_the_front.mp3"
  },
  {
    "text": "A joke hole that's just for farts!",
    "character": "",
    "audioUrl": "audio/itysl-s1/199_but_with_a_joke_hole_that_s_just_for_farts.mp3"
  },
  {
    "text": "A little cheese and one nugget of meat",
    "character": "",
    "audioUrl": "audio/itysl-s1/207_but_like_a_little_bit_of_cheese_and_maybe_one_little_nugget.mp3"
  },
  {
    "text": "Call Laser Spine Specialists",
    "character": "",
    "audioUrl": "audio/itysl-s1/211_call_laser_spine_specialists_for_your_no_cost_mri_review.mp3"
  },
  {
    "text": "Corporate actually listened to our request",
    "character": "",
    "audioUrl": "audio/itysl-s1/219_can_t_believe_corporate_actually_listened_to_our_request.mp3"
  },
  {
    "text": "Chunky eats your points and gets mad",
    "character": "",
    "audioUrl": "audio/itysl-s1/224_chunky_eats_your_points_and_he_gets_very_mad.mp3"
  },
  {
    "text": "Coach is nicer on international flights.",
    "character": "",
    "audioUrl": "audio/itysl-s1/226_coach_is_so_much_nicer_on_international_flights.mp3"
  },
  {
    "text": "Colleen, pick a square on the board.",
    "character": "",
    "audioUrl": "audio/itysl-s1/227_colleen_you_re_up_first_pick_a_square_on_the_board.mp3"
  },
  {
    "text": "Neither is your suit suit.",
    "character": "",
    "audioUrl": "audio/itysl-s1/234_confidence_is_not_your_strong_suit_neither_is_your_suit_suit.mp3"
  },
  {
    "text": "Say that about the nachos?",
    "character": "",
    "audioUrl": "audio/itysl-s1/243_did_he_ask_you_to_come_over_and_say_that_about_the_nachos.mp3"
  },
  {
    "text": "Did you ask him to come say that?",
    "character": "",
    "audioUrl": "audio/itysl-s1/244_did_you_ask_him_to_come_over_here_and_say_that.mp3"
  },
  {
    "text": "Does that count as my Christmas gift?",
    "character": "",
    "audioUrl": "audio/itysl-s1/248_does_that_count_as_what_i_get_for_christmas_as_my_gift.mp3"
  },
  {
    "text": "Big fan of his Angels and Archways clothing",
    "character": "",
    "audioUrl": "audio/itysl-s1/263_dude_i_am_such_a_big_fan_of_his_angels_and_archways_clothing.mp3"
  },
  {
    "text": "Replace your hairpiece with a balder one",
    "character": "",
    "audioUrl": "audio/itysl-s1/266_every_17_hours_replace_your_hairpiece_with_the_next_most_bal.mp3"
  },
  {
    "text": "Everybody's going to party at my house.",
    "character": "",
    "audioUrl": "audio/itysl-s1/268_everybody_s_going_to_party_at_my_house.mp3"
  },
  {
    "text": "50 Stanzo brand fedoras",
    "character": "",
    "audioUrl": "audio/itysl-s1/283_for_200_i_could_probably_get_50_stanzo_brand_fedoras.mp3"
  },
  {
    "text": "A thousand plastic meatballs",
    "character": "",
    "audioUrl": "audio/itysl-s1/284_for_200_i_could_probably_get_a_thousand_plastic_meatballs.mp3"
  },
  {
    "text": "A toilet the exact same size as yours",
    "character": "",
    "audioUrl": "audio/itysl-s1/285_for_a_toilet_the_exact_same_size_as_yours.mp3"
  },
  {
    "text": "Michael Patrick Porkins",
    "character": "",
    "audioUrl": "audio/itysl-s1/292_from_salisbury_north_carolina_michael_patrick_porkins.mp3"
  },
  {
    "text": "Get her out! Goddamn it!",
    "character": "",
    "audioUrl": "audio/itysl-s1/296_get_her_out_goddamn_it.mp3"
  },
  {
    "text": "Get in that random hot dog car...",
    "character": "",
    "audioUrl": "audio/itysl-s1/297_get_in_that_random_hot_dog_car.mp3"
  },
  {
    "text": "Get him out of here!",
    "character": "",
    "audioUrl": "audio/itysl-s1/300_get_him_out_of_here.mp3"
  },
  {
    "text": "That sounds like a good idea, yeah.",
    "character": "",
    "audioUrl": "audio/itysl-s1/312_good_that_sounds_like_a_good_idea_yeah.mp3"
  },
  {
    "text": "Hung like a horse?",
    "character": "",
    "audioUrl": "audio/itysl-s1/315_ha_is_that_what_they_mean_by_hung_like_a_horse.mp3"
  },
  {
    "text": "Victim of unfair treatment by a business?",
    "character": "",
    "audioUrl": "audio/itysl-s1/320_have_you_been_the_victim_of_unfair_treatment_by_a_business_o.mp3"
  },
  {
    "text": "He always had time for his kids.",
    "character": "",
    "audioUrl": "audio/itysl-s1/325_he_always_had_time_for_his_kids.mp3"
  },
  {
    "text": "Pulled your little dick out in front of everyone",
    "character": "",
    "audioUrl": "audio/itysl-s1/327_he_basically_pulled_your_little_dick_out_in_front_of_everyon.mp3"
  },
  {
    "text": "I am a star. Nobody tricked me.",
    "character": "",
    "audioUrl": "audio/itysl-s1/333_he_didn_t_trick_me_i_am_a_star_nobody_tricked_me.mp3"
  },
  {
    "text": "At least he didn't beat up Matt Simms",
    "character": "",
    "audioUrl": "audio/itysl-s1/341_he_may_be_weird_but_at_least_he_didn_t_beat_up_matt_simms.mp3"
  },
  {
    "text": "Mookie Kramer and the Eight Balls",
    "character": "",
    "audioUrl": "audio/itysl-s1/347_he_was_one_of_the_eight_balls_in_mookie_kramer_and_the_eight.mp3"
  },
  {
    "text": "He was trying to hump your head.",
    "character": "",
    "audioUrl": "audio/itysl-s1/348_he_was_trying_to_hump_your_head.mp3"
  },
  {
    "text": "The tobacco shop my mom buys cigars at",
    "character": "",
    "audioUrl": "audio/itysl-s1/349_he_works_at_the_tobacco_shop_my_mom_buys_cigars_at.mp3"
  },
  {
    "text": "I just got this new beat",
    "character": "",
    "audioUrl": "audio/itysl-s1/372_hey_listen_i_just_got_this_new_beat.mp3"
  },
  {
    "text": "I just heard an interview of this guy!",
    "character": "",
    "audioUrl": "audio/itysl-s1/375_hey_i_just_heard_an_interview_of_this_guy.mp3"
  },
  {
    "text": "How to search for it.",
    "character": "",
    "audioUrl": "audio/itysl-s1/391_how_to_search_for_it.mp3"
  },
  {
    "text": "I have not gone to the bathroom yet today",
    "character": "",
    "audioUrl": "audio/itysl-s1/395_i_am_now_sanitizing_my_hands_i_have_not_gone_to_the_bathroom.mp3"
  },
  {
    "text": "Finally fight my wife's new husband",
    "character": "",
    "audioUrl": "audio/itysl-s1/400_i_can_finally_fight_my_wife_s_new_husband_danny_crouse.mp3"
  },
  {
    "text": "You can't eat that.",
    "character": "",
    "audioUrl": "audio/itysl-s1/411_i_could_save_your_life_right_now_don_t_eat_you_can_t_eat_tha.mp3"
  },
  {
    "text": "Addicted to your phone",
    "character": "",
    "audioUrl": "audio/itysl-s1/412_i_criticized_you_for_being_addicted_to_your_phone.mp3"
  },
  {
    "text": "I don't know why I got the sticker, man!",
    "character": "",
    "audioUrl": "audio/itysl-s1/418_i_don_t_know_why_i_got_the_fucking_sticker_man.mp3"
  },
  {
    "text": "A different guy is dubbing over it",
    "character": "",
    "audioUrl": "audio/itysl-s1/425_i_feel_like_it_makes_more_sense_that_a_different_guy_is_dubb.mp3"
  },
  {
    "text": "I fucking hate her. Such an idiot.",
    "character": "",
    "audioUrl": "audio/itysl-s1/426_i_fucking_hate_her_such_an_idiot.mp3"
  },
  {
    "text": "I guess if nobody wants this car,",
    "character": "",
    "audioUrl": "audio/itysl-s1/431_i_guess_if_nobody_wants_this_car.mp3"
  },
  {
    "text": "A viral video where Bozo dubs over",
    "character": "",
    "audioUrl": "audio/itysl-s1/432_i_guess_it_s_like_a_viral_video_where_bozo_dubs_over.mp3"
  },
  {
    "text": "Hope nobody goes home and fucks my mom",
    "character": "",
    "audioUrl": "audio/itysl-s1/443_i_hope_nobody_goes_home_and_fucks_my_mom.mp3"
  },
  {
    "text": "Can't remember how you type it in",
    "character": "",
    "audioUrl": "audio/itysl-s1/447_i_just_can_t_remember_exactly_how_you_type_it_in.mp3"
  },
  {
    "text": "I know these names better than my grandmother's",
    "character": "",
    "audioUrl": "audio/itysl-s1/454_i_know_these_names_better_than_i_know_my_own_grandmother_s.mp3"
  },
  {
    "text": "I make ten times as much as you.",
    "character": "",
    "audioUrl": "audio/itysl-s1/462_i_make_ten_times_as_much_as_you.mp3"
  },
  {
    "text": "Fedoras for a baby shower, though?",
    "character": "",
    "audioUrl": "audio/itysl-s1/464_i_mean_i_don_t_know_about_fedoras_for_a_baby_shower_though.mp3"
  },
  {
    "text": "All my money on the Jim Davis house",
    "character": "",
    "audioUrl": "audio/itysl-s1/474_i_saw_how_you_said_i_spent_all_my_money_on_the_jim_davis_hou.mp3"
  },
  {
    "text": "I was gonna embarrass you, Barry.",
    "character": "",
    "audioUrl": "audio/itysl-s1/483_i_told_you_i_told_you_i_was_gonna_embarrass_you_barry.mp3"
  },
  {
    "text": "You said no PDA. Remember?",
    "character": "",
    "audioUrl": "audio/itysl-s1/487_i_tried_to_give_you_those_little_kisses_and_you_said_no_pda.mp3"
  },
  {
    "text": "It goes both ways",
    "character": "",
    "audioUrl": "audio/itysl-s1/492_i_was_here_yesterday_and_it_actually_goes_both_ways.mp3"
  },
  {
    "text": "Complain about the rule",
    "character": "",
    "audioUrl": "audio/itysl-s1/495_i_went_up_there_to_complain_about_the_rule.mp3"
  },
  {
    "text": "Call up Paul's daughter Olivia",
    "character": "",
    "audioUrl": "audio/itysl-s1/499_i_would_like_to_now_call_up_paul_s_daughter_olivia.mp3"
  },
  {
    "text": "Hope I didn't talk too much",
    "character": "",
    "audioUrl": "audio/itysl-s1/500_i_i_feel_good_about_it_i_hope_i_didn_t_do_too_much_talking.mp3"
  },
  {
    "text": "Any volunteer from the audience",
    "character": "",
    "audioUrl": "audio/itysl-s1/503_i_d_like_to_pick_from_the_audience_any_volunteer.mp3"
  },
  {
    "text": "I'm chill, huge fan",
    "character": "",
    "audioUrl": "audio/itysl-s1/513_i_m_chill_i_m_just_like_such_a_huge_fan_of_his_music_and_his.mp3"
  },
  {
    "text": "Take as many suits as I can grab",
    "character": "",
    "audioUrl": "audio/itysl-s1/521_i_m_just_gonna_take_as_many_suits_as_i_can_grab.mp3"
  },
  {
    "text": "Rushed to the hospital",
    "character": "",
    "audioUrl": "audio/itysl-s1/527_i_m_rushed_to_the_hospital_and_there_for_hours.mp3"
  },
  {
    "text": "Another ten, fifteen, hang tight?",
    "character": "",
    "audioUrl": "audio/itysl-s1/531_i_m_sorry_guys_it_s_gonna_be_another_ten_fifteen_if_you_can.mp3"
  },
  {
    "text": "Taffy Lee Fubbins, Best Baby",
    "character": "",
    "audioUrl": "audio/itysl-s1/544_if_taffy_lee_fubbins_isn_t_the_best_baby_of_the_year.mp3"
  },
  {
    "text": "If two people order nachos to share",
    "character": "",
    "audioUrl": "audio/itysl-s1/546_if_two_people_order_nachos_to_share.mp3"
  },
  {
    "text": "Keep asking, I'll beat the crap out of you",
    "character": "",
    "audioUrl": "audio/itysl-s1/549_if_you_keep_asking_me_questions_i_m_gonna_beat_the_crap_out.mp3"
  },
  {
    "text": "Talk about the hit and run, I'll kill you",
    "character": "",
    "audioUrl": "audio/itysl-s1/550_if_you_keep_talking_about_the_hit_and_run_i_m_gonna_fucking.mp3"
  },
  {
    "text": "If you love it as much as you say",
    "character": "",
    "audioUrl": "audio/itysl-s1/551_if_you_love_it_as_much_as_you_say_you_do.mp3"
  },
  {
    "text": "Something that's more you",
    "character": "",
    "audioUrl": "audio/itysl-s1/552_if_you_want_to_exchange_it_for_something_that_s_more_you.mp3"
  },
  {
    "text": "This year we were excited to welcome",
    "character": "",
    "audioUrl": "audio/itysl-s1/555_in_fact_this_year_we_were_excited_to_welcome.mp3"
  },
  {
    "text": "In the locker room, in front of everyone",
    "character": "",
    "audioUrl": "audio/itysl-s1/559_in_the_locker_room_in_front_of_everyone.mp3"
  },
  {
    "text": "10th percentile in height",
    "character": "",
    "audioUrl": "audio/itysl-s1/561_in_weight_and_10th_percentile_in_height.mp3"
  },
  {
    "text": "Instead of a real smile",
    "character": "",
    "audioUrl": "audio/itysl-s1/562_instead_of_giving_someone_a_real_smile.mp3"
  },
  {
    "text": "A horse with a short peanut",
    "character": "",
    "audioUrl": "audio/itysl-s1/566_is_it_easy_to_find_a_horse_with_a_short_peanut_like_this.mp3"
  },
  {
    "text": "Sunday funday with these idiots",
    "character": "",
    "audioUrl": "audio/itysl-s1/574_is_this_good_i_said_sunday_funday_with_these_idiots.mp3"
  },
  {
    "text": "Could be any one of us. Ooh ooh!",
    "character": "",
    "audioUrl": "audio/itysl-s1/578_it_could_literally_be_any_one_of_us_ooh_ooh.mp3"
  },
  {
    "text": "One view, uploaded at 6 a.m.",
    "character": "",
    "audioUrl": "audio/itysl-s1/580_it_has_one_view_and_it_says_it_was_uploaded_at_6_00_a_m_this.mp3"
  },
  {
    "text": "You said you don't like any PDA",
    "character": "",
    "audioUrl": "audio/itysl-s1/588_it_was_the_same_dinner_that_you_said_you_don_t_like_any_pda.mp3"
  },
  {
    "text": "He was just faking it",
    "character": "",
    "audioUrl": "audio/itysl-s1/589_it_wasn_t_stuck_at_all_he_was_just_faking_it.mp3"
  },
  {
    "text": "Riding with a loved one",
    "character": "",
    "audioUrl": "audio/itysl-s1/592_it_s_a_beautiful_fall_day_and_you_re_riding_with_a_loved_one.mp3"
  },
  {
    "text": "It's a Chunky!",
    "character": "",
    "audioUrl": "audio/itysl-s1/593_it_s_a_chunky.mp3"
  },
  {
    "text": "Wilson's sends 500 little wigs",
    "character": "",
    "audioUrl": "audio/itysl-s1/600_it_s_easy_when_you_sign_up_wilson_s_will_send_500_little_wig.mp3"
  },
  {
    "text": "Marcus 'The Worm' Hicks",
    "character": "",
    "audioUrl": "audio/itysl-s1/608_it_s_jazz_legend_marcus_the_worm_hicks.mp3"
  },
  {
    "text": "Not exactly in my Q zone",
    "character": "",
    "audioUrl": "audio/itysl-s1/614_it_s_not_exactly_in_my_q_zone_is_it.mp3"
  },
  {
    "text": "It's a rule the restaurant has",
    "character": "",
    "audioUrl": "audio/itysl-s1/617_it_s_not_you_it_s_a_rule_the_restaurant_has.mp3"
  },
  {
    "text": "He hasn't touched my gift receipt",
    "character": "",
    "audioUrl": "audio/itysl-s1/631_jacob_hasn_t_touched_my_gift_receipt_because_he_likes_my_gif.mp3"
  },
  {
    "text": "You don't remember that night",
    "character": "",
    "audioUrl": "audio/itysl-s1/634_jeez_you_don_t_remember_that_night.mp3"
  },
  {
    "text": "Jerk your little boy dick off",
    "character": "",
    "audioUrl": "audio/itysl-s1/635_jerk_your_little_boy_dick_off.mp3"
  },
  {
    "text": "Take your car and get out of here",
    "character": "",
    "audioUrl": "audio/itysl-s1/648_just_take_your_car_and_get_out_of_here.mp3"
  },
  {
    "text": "Like I was a representative",
    "character": "",
    "audioUrl": "audio/itysl-s1/667_like_i_was_some_sort_of_representative_or_something.mp3"
  },
  {
    "text": "Like mostly just chips",
    "character": "",
    "audioUrl": "audio/itysl-s1/668_like_mostly_just_chips.mp3"
  },
  {
    "text": "Like, no records of 'em",
    "character": "",
    "audioUrl": "audio/itysl-s1/673_like_there_s_like_no_records_of_em.mp3"
  },
  {
    "text": "Not supposed to be around here",
    "character": "",
    "audioUrl": "audio/itysl-s1/674_like_they_re_not_even_supposed_to_be_around_in_the_area.mp3"
  },
  {
    "text": "Gazpacho soup in your fridge",
    "character": "",
    "audioUrl": "audio/itysl-s1/675_listen_i_saw_you_had_some_gazpacho_soup_in_your_fridge.mp3"
  },
  {
    "text": "Meatball down my leg",
    "character": "",
    "audioUrl": "audio/itysl-s1/702_meatball_down_my_leg_make_it_look_like_my_ball_sack_ripped_o.mp3"
  },
  {
    "text": "Over time, it will grow mold",
    "character": "",
    "audioUrl": "audio/itysl-s1/704_melted_or_cold_from_the_cow_s_udders_over_time_it_will_grow.mp3"
  },
  {
    "text": "Motorcycle with no motor?",
    "character": "",
    "audioUrl": "audio/itysl-s1/707_motorcycle_with_no_motor.mp3"
  },
  {
    "text": "Most aggressive baby I've ever met",
    "character": "",
    "audioUrl": "audio/itysl-s1/709_mr_jarvis_is_one_of_the_most_aggressive_babies_i_ve_ever_met.mp3"
  },
  {
    "text": "One mean bastard to give this so early",
    "character": "",
    "audioUrl": "audio/itysl-s1/710_must_be_one_mean_bastard_to_give_us_this_so_early.mp3"
  },
  {
    "text": "It's a studded leather belt",
    "character": "",
    "audioUrl": "audio/itysl-s1/711_my_belt_right_now_it_s_a_studded_leather_belt.mp3"
  },
  {
    "text": "Crap from your mob movie",
    "character": "",
    "audioUrl": "audio/itysl-s1/717_my_friends_aren_t_gonna_buy_the_crap_from_your_mob_movie.mp3"
  },
  {
    "text": "No matter how busy he was",
    "character": "",
    "audioUrl": "audio/itysl-s1/723_no_matter_how_busy_he_was.mp3"
  },
  {
    "text": "Scamming adults into thinking they're stars",
    "character": "",
    "audioUrl": "audio/itysl-s1/724_no_more_scamming_adults_into_thinking_they_re_stars.mp3"
  },
  {
    "text": "No space for mother in law",
    "character": "",
    "audioUrl": "audio/itysl-s1/727_no_space_for_mother_in_law.mp3"
  },
  {
    "text": "He was a funny magician",
    "character": "",
    "audioUrl": "audio/itysl-s1/728_no_he_was_just_joking_around_he_was_a_funny_magician.mp3"
  },
  {
    "text": "Saying what he wanted to say",
    "character": "",
    "audioUrl": "audio/itysl-s1/729_no_he_s_saying_what_he_wanted_to_say_on_the_show_now.mp3"
  },
  {
    "text": "I eat paper all the time!",
    "character": "",
    "audioUrl": "audio/itysl-s1/730_no_i_eat_paper_all_the_time.mp3"
  },
  {
    "text": "Nothing rare in there",
    "character": "",
    "audioUrl": "audio/itysl-s1/733_no_it_just_means_you_don_t_have_anything_rare_in_there.mp3"
  },
  {
    "text": "Just say the restaurant has a rule",
    "character": "",
    "audioUrl": "audio/itysl-s1/735_no_just_say_the_restaurant_has_a_rule.mp3"
  },
  {
    "text": "This is Caleb fucking Went",
    "character": "",
    "audioUrl": "audio/itysl-s1/740_no_what_the_fuck_are_you_doing_this_is_caleb_fucking_went_ju.mp3"
  },
  {
    "text": "The style is just basically this",
    "character": "",
    "audioUrl": "audio/itysl-s1/741_no_yeah_the_style_is_just_is_just_basically_this.mp3"
  },
  {
    "text": "Nobody should feel sad at all",
    "character": "",
    "audioUrl": "audio/itysl-s1/749_nobody_should_feel_sad_at_all.mp3"
  },
  {
    "text": "Nobody wants a thousand plastic meatballs!",
    "character": "",
    "audioUrl": "audio/itysl-s1/750_nobody_wants_a_thousand_plastic_meatballs.mp3"
  },
  {
    "text": "My stomach's absolutely fucked",
    "character": "",
    "audioUrl": "audio/itysl-s1/756_now_my_stomach_s_absolutely_fucked.mp3"
  },
  {
    "text": "Clown mask lady falls off the couch",
    "character": "",
    "audioUrl": "audio/itysl-s1/764_of_the_dancing_lady_in_the_clown_mask_who_falls_off_the_couc.mp3"
  },
  {
    "text": "Thought this guy was bald!",
    "character": "",
    "audioUrl": "audio/itysl-s1/769_oh_fuck_i_thought_this_guy_s_supposed_to_be_bald.mp3"
  },
  {
    "text": "Little individual bottles of champagne",
    "character": "",
    "audioUrl": "audio/itysl-s1/778_oh_maybe_we_could_give_everybody_little_individual_bottles_o.mp3"
  },
  {
    "text": "It was just a magic act, Brenda",
    "character": "",
    "audioUrl": "audio/itysl-s1/780_oh_my_god_it_was_just_a_magic_act_brenda.mp3"
  },
  {
    "text": "Oh my, this is perfect",
    "character": "",
    "audioUrl": "audio/itysl-s1/792_oh_my_this_is_perfect.mp3"
  },
  {
    "text": "Our organist Peg is under the weather",
    "character": "",
    "audioUrl": "audio/itysl-s1/799_oh_our_organist_peg_is_under_the_weather.mp3"
  },
  {
    "text": "Oh, shit! Shit!",
    "character": "",
    "audioUrl": "audio/itysl-s1/800_oh_shit_shit.mp3"
  },
  {
    "text": "Household names like Roy Donk",
    "character": "",
    "audioUrl": "audio/itysl-s1/808_oh_you_mean_like_household_names_like_roy_donk.mp3"
  },
  {
    "text": "She was a pretty woman",
    "character": "",
    "audioUrl": "audio/itysl-s1/828_okay_she_was_a_pretty_woman.mp3"
  },
  {
    "text": "I've got Lev in my car, follow us",
    "character": "",
    "audioUrl": "audio/itysl-s1/838_okay_you_guys_i_ve_got_lev_in_my_car_so_just_follow_us.mp3"
  },
  {
    "text": "Welcome him on stage, come on up",
    "character": "",
    "audioUrl": "audio/itysl-s1/850_okay_let_s_welcome_him_on_stage_come_on_up.mp3"
  },
  {
    "text": "Okay, that's fine, uh...",
    "character": "",
    "audioUrl": "audio/itysl-s1/851_okay_okay_that_s_fine_uh.mp3"
  },
  {
    "text": "Can't take all the ones with meat",
    "character": "",
    "audioUrl": "audio/itysl-s1/857_one_person_can_t_take_the_ones_with_meat_and_stuff.mp3"
  },
  {
    "text": "Pub crawls in 'em like the Snuggie",
    "character": "",
    "audioUrl": "audio/itysl-s1/861_or_do_pub_crawls_in_em_like_the_snuggie.mp3"
  },
  {
    "text": "Wrote The Munsters' theme song",
    "character": "",
    "audioUrl": "audio/itysl-s1/862_or_jack_marshall_who_wrote_the_munsters_theme_song.mp3"
  },
  {
    "text": "Spanking my bare butt, balls and back",
    "character": "",
    "audioUrl": "audio/itysl-s1/866_or_would_you_be_spanking_my_bare_butt_balls_and_back.mp3"
  },
  {
    "text": "Why would it be allowed in here",
    "character": "",
    "audioUrl": "audio/itysl-s1/867_otherwise_why_would_it_be_allowed_in_here.mp3"
  },
  {
    "text": "Our first five inch horse penis",
    "character": "",
    "audioUrl": "audio/itysl-s1/869_our_first_five_inch_horse_penis.mp3"
  },
  {
    "text": "Ow! What is this?",
    "character": "",
    "audioUrl": "audio/itysl-s1/871_ow_what_is_this.mp3"
  },
  {
    "text": "Panty jobs, homegrown Simpsons stuff",
    "character": "",
    "audioUrl": "audio/itysl-s1/872_panty_jobs_homegrown_simpsons_stuff.mp3"
  },
  {
    "text": "Oral on the mystery judge",
    "character": "",
    "audioUrl": "audio/itysl-s1/878_performing_oral_on_the_mystery_judge_of_the_competition.mp3"
  },
  {
    "text": "Permission to go home and watch TV",
    "character": "",
    "audioUrl": "audio/itysl-s1/879_permission_to_go_home_lie_down_and_watch_some_tv.mp3"
  },
  {
    "text": "Planning on relaxing? [chuckling]",
    "character": "",
    "audioUrl": "audio/itysl-s1/880_planning_on_relaxing_chuckling.mp3"
  },
  {
    "text": "It's already a party house",
    "character": "",
    "audioUrl": "audio/itysl-s1/881_plus_it_s_already_like_a_party_house_so_he_ll_want_to_go_the.mp3"
  },
  {
    "text": "Pornhub, Xtube...",
    "character": "",
    "audioUrl": "audio/itysl-s1/882_pornhub_xtube.mp3"
  },
  {
    "text": "Reggie, did you make this last night?",
    "character": "",
    "audioUrl": "audio/itysl-s1/889_reggie_did_you_make_this_thing_last_night_so_you_d_have_a_vi.mp3"
  },
  {
    "text": "Santa himself brought this early",
    "character": "",
    "audioUrl": "audio/itysl-s1/894_santa_himself_brought_this_here_early.mp3"
  },
  {
    "text": "Santa should have wrapped it",
    "character": "",
    "audioUrl": "audio/itysl-s1/895_santa_should_have_wrapped_it_when_he_gave_it_early.mp3"
  },
  {
    "text": "Shit! Shit! No! No!",
    "character": "",
    "audioUrl": "audio/itysl-s1/907_shit_shit_no_no.mp3"
  },
  {
    "text": "It's a new arrangement",
    "character": "",
    "audioUrl": "audio/itysl-s1/913_sir_it_s_not_a_gospel_song_it_s_a_new_arrangement.mp3"
  },
  {
    "text": "Skeletrex and his Bone Brigade",
    "character": "",
    "audioUrl": "audio/itysl-s1/919_skeletrex_and_his_bone_brigade_have_enslaved_the_human_race.mp3"
  },
  {
    "text": "Pig dicks or bags of meat?",
    "character": "",
    "audioUrl": "audio/itysl-s1/920_so_are_we_the_pig_dicks_or_the_bags_of_meat.mp3"
  },
  {
    "text": "Babysitter did art with the kids",
    "character": "",
    "audioUrl": "audio/itysl-s1/931_so_the_babysitter_did_art_with_the_kids_that_s_cool.mp3"
  },
  {
    "text": "A replacement organist for the day",
    "character": "",
    "audioUrl": "audio/itysl-s1/933_so_we_have_a_replacement_organist_for_the_day.mp3"
  },
  {
    "text": "Hot dog car through the window!",
    "character": "",
    "audioUrl": "audio/itysl-s1/950_someone_drove_a_hot_dog_shaped_car_through_the_window.mp3"
  },
  {
    "text": "Sorry I'm late, very rude of me",
    "character": "",
    "audioUrl": "audio/itysl-s1/953_sorry_i_m_late_everyone_it_s_very_rude_of_me_i_apologize.mp3"
  },
  {
    "text": "Steve makes one Christmas joke",
    "character": "",
    "audioUrl": "audio/itysl-s1/963_steve_makes_one_christmas_joke.mp3"
  },
  {
    "text": "Huge mud pies and over flushing?",
    "character": "",
    "audioUrl": "audio/itysl-s1/973_taking_huge_mud_pies_and_over_flushing.mp3"
  },
  {
    "text": "More bone soldiers",
    "character": "",
    "audioUrl": "audio/itysl-s1/974_taking_their_bones_and_using_them_to_make_more_bone_soldiers.mp3"
  },
  {
    "text": "Made you look like a fool, Charlie",
    "character": "",
    "audioUrl": "audio/itysl-s1/992_that_fat_piece_of_shit_made_you_look_like_a_fool_charlie.mp3"
  },
  {
    "text": "I bought the creator of Garfield's house",
    "character": "",
    "audioUrl": "audio/itysl-s1/995_that_i_bought_jim_davis_house_the_creator_of_garfield.mp3"
  },
  {
    "text": "That I miss my family photo tonight?",
    "character": "",
    "audioUrl": "audio/itysl-s1/998_that_i_miss_my_family_photo_tonight.mp3"
  },
  {
    "text": "A termite infestation in the moldings",
    "character": "",
    "audioUrl": "audio/itysl-s1/1010_that_there_was_a_termite_infestation_in_the_walls_and_in_the.mp3"
  },
  {
    "text": "Christine is gonna love that",
    "character": "",
    "audioUrl": "audio/itysl-s1/1025_that_s_perfect_christine_is_gonna_love_that.mp3"
  },
  {
    "text": "Cops were like, oh yeah, this is fine",
    "character": "",
    "audioUrl": "audio/itysl-s1/1035_the_cops_were_just_like_oh_yeah_this_is_fine.mp3"
  },
  {
    "text": "The deceased taught us a lot about life",
    "character": "",
    "audioUrl": "audio/itysl-s1/1037_the_deceased_taught_us_all_a_lot_about_life.mp3"
  },
  {
    "text": "Voice of the Road Runner. Beep beep",
    "character": "",
    "audioUrl": "audio/itysl-s1/1044_the_guy_who_did_the_voice_of_the_road_runner_beep_beep.mp3"
  },
  {
    "text": "The mouth on the thing doesn't move!",
    "character": "",
    "audioUrl": "audio/itysl-s1/1049_the_mouth_on_the_thing_doesn_t_move.mp3"
  },
  {
    "text": "Kept me out of college",
    "character": "",
    "audioUrl": "audio/itysl-s1/1050_the_next_trick_is_something_that_kept_me_out_of_college_for.mp3"
  },
  {
    "text": "KFC sign through their front window",
    "character": "",
    "audioUrl": "audio/itysl-s1/1052_the_one_where_you_can_see_the_kfc_sign_through_their_front_w.mp3"
  },
  {
    "text": "Society of Arts and Music",
    "character": "",
    "audioUrl": "audio/itysl-s1/1057_the_president_of_the_marjorie_caldwell_society_of_arts_and_m.mp3"
  },
  {
    "text": "Third phase, we hit up Instagram",
    "character": "",
    "audioUrl": "audio/itysl-s1/1062_the_third_phase_we_hit_up_instagram_and.mp3"
  },
  {
    "text": "Two hours, in and out of there",
    "character": "",
    "audioUrl": "audio/itysl-s1/1069_then_for_over_two_hours_they_take_turns_going_in_and_out_of.mp3"
  },
  {
    "text": "If I take the receipt back",
    "character": "",
    "audioUrl": "audio/itysl-s1/1072_then_it_shouldn_t_be_a_problem_if_i_take_the_receipt_back.mp3"
  },
  {
    "text": "Not important, they don't matter",
    "character": "",
    "audioUrl": "audio/itysl-s1/1103_they_re_just_like_not_important_like_they_don_t_matter.mp3"
  },
  {
    "text": "This guy's about to jack off",
    "character": "",
    "audioUrl": "audio/itysl-s1/1112_this_guy_s_about_to_jack_off.mp3"
  },
  {
    "text": "A betrayal no one's ever seen!",
    "character": "",
    "audioUrl": "audio/itysl-s1/1113_this_is_a_betrayal_on_levels_that_no_one_s_ever_seen.mp3"
  },
  {
    "text": "It's somber, all right to cry",
    "character": "",
    "audioUrl": "audio/itysl-s1/1121_this_one_is_somber_so_it_s_all_right_to_cry.mp3"
  },
  {
    "text": "Covered head to toe in shit",
    "character": "",
    "audioUrl": "audio/itysl-s1/1123_this_place_is_covered_head_to_toe_in_shit.mp3"
  },
  {
    "text": "To ask if we could switch tables",
    "character": "",
    "audioUrl": "audio/itysl-s1/1132_to_ask_if_we_could_switch_tables.mp3"
  },
  {
    "text": "My revenge on you, little baby",
    "character": "",
    "audioUrl": "audio/itysl-s1/1136_to_getting_my_revenge_on_you_little_baby.mp3"
  },
  {
    "text": "Tons that just blow me away",
    "character": "",
    "audioUrl": "audio/itysl-s1/1144_tons_i_can_think_of_that_just_blow_me_away.mp3"
  },
  {
    "text": "Tragically, he passed this year",
    "character": "",
    "audioUrl": "audio/itysl-s1/1147_tragically_he_passed_early_this_year.mp3"
  },
  {
    "text": "Type in Bozo Dubbed Over",
    "character": "",
    "audioUrl": "audio/itysl-s1/1152_type_in_bozo_dubbed_over.mp3"
  },
  {
    "text": "Can't eat all the fully loaded nachos",
    "character": "",
    "audioUrl": "audio/itysl-s1/1158_uh_one_person_can_t_just_eat_all_the_fully_loaded_nachos.mp3"
  },
  {
    "text": "I don't have any qualms",
    "character": "",
    "audioUrl": "audio/itysl-s1/1164_uh_i_don_t_have_any_qualms.mp3"
  },
  {
    "text": "Newscaster on the roller coaster",
    "character": "",
    "audioUrl": "audio/itysl-s1/1187_we_have_to_watch_the_guy_with_the_newscaster_on_the_roller_c.mp3"
  },
  {
    "text": "Get this thing really popping off!",
    "character": "",
    "audioUrl": "audio/itysl-s1/1191_we_just_need_a_couple_more_dollars_to_get_this_thing_really.mp3"
  },
  {
    "text": "Gospel records ain't selling no more",
    "character": "",
    "audioUrl": "audio/itysl-s1/1213_we_re_sorry_gospel_records_ain_t_selling_no_more.mp3"
  },
  {
    "text": "Guest on The Colgate Comedy Hour",
    "character": "",
    "audioUrl": "audio/itysl-s1/1217_well_he_was_a_frequent_guest_on_the_colgate_comedy_hour.mp3"
  },
  {
    "text": "Mark nearly hit his head on the counter",
    "character": "",
    "audioUrl": "audio/itysl-s1/1221_well_last_night_mark_fell_down_and_nearly_hit_his_head_on_th.mp3"
  },
  {
    "text": "Not if you go through someone's trash",
    "character": "",
    "audioUrl": "audio/itysl-s1/1222_well_not_if_you_go_through_someone_s_trash.mp3"
  },
  {
    "text": "What game show had swearing in it?",
    "character": "",
    "audioUrl": "audio/itysl-s1/1250_what_game_show_have_you_ever_seen_that_had_swearing_in_it.mp3"
  },
  {
    "text": "What I don't make a habit of doing",
    "character": "",
    "audioUrl": "audio/itysl-s1/1255_what_i_don_t_like_to_make_a_habit_of_doing.mp3"
  },
  {
    "text": "What society, that we tape everything?",
    "character": "",
    "audioUrl": "audio/itysl-s1/1262_what_is_this_society_that_we_tape_everything.mp3"
  },
  {
    "text": "What the fuck?",
    "character": "",
    "audioUrl": "audio/itysl-s1/1267_what_the_fuck.mp3"
  },
  {
    "text": "Chunky, you can't wreck his shirt",
    "character": "",
    "audioUrl": "audio/itysl-s1/1270_what_the_hell_are_you_doing_chunky_you_can_t_wreck_his_shirt.mp3"
  },
  {
    "text": "What the hell are you talking about?",
    "character": "",
    "audioUrl": "audio/itysl-s1/1272_what_the_hell_are_you_talking_about.mp3"
  },
  {
    "text": "I had a whole song wrote",
    "character": "",
    "audioUrl": "audio/itysl-s1/1275_what_the_hell_was_that_man_i_had_a_whole_song_wrote.mp3"
  },
  {
    "text": "Make sure nobody hit my car",
    "character": "",
    "audioUrl": "audio/itysl-s1/1276_what_the_i_got_to_check_this_out_to_make_sure_that_nobody_hi.mp3"
  },
  {
    "text": "Never heard anything like that before",
    "character": "",
    "audioUrl": "audio/itysl-s1/1287_what_i_ve_never_heard_anything_like_that_before.mp3"
  },
  {
    "text": "Made to feel less of a man",
    "character": "",
    "audioUrl": "audio/itysl-s1/1296_when_all_of_a_sudden_you_re_made_to_feel_less_of_a_man.mp3"
  },
  {
    "text": "In London, I was a shell of a man",
    "character": "",
    "audioUrl": "audio/itysl-s1/1297_when_i_arrived_in_london_i_was_a_shell_of_a_man.mp3"
  },
  {
    "text": "Everyone watched an adult man",
    "character": "",
    "audioUrl": "audio/itysl-s1/1306_while_everyone_else_had_to_watch_an_adult_man.mp3"
  },
  {
    "text": "Let's enjoy a beautiful song",
    "character": "",
    "audioUrl": "audio/itysl-s1/1319_why_don_t_we_listen_to_and_enjoy_a_beautiful_song.mp3"
  },
  {
    "text": "Now you can be the life of the party",
    "character": "",
    "audioUrl": "audio/itysl-s1/1324_wilson_s_now_you_can_be_the_life_of_the_party.mp3"
  },
  {
    "text": "Minimally invasive spine surgery",
    "character": "",
    "audioUrl": "audio/itysl-s1/1327_with_our_minimally_invasive_spine_surgery.mp3"
  },
  {
    "text": "Fake Gorilla Attack hair removal",
    "character": "",
    "audioUrl": "audio/itysl-s1/1330_with_wilson_s_natural_fake_gorilla_attack_hair_removal_syste.mp3"
  },
  {
    "text": "You're still a great doctor",
    "character": "",
    "audioUrl": "audio/itysl-s1/1379_yeah_don_t_let_it_ruin_your_day_okay_you_re_still_a_great_do.mp3"
  },
  {
    "text": "Yes! Yeah!",
    "character": "",
    "audioUrl": "audio/itysl-s1/1392_yes_yeah.mp3"
  },
  {
    "text": "The bell already rang",
    "character": "",
    "audioUrl": "audio/itysl-s1/1399_you_can_t_be_in_the_hall_when_the_bell_rang_the_bell_already.mp3"
  },
  {
    "text": "What Herbie's music is against",
    "character": "",
    "audioUrl": "audio/itysl-s1/1428_you_know_that_s_what_herbie_s_music_is_against.mp3"
  },
  {
    "text": "The weather, obviously",
    "character": "",
    "audioUrl": "audio/itysl-s1/1432_you_know_the_weather_obviously_woman_mm_hm.mp3"
  },
  {
    "text": "You make ten times what he makes",
    "character": "",
    "audioUrl": "audio/itysl-s1/1433_you_make_ten_times_what_he_makes_why_didn_t_you_say_that_to.mp3"
  },
  {
    "text": "You probably love your mother in law",
    "character": "",
    "audioUrl": "audio/itysl-s1/1437_you_probably_love_your_mother_in_law.mp3"
  },
  {
    "text": "Spent my life savings to go to London",
    "character": "",
    "audioUrl": "audio/itysl-s1/1444_you_see_i_had_spent_my_entire_life_savings_to_go_to_london.mp3"
  },
  {
    "text": "Their bones were money, like four times",
    "character": "",
    "audioUrl": "audio/itysl-s1/1446_you_talked_about_how_their_bones_were_money_like_four_times.mp3"
  },
  {
    "text": "Your family, your job, your leisure time",
    "character": "",
    "audioUrl": "audio/itysl-s1/1471_your_family_your_job_even_your_leisure_time.mp3"
  },
  {
    "text": "Very meat and potatoes, Liz",
    "character": "",
    "audioUrl": "audio/itysl-s1/1475_your_record_collection_s_very_meat_and_potatoes_liz.mp3"
  },
  {
    "text": "Your shirt gets kind of bunched up",
    "character": "",
    "audioUrl": "audio/itysl-s1/1476_your_shirt_gets_kind_of_bunched_up.mp3"
  },
  {
    "text": "Pancaked by drunk dump truck driver",
    "character": "",
    "audioUrl": "audio/itysl-s1/1479_92_pancaked_by_drunk_dump_truck_driver.mp3"
  },
  {
    "text": "I was just trying Don't talk!",
    "character": "",
    "audioUrl": "audio/itysl-s1/1494_chunky_i_was_just_trying_well_don_t_talk.mp3"
  },
  {
    "text": "Don't throw away Don't talk!",
    "character": "",
    "audioUrl": "audio/itysl-s1/1495_chunky_well_don_t_throw_away_don_t_talk.mp3"
  },
  {
    "text": "[horn honking, menacing music]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1497_continuous_horn_honking_menacing_music_playing.mp3"
  },
  {
    "text": "[dog barking, horn honking]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1500_dog_barking_continuous_horn_honking.mp3"
  },
  {
    "text": "[xylophone] Hush little baby",
    "character": "",
    "audioUrl": "audio/itysl-s1/1503_eerie_xylophone_playing_hush_little_baby_don_t_say_a_word.mp3"
  },
  {
    "text": "Paul! You flinch!",
    "character": "",
    "audioUrl": "audio/itysl-s1/1507_group_celebrates_paul_you_flinch.mp3"
  },
  {
    "text": "Uh oh! You got a Chunky!",
    "character": "",
    "audioUrl": "audio/itysl-s1/1514_hip_hop_beat_playing_uh_oh_you_got_a_chunky.mp3"
  },
  {
    "text": "You can say anything you want",
    "character": "",
    "audioUrl": "audio/itysl-s1/1519_man_remind_me_the_rules_again_you_can_say_anything_you_want.mp3"
  },
  {
    "text": "Small whimpers at first",
    "character": "",
    "audioUrl": "audio/itysl-s1/1522_menacing_music_playing_small_whimpers_at_first.mp3"
  },
  {
    "text": "You had all summer to think of it",
    "character": "",
    "audioUrl": "audio/itysl-s1/1537_uptempo_jingle_playing_you_had_all_summer_to_think_of_it.mp3"
  },
  {
    "text": "All Garfield. Do you know how hard that is?",
    "character": "",
    "audioUrl": "audio/itysl-s1/1539_whispers_all_garfield_do_you_know_how_hard_that_is_for_me.mp3"
  },
  {
    "text": "All right, Team One, let's go",
    "character": "",
    "audioUrl": "audio/itysl-s1/1550_all_right_team_one_let_s_go_okay.mp3"
  },
  {
    "text": "I'm sick off of your mud pie",
    "character": "",
    "audioUrl": "audio/itysl-s1/1553_and_now_i_m_sick_off_of_your_mud_pie_what_the_hell_are_you_t.mp3"
  },
  {
    "text": "What the fuck, he wrecked my shirt",
    "character": "",
    "audioUrl": "audio/itysl-s1/1557_before_you_come_out_here_go_what_the_fuck_man_he_wrecked_my.mp3"
  },
  {
    "text": "You can't just sit wherever",
    "character": "",
    "audioUrl": "audio/itysl-s1/1559_but_can_t_i_stay_here_you_can_t_just_sit_wherever.mp3"
  },
  {
    "text": "Oh my God, Dave",
    "character": "",
    "audioUrl": "audio/itysl-s1/1570_dave_man_oh_my_god_dave.mp3"
  },
  {
    "text": "Don't touch my ride!",
    "character": "",
    "audioUrl": "audio/itysl-s1/1571_do_not_touch_me_don_t_touch_my_ride.mp3"
  },
  {
    "text": "Do you have a solution?",
    "character": "",
    "audioUrl": "audio/itysl-s1/1596_how_would_i_help_you_out_i_don_t_know_do_you_have_a_solution.mp3"
  },
  {
    "text": "It's a guaranteed goddamn hit",
    "character": "",
    "audioUrl": "audio/itysl-s1/1598_i_can_t_sing_it_s_a_guaranteed_goddamn_hit_all_right.mp3"
  },
  {
    "text": "I don't know what The Colgate Hour is",
    "character": "",
    "audioUrl": "audio/itysl-s1/1601_i_don_t_know_what_the_colgate_hour_is_okay_pass_okay.mp3"
  },
  {
    "text": "I don't know. Not sure",
    "character": "",
    "audioUrl": "audio/itysl-s1/1602_i_don_t_know_not_sure.mp3"
  },
  {
    "text": "He's choking. This guy's on the phone",
    "character": "",
    "audioUrl": "audio/itysl-s1/1611_i_m_with_my_friend_he_s_choking_choked_this_guy_s_on_the_pho.mp3"
  },
  {
    "text": "Or what about a little candle?",
    "character": "",
    "audioUrl": "audio/itysl-s1/1648_oh_or_what_about_like_a_little_candle.mp3"
  },
  {
    "text": "Previously on River Mountain High",
    "character": "",
    "audioUrl": "audio/itysl-s1/1663_previously_on_river_mountain_high_you_re_hiding_something.mp3"
  },
  {
    "text": "Reggie, what's your favorite?",
    "character": "",
    "audioUrl": "audio/itysl-s1/1665_reggie_what_s_your_favorite_uh_i_don_t_know_what_my_favorite.mp3"
  },
  {
    "text": "Call the police! Yeah, that's one idea",
    "character": "",
    "audioUrl": "audio/itysl-s1/1682_someone_call_the_police_yeah_that_s_one_idea.mp3"
  },
  {
    "text": "A TC Topp from TC Tuggers",
    "character": "",
    "audioUrl": "audio/itysl-s1/1691_that_s_a_cool_shirt_yeah_it_s_a_tc_topp_from_tc_tuggers.mp3"
  },
  {
    "text": "It is cheese",
    "character": "",
    "audioUrl": "audio/itysl-s1/1694_that_s_right_it_is_cheese_cheering_and_applause.mp3"
  },
  {
    "text": "Not real people, the cops said",
    "character": "",
    "audioUrl": "audio/itysl-s1/1697_they_re_not_like_real_people_kinda_the_cops_said_that.mp3"
  },
  {
    "text": "Mix it professionally",
    "character": "",
    "audioUrl": "audio/itysl-s1/1706_to_mix_it_professionally_you_listen_to_me.mp3"
  },
  {
    "text": "Um, the third phase, we...",
    "character": "",
    "audioUrl": "audio/itysl-s1/1711_um_the_third_phase_we_distant_car_horn_honking.mp3"
  },
  {
    "text": "Poppers are here",
    "character": "",
    "audioUrl": "audio/itysl-s1/1712_unbelievable_poppers_are_here_who_wants_one.mp3"
  },
  {
    "text": "Oh yeah, I almost forgot",
    "character": "",
    "audioUrl": "audio/itysl-s1/1717_what_oh_yeah_i_almost_forgot.mp3"
  },
  {
    "text": "What the hell is all this stuff?",
    "character": "",
    "audioUrl": "audio/itysl-s1/1722_what_the_hell_is_all_this_stuff_yeah_should_we_do_this_somew.mp3"
  },
  {
    "text": "'Cause I didn't ask for that",
    "character": "",
    "audioUrl": "audio/itysl-s1/1724_what_cause_i_didn_t_ask_for_that.mp3"
  },
  {
    "text": "That's my backpack",
    "character": "",
    "audioUrl": "audio/itysl-s1/1734_what_s_this_you_have_a_bag_what_the_hell_that_s_my_backpack.mp3"
  },
  {
    "text": "Yeah! [cheering]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1742_yeah_all_cheering.mp3"
  },
  {
    "text": "A dumdum, term of endearment",
    "character": "",
    "audioUrl": "audio/itysl-s1/1745_you_called_me_a_dumdum_right_it_s_like_a_term_of_endearment.mp3"
  },
  {
    "text": "What's the joke, exactly?",
    "character": "",
    "audioUrl": "audio/itysl-s1/1751_you_know_it_s_just_a_joke_what_s_the_joke_exactly.mp3"
  },
  {
    "text": "Caked in pure shit",
    "character": "",
    "audioUrl": "audio/itysl-s1/1758_cause_he_s_gonna_pretend_he_s_not_sick_even_if_it_s_caked_i.mp3"
  },
  {
    "text": "Waiting for the private bathroom",
    "character": "",
    "audioUrl": "audio/itysl-s1/1767_earlier_today_when_i_was_waiting_to_use_the_private_bathroo.mp3"
  },
  {
    "text": "Steering wheel fly off, I'm toast",
    "character": "",
    "audioUrl": "audio/itysl-s1/1773_if_the_steering_wheel_fly_off_i_m_toast.mp3"
  },
  {
    "text": "Hardest letter I've had to write",
    "character": "",
    "audioUrl": "audio/itysl-s1/1774_mark_this_is_the_hardest_letter_i_ve_ever_had_to_write.mp3"
  },
  {
    "text": "Not part of the Turbo Team!",
    "character": "",
    "audioUrl": "audio/itysl-s1/1781_you_re_not_part_of_the_turbo_team_don_t_run.mp3"
  },
  {
    "text": "[Big Flame by Doris Wilson]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1784_big_flame_is_gonna_break_my_heart_in_two_by_doris_wilson_pl.mp3"
  },
  {
    "text": "[Big Flame by Doris Wilson]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1785_big_flame_is_gonna_break_my_heart_in_two_by_doris_wilson_pl.mp3"
  },
  {
    "text": "[Big Flame by Doris Wilson]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1786_big_flame_is_gonna_break_my_heart_in_two_by_doris_wilson_pl.mp3"
  },
  {
    "text": "[Big Flame by Doris Wilson]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1787_big_flame_is_gonna_break_my_heart_in_two_by_doris_wilson_pl.mp3"
  },
  {
    "text": "[Big Flame by Doris Wilson]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1788_big_flame_is_gonna_break_my_heart_in_two_by_doris_wilson_pl.mp3"
  },
  {
    "text": "[Big Flame by Doris Wilson]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1789_big_flame_is_gonna_break_my_heart_in_two_by_doris_wilson_pl.mp3"
  },
  {
    "text": "[Big Flame by Doris Wilson]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1793_big_flame_is_gonna_break_my_heart_in_two_by_doris_wilson_pl.mp3"
  },
  {
    "text": "[Big Flame by Doris Wilson]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1794_big_flame_is_gonna_break_my_heart_in_two_by_doris_wilson_pl.mp3"
  },
  {
    "text": "[Big Flame by Doris Wilson]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1795_big_flame_is_gonna_break_my_heart_in_two_by_doris_wilson.mp3"
  },
  {
    "text": "[Big Flame by Doris Wilson]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1796_big_flame_is_gonna_break_my_heart_in_two_by_doris_wilson.mp3"
  },
  {
    "text": "[Blending Soul by Soul Blenders]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1798_blending_soul_by_soul_blenders_playing.mp3"
  },
  {
    "text": "[Blending Soul by Soul Blenders]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1799_blending_soul_by_soul_blenders_playing.mp3"
  },
  {
    "text": "Who took my cigars?",
    "character": "",
    "audioUrl": "audio/itysl-s1/1812_as_mob_movie_character_hey_who_took_my_cigars.mp3"
  },
  {
    "text": "What the hell's going on out there?",
    "character": "",
    "audioUrl": "audio/itysl-s1/1830_choked_what_the_heck_what_the_hell_s_going_on_out_there.mp3"
  },
  {
    "text": "[circus music]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1843_circus_music_playing_on_video.mp3"
  },
  {
    "text": "♪ Who will be Baby of the Year? ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/1862_crooning_who_will_be_the_baby_of_the_year.mp3"
  },
  {
    "text": "I'm sorry! I'm so sorry!",
    "character": "",
    "audioUrl": "audio/itysl-s1/1874_frenzied_driver_i_m_sorry_i_m_so_sorry.mp3"
  },
  {
    "text": "[funk music]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1876_funk_music_playing.mp3"
  },
  {
    "text": "[funky music]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1877_funky_music_playing.mp3"
  },
  {
    "text": "Gonna embarrass you, Barry",
    "character": "",
    "audioUrl": "audio/itysl-s1/1888_groans_i_m_gonna_embarrass_you_at_this_party_barry.mp3"
  },
  {
    "text": "[heavenly music]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1896_heavenly_music_playing.mp3"
  },
  {
    "text": "That naughty old elf",
    "character": "",
    "audioUrl": "audio/itysl-s1/1911_in_husky_voice_oh_that_naughty_old_elf.mp3"
  },
  {
    "text": "As painful and sad as today is...",
    "character": "",
    "audioUrl": "audio/itysl-s1/1938_man_as_painful_and_sad_as_today_is.mp3"
  },
  {
    "text": "Oh fuck, a clownputer?",
    "character": "",
    "audioUrl": "audio/itysl-s1/1947_man_oh_fuck_a_clownputer.mp3"
  },
  {
    "text": "This bike's a piece of shit",
    "character": "",
    "audioUrl": "audio/itysl-s1/1956_man_this_little_fucking_bike_s_a_piece_of_shit.mp3"
  },
  {
    "text": "[melody stops]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1968_melody_stopping.mp3"
  },
  {
    "text": "[muffled wailing]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1972_muffled_wailing.mp3"
  },
  {
    "text": "[music stops]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1976_music_stopping.mp3"
  },
  {
    "text": "[speech drowned out by honking]",
    "character": "",
    "audioUrl": "audio/itysl-s1/1984_priest_s_speech_drowned_out_by_honking.mp3"
  },
  {
    "text": "[yelling in agony]",
    "character": "",
    "audioUrl": "audio/itysl-s1/2003_yelling_in_agony.mp3"
  },
  {
    "text": "♪ Yah yah yah yah yah yah ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2004_yah_yah_yah_yah_yah_yah.mp3"
  },
  {
    "text": "♪ This big flame's gonna break my heart ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2009_this_big_flame_boy_is_gonna_break_my_heart_in_two.mp3"
  },
  {
    "text": "♪ The night the skeletons came to life ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2014_it_was_also_the_night_that_the_skeletons_came_to_life.mp3"
  },
  {
    "text": "♪ Riding shotgun in your car ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2017_now_i_m_riding_shotgun_in_your_car.mp3"
  },
  {
    "text": "♪ This big flame's gonna break my heart ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2018_this_big_flame_boy_is_gonna_break_my_heart_in_two.mp3"
  },
  {
    "text": "♪ It's burning hot ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2021_and_believe_me_when_i_say_it_s_burning_hot.mp3"
  },
  {
    "text": "♪ A big flame in my heart ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2022_a_big_flame_in_my_heart.mp3"
  },
  {
    "text": "♪ Mmm, baby, baby, ba ba bay ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2025_mmm_baby_baby_ba_ba_bay.mp3"
  },
  {
    "text": "♪ Whoa, baby, baby, ba ba bay ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2027_whoa_baby_baby_ba_ba_bay.mp3"
  },
  {
    "text": "[stirring music]",
    "character": "",
    "audioUrl": "audio/itysl-s1/2029_stirring_music.mp3"
  },
  {
    "text": "♪ And He shall set you free ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2034_and_he_shall_set_you_free.mp3"
  },
  {
    "text": "♪ Lay your head in the river ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2035_and_you_lay_your_head_in_the_river.mp3"
  },
  {
    "text": "♪ Who will be Baby of the Year? ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2039_oh_who_will_be_baby_of_the_year.mp3"
  },
  {
    "text": "♪ This big flame's gonna break my heart ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2049_this_big_flame_boy_is_gonna_break_my_heart_in_two.mp3"
  },
  {
    "text": "♪ Even though we are through ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2050_even_though_we_are_through.mp3"
  },
  {
    "text": "♪ Friday night ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2055_friday_night.mp3"
  },
  {
    "text": "♪ Studded belt, three stacks on the radio ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2056_studded_belt_pole_cut_three_stacks_on_the_radio.mp3"
  },
  {
    "text": "♪ Hair flying across your face ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2057_blowing_hair_flying_across_your_face.mp3"
  },
  {
    "text": "♪ Like explorers going 65 ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2058_we_drive_through_the_city_like_explorers_going_65.mp3"
  },
  {
    "text": "♪ I'm thinking that we just might ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2061_i_m_thinking_that_we_just_might.mp3"
  },
  {
    "text": "♪ This big flame's gonna break my heart ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2065_this_big_flame_boy_is_gonna_break_my_heart_in_two.mp3"
  },
  {
    "text": "♪ Even though we are through ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2066_even_though_we_are_through.mp3"
  },
  {
    "text": "♪ It's burning hot ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2068_and_believe_me_when_i_say_it_s_burning_hot.mp3"
  },
  {
    "text": "♪ A big flame in my heart ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2071_a_big_flame_in_my_heart.mp3"
  },
  {
    "text": "♪ Gonna make a big noise ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2073_gonna_take_it_to_the_street_now_we_re_gonna_make_a_big_nois.mp3"
  },
  {
    "text": "♪ Pull it out, they turn to bones ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2075_but_if_they_pull_it_out_they_turn_to_bones.mp3"
  },
  {
    "text": "♪ The bones are their dollars ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2085_the_bones_are_their_dollars_and.mp3"
  },
  {
    "text": "♪ The day Robert Palins murdered me ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2094_the_day_robert_palins_murdered_me.mp3"
  },
  {
    "text": "♪ The day Robert Palins shot me down ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2096_the_day_robert_palins_shot_me_down.mp3"
  },
  {
    "text": "♪ Baby, baby, ba ba bay ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2099_baby_baby_baby_baby_ba_ba_bay.mp3"
  },
  {
    "text": "♪ Palm tree girls, palm tree guys ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2106_palm_tree_girls_the_palm_tree_guys.mp3"
  },
  {
    "text": "♪ Palins grabbed the preacher's daughter ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2110_they_palins_grabbed_the_preacher_s_daughter.mp3"
  },
  {
    "text": "♪ Baby, baby, ba ba bay ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2111_baby_baby_baby_ba_ba_bay.mp3"
  },
  {
    "text": "♪ My sweet Marie cried for me ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2112_my_sweet_marie_she_cried_for_me.mp3"
  },
  {
    "text": "♪ The night the skeletons came to life ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2115_and_it_was_also_the_night_that_the_skeletons_came_to_life.mp3"
  },
  {
    "text": "♪ Rode into town on a jet black mare ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2116_he_rode_into_town_on_a_jet_black_mare.mp3"
  },
  {
    "text": "♪ Just to float and not sink ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2121_just_to_float_and_not_sink.mp3"
  },
  {
    "text": "♪ Mama's gonna buy you a mockingbird ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2126_mama_s_gonna_buy_you_a_mockingbird.mp3"
  },
  {
    "text": "♪ Even though we are through ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2128_even_though_we_are_through.mp3"
  },
  {
    "text": "♪ Heads are round, bellies are squishy ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2129_heads_are_round_bellies_are_squishy.mp3"
  },
  {
    "text": "Sponsored by TC Topps",
    "character": "",
    "audioUrl": "audio/itysl-s1/2132_woman_river_mountain_high_is_sponsored_by_tc_topps_tc_tugge.mp3"
  },
  {
    "text": "♪ Can they be tricked? Can they be chucked? ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2134_can_they_be_tricked_can_they_be_chucked.mp3"
  },
  {
    "text": "♪ Left on Friday, now it's Saturday ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2136_we_left_on_friday_now_it_s_saturday.mp3"
  },
  {
    "text": "♪ Dick watch hanging low ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2141_sunglasses_flaring_out_dick_watch_hanging_low.mp3"
  },
  {
    "text": "♪ Run away to someplace ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2146_run_away_to_someplace_we.mp3"
  },
  {
    "text": "♪ Even though we are through ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2147_even_though_we_are_through.mp3"
  },
  {
    "text": "♪ It's burning hot ♪",
    "character": "",
    "audioUrl": "audio/itysl-s1/2153_and_believe_me_when_i_say_it_s_burning_hot.mp3"
  }
];
