// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "Beneath the man",
    "character": "",
    "audioUrl": "audio/nacho-libre/003_and_beneath_the_man.mp3"
  },
  {
    "text": "Be grateful",
    "character": "",
    "audioUrl": "audio/nacho-libre/006_be_grateful.mp3"
  },
  {
    "text": "Encarnacion!",
    "character": "",
    "audioUrl": "audio/nacho-libre/040_encarnacion_encarnacion_encarnacion_encarnacion.mp3"
  },
  {
    "text": "Forced baptism",
    "character": "",
    "audioUrl": "audio/nacho-libre/041_forced_baptism.mp3"
  },
  {
    "text": "Save me a piece of that corn",
    "character": "",
    "audioUrl": "audio/nacho-libre/058_hello_i_m_talking_to_you_i_will_come_save_me_a_piece_of_that.mp3"
  },
  {
    "text": "Hug hug kiss kiss",
    "character": "",
    "audioUrl": "audio/nacho-libre/077_hug_hug_kiss_kiss_hug_hug_big_kiss_little_hug_kiss_kiss_litt.mp3"
  },
  {
    "text": "Hug, hug, kiss, kiss",
    "character": "",
    "audioUrl": "audio/nacho-libre/078_hug_hug_kiss_kiss.mp3"
  },
  {
    "text": "My turn to sing",
    "character": "",
    "audioUrl": "audio/nacho-libre/081_i_am_singing_at_the_party_i_am_singing_it_s_my_turn_to_sing.mp3"
  },
  {
    "text": "Gatekeeper of my destiny",
    "character": "",
    "audioUrl": "audio/nacho-libre/082_i_am_the_gatekeeper_of_my_own_destiny_and_i_will_have_my_glo.mp3"
  },
  {
    "text": "Going into the wilderness",
    "character": "",
    "audioUrl": "audio/nacho-libre/086_i_don_t_belong_out_there_and_i_don_t_belong_in_here_so_i_m_g.mp3"
  },
  {
    "text": "Wake up at 5 a.m.",
    "character": "",
    "audioUrl": "audio/nacho-libre/089_i_get_to_wake_up_every_morning_at_5_a_m.mp3"
  },
  {
    "text": "I hate orphans",
    "character": "",
    "audioUrl": "audio/nacho-libre/091_i_hate_orphans.mp3"
  },
  {
    "text": "Pile drive to the face",
    "character": "",
    "audioUrl": "audio/nacho-libre/100_i_know_it_is_fun_to_wrestle_a_nice_pile_drive_to_the_face_or.mp3"
  },
  {
    "text": "Beneath a man, his nucleus",
    "character": "",
    "audioUrl": "audio/nacho-libre/107_i_mean_yes_they_may_have_the_appearance_of_riches_but_beneat.mp3"
  },
  {
    "text": "A signature and a picture",
    "character": "",
    "audioUrl": "audio/nacho-libre/111_i_was_wondering_if_the_children_could_get_a_signature_from_y.mp3"
  },
  {
    "text": "Swallow the eagle's yolk",
    "character": "",
    "audioUrl": "audio/nacho-libre/127_in_order_for_you_to_become_empowered_by_the_eagle_you_must_c.mp3"
  },
  {
    "text": "Loved you as a brother",
    "character": "",
    "audioUrl": "audio/nacho-libre/134_know_that_i_ve_always_loved_you_as_a_brother_in_god.mp3"
  },
  {
    "text": "Free creams and lotions",
    "character": "",
    "audioUrl": "audio/nacho-libre/140_listen_i_know_the_wrestlers_get_all_the_fancy_ladies_and_the.mp3"
  },
  {
    "text": "May he rest in peace",
    "character": "",
    "audioUrl": "audio/nacho-libre/148_may_he_rest_in_peace.mp3"
  },
  {
    "text": "My turn to sing",
    "character": "",
    "audioUrl": "audio/nacho-libre/152_my_turn_to_sing_at_the_party.mp3"
  },
  {
    "text": "My turn to sing",
    "character": "",
    "audioUrl": "audio/nacho-libre/153_my_turn_to_sing_at_the_party.mp3"
  },
  {
    "text": "Nacho Libre",
    "character": "",
    "audioUrl": "audio/nacho-libre/156_nacho_libre.mp3"
  },
  {
    "text": "Stretchy",
    "character": "",
    "audioUrl": "audio/nacho-libre/158_nacho_libre_stretchy.mp3"
  },
  {
    "text": "Nachoooooo!",
    "character": "",
    "audioUrl": "audio/nacho-libre/165_nachoooooo.mp3"
  },
  {
    "text": "Fight for something noble",
    "character": "",
    "audioUrl": "audio/nacho-libre/167_no_if_you_fight_for_something_noble_or_for_someone_who_needs.mp3"
  },
  {
    "text": "Wrestling servant of you",
    "character": "",
    "audioUrl": "audio/nacho-libre/172_okay_if_i_win_tonight_at_the_battle_jam_i_will_know_that_you.mp3"
  },
  {
    "text": "Cooking duty, dead guy duty",
    "character": "",
    "audioUrl": "audio/nacho-libre/174_okay_maybe_i_am_not_meant_for_these_duties_cooking_duty_dead.mp3"
  },
  {
    "text": "Okay, orphans",
    "character": "",
    "audioUrl": "audio/nacho-libre/180_okay_orphans.mp3"
  },
  {
    "text": "Such a stinky warrior",
    "character": "",
    "audioUrl": "audio/nacho-libre/182_precious_father_why_have_you_given_me_this_desire_to_wrestle.mp3"
  },
  {
    "text": "She hails from the convent",
    "character": "",
    "audioUrl": "audio/nacho-libre/195_she_hails_from_the_oaxaca_parish_convent_of_the_immaculate_h.mp3"
  },
  {
    "text": "Pretty dang exciting, huh",
    "character": "",
    "audioUrl": "audio/nacho-libre/198_so_now_you_got_a_little_taste_of_what_i_do_it_s_pretty_dang.mp3"
  },
  {
    "text": "The best in the whole world",
    "character": "",
    "audioUrl": "audio/nacho-libre/199_so_what_you_re_saying_to_me_is_if_i_can_eat_this_yolk_my_mov.mp3"
  },
  {
    "text": "Stretchy pants",
    "character": "",
    "audioUrl": "audio/nacho-libre/205_sometimes_you_wear_stretchy_pants.mp3"
  },
  {
    "text": "Those eggs were a lie!",
    "character": "",
    "audioUrl": "audio/nacho-libre/225_those_eggs_were_a_lie_steven_a_lie_they_gave_me_no_eagle_pow.mp3"
  },
  {
    "text": "I'd break my vow",
    "character": "",
    "audioUrl": "audio/nacho-libre/228_to_kiss_your_mouth_i_d_break_my_vow_no_no_no.mp3"
  },
  {
    "text": "Throwing daisies at him",
    "character": "",
    "audioUrl": "audio/nacho-libre/230_today_i_saw_a_man_in_town_people_were_throwing_daisies_at_hi.mp3"
  },
  {
    "text": "Fight the seven strongest men",
    "character": "",
    "audioUrl": "audio/nacho-libre/233_tonight_i_will_fight_the_seven_strongest_men_in_town_maybe_t.mp3"
  },
  {
    "text": "Whatever",
    "character": "",
    "audioUrl": "audio/nacho-libre/248_whatever.mp3"
  },
  {
    "text": "Sometimes you wear stretchy pants",
    "character": "",
    "audioUrl": "audio/nacho-libre/250_when_you_are_a_man_sometimes_you_wear_stretchy_pants_in_your.mp3"
  },
  {
    "text": "Diarrhea since Easters",
    "character": "",
    "audioUrl": "audio/nacho-libre/264_your_only_job_is_to_cook_do_you_not_realize_i_have_had_diarr.mp3"
  }
];
