// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "Anywhere I want",
    "character": "",
    "audioUrl": "audio/this-is-the-end/001_anywhere_i_want.mp3"
  },
  {
    "text": "Bang Bang Your'e dead",
    "character": "",
    "audioUrl": "audio/this-is-the-end/002_bang_bang_your_e_dead.mp3"
  },
  {
    "text": "Bang, bang, bang, you're dead. Pow, pow, pow. Stop, guys. Stop fucking with the gun.",
    "character": "",
    "audioUrl": "audio/this-is-the-end/003_bang_bang_bang_you_re_dead_pow_pow_pow_stop_guys_stop_fuckin.mp3"
  },
  {
    "text": "Because if you want me to tell you fuck you, I will so good. Ohh you love.",
    "character": "",
    "audioUrl": "audio/this-is-the-end/004_because_if_you_want_me_to_tell_you_fuck_you_i_will_so_good_o.mp3"
  },
  {
    "text": "Does this coke smell funny",
    "character": "",
    "audioUrl": "audio/this-is-the-end/005_does_this_coke_smell_funny.mp3"
  },
  {
    "text": "Does this Coke Smell Funny",
    "character": "",
    "audioUrl": "audio/this-is-the-end/006_does_this_coke_smell_funny.mp3"
  },
  {
    "text": "Fuck Michael cera",
    "character": "",
    "audioUrl": "audio/this-is-the-end/007_fuck_michael_cera.mp3"
  },
  {
    "text": "Fuck Yeah",
    "character": "",
    "audioUrl": "audio/this-is-the-end/008_fuck_yeah.mp3"
  },
  {
    "text": "Fuck yeah",
    "character": "",
    "audioUrl": "audio/this-is-the-end/009_fuck_yeah.mp3"
  },
  {
    "text": "Good Morning Sunshine",
    "character": "",
    "audioUrl": "audio/this-is-the-end/010_good_morning_sunshine.mp3"
  },
  {
    "text": "Guys, guys, wake up. Danny's alive. He's eating all the fucking phone.",
    "character": "",
    "audioUrl": "audio/this-is-the-end/011_guys_guys_wake_up_danny_s_alive_he_s_eating_all_the_fucking.mp3"
  },
  {
    "text": "He's Eating All the Fucking Food",
    "character": "",
    "audioUrl": "audio/this-is-the-end/012_he_s_eating_all_the_fucking_food.mp3"
  },
  {
    "text": "Heading fucking Tatum. I found him wandering on the freeway. I collected them, made my bitch get off my Dick.",
    "character": "",
    "audioUrl": "audio/this-is-the-end/013_heading_fucking_tatum_i_found_him_wandering_on_the_freeway_i.mp3"
  },
  {
    "text": "Hey does this coke smell funny?",
    "character": "",
    "audioUrl": "audio/this-is-the-end/014_hey_does_this_coke_smell_funny.mp3"
  },
  {
    "text": "I call him Channing Tate. Yum.",
    "character": "",
    "audioUrl": "audio/this-is-the-end/015_i_call_him_channing_tate_yum.mp3"
  },
  {
    "text": "I have a particularly explosive ejaculate. It just goes everywhere.",
    "character": "",
    "audioUrl": "audio/this-is-the-end/016_i_have_a_particularly_explosive_ejaculate_it_just_goes_every.mp3"
  },
  {
    "text": "I say unto thee. The power of Christ compels you. Doesn't compel me.",
    "character": "",
    "audioUrl": "audio/this-is-the-end/017_i_say_unto_thee_the_power_of_christ_compels_you_doesn_t_comp.mp3"
  },
  {
    "text": "I'm not gonna shoot Emma Watson.",
    "character": "",
    "audioUrl": "audio/this-is-the-end/018_i_m_not_gonna_shoot_emma_watson.mp3"
  },
  {
    "text": "Jonah Plays With The Gun",
    "character": "",
    "audioUrl": "audio/this-is-the-end/019_jonah_plays_with_the_gun.mp3"
  },
  {
    "text": "Let's do all the drugs.",
    "character": "",
    "audioUrl": "audio/this-is-the-end/020_let_s_do_all_the_drugs.mp3"
  },
  {
    "text": "List of supplies",
    "character": "",
    "audioUrl": "audio/this-is-the-end/021_list_of_supplies.mp3"
  },
  {
    "text": "Lol, That's Why Y'all is",
    "character": "",
    "audioUrl": "audio/this-is-the-end/022_lol_that_s_why_y_all_is.mp3"
  },
  {
    "text": "Milky Way",
    "character": "",
    "audioUrl": "audio/this-is-the-end/023_milky_way.mp3"
  },
  {
    "text": "Oh my God, you guys are alive. You're actually alive, thank God.",
    "character": "",
    "audioUrl": "audio/this-is-the-end/024_oh_my_god_you_guys_are_alive_you_re_actually_alive_thank_god.mp3"
  },
  {
    "text": "Please get the fuck out of here. Well. Fuck you, Kevin.",
    "character": "",
    "audioUrl": "audio/this-is-the-end/025_please_get_the_fuck_out_of_here_well_fuck_you_kevin.mp3"
  },
  {
    "text": "Pow! Pow!",
    "character": "",
    "audioUrl": "audio/this-is-the-end/026_pow_pow.mp3"
  },
  {
    "text": "Say cheese baby",
    "character": "",
    "audioUrl": "audio/this-is-the-end/027_say_cheese_baby.mp3"
  },
  {
    "text": "Sick Reference Bro",
    "character": "",
    "audioUrl": "audio/this-is-the-end/028_sick_reference_bro.mp3"
  },
  {
    "text": "Sink Hole de Mayo",
    "character": "",
    "audioUrl": "audio/this-is-the-end/029_sink_hole_de_mayo.mp3"
  },
  {
    "text": "Something not that chill happened last night",
    "character": "",
    "audioUrl": "audio/this-is-the-end/030_something_not_that_chill_happened_last_night.mp3"
  },
  {
    "text": "Take yo panties off",
    "character": "",
    "audioUrl": "audio/this-is-the-end/031_take_yo_panties_off.mp3"
  },
  {
    "text": "That Fuckers Gotta Go",
    "character": "",
    "audioUrl": "audio/this-is-the-end/032_that_fuckers_gotta_go.mp3"
  },
  {
    "text": "That's what I thought, nerd!",
    "character": "",
    "audioUrl": "audio/this-is-the-end/033_that_s_what_i_thought_nerd.mp3"
  },
  {
    "text": "Weed is Tight",
    "character": "",
    "audioUrl": "audio/this-is-the-end/035_weed_is_tight.mp3"
  },
  {
    "text": "Who did this? Who did this?",
    "character": "",
    "audioUrl": "audio/this-is-the-end/036_who_did_this_who_did_this.mp3"
  },
  {
    "text": "Who took my phone?",
    "character": "",
    "audioUrl": "audio/this-is-the-end/037_who_took_my_phone.mp3"
  },
  {
    "text": "Who wants a sip?",
    "character": "",
    "audioUrl": "audio/this-is-the-end/038_who_wants_a_sip.mp3"
  },
  {
    "text": "You can't just leave him out there and die. Are you crazy?",
    "character": "",
    "audioUrl": "audio/this-is-the-end/039_you_can_t_just_leave_him_out_there_and_die_are_you_crazy.mp3"
  },
  {
    "text": "You're fucking stupid. Cut out from Spiderman 3.",
    "character": "",
    "audioUrl": "audio/this-is-the-end/040_you_re_fucking_stupid_cut_out_from_spiderman_3.mp3"
  },
  {
    "text": "You're the Art",
    "character": "",
    "audioUrl": "audio/this-is-the-end/041_you_re_the_art.mp3"
  }
];
