// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "A lame attempt at humor",
    "character": "",
    "audioUrl": "audio/the-office/001_a_lame_attempt_at_humor.mp3"
  },
  {
    "text": "Accidental Office",
    "character": "",
    "audioUrl": "audio/the-office/002_accidental_office.mp3"
  },
  {
    "text": "Ahhhh! I’m going to kill myself and it’s your fault",
    "character": "",
    "audioUrl": "audio/the-office/003_ahhhh_i_m_going_to_kill_myself_and_it_s_your_fault.mp3"
  },
  {
    "text": "Am I a hero?",
    "character": "",
    "audioUrl": "audio/the-office/005_am_i_a_hero.mp3"
  },
  {
    "text": "Andy Bernard",
    "character": "",
    "audioUrl": "audio/the-office/008_andy_bernard.mp3"
  },
  {
    "text": "Andy Bernard punches wall",
    "character": "",
    "audioUrl": "audio/the-office/011_andy_bernard_punches_wall.mp3"
  },
  {
    "text": "Andy punches a wall",
    "character": "",
    "audioUrl": "audio/the-office/012_andy_punches_a_wall.mp3"
  },
  {
    "text": "Andy the funny guy",
    "character": "",
    "audioUrl": "audio/the-office/013_andy_the_funny_guy.mp3"
  },
  {
    "text": "Andy's Ringtone",
    "character": "",
    "audioUrl": "audio/the-office/014_andy_s_ringtone.mp3"
  },
  {
    "text": "Are you even certified?",
    "character": "",
    "audioUrl": "audio/the-office/015_are_you_even_certified.mp3"
  },
  {
    "text": "Babies I don't care about",
    "character": "",
    "audioUrl": "audio/the-office/017_babies_i_don_t_care_about.mp3"
  },
  {
    "text": "Bears, beets, Battlestar Galactica",
    "character": "",
    "audioUrl": "audio/the-office/019_bears_beets_battlestar_galactica.mp3"
  },
  {
    "text": "Bell of the ball",
    "character": "",
    "audioUrl": "audio/the-office/020_bell_of_the_ball.mp3"
  },
  {
    "text": "Birthday Surprise",
    "character": "",
    "audioUrl": "audio/the-office/021_birthday_surprise.mp3"
  },
  {
    "text": "Boboddy Acronym",
    "character": "",
    "audioUrl": "audio/the-office/023_boboddy_acronym.mp3"
  },
  {
    "text": "Bros before hoes",
    "character": "",
    "audioUrl": "audio/the-office/025_bros_before_hoes.mp3"
  },
  {
    "text": "Buttlicker",
    "character": "",
    "audioUrl": "audio/the-office/027_buttlicker.mp3"
  },
  {
    "text": "Cafe Disco",
    "character": "",
    "audioUrl": "audio/the-office/028_cafe_disco.mp3"
  },
  {
    "text": "Cancel Christmas",
    "character": "",
    "audioUrl": "audio/the-office/029_cancel_christmas.mp3"
  },
  {
    "text": "Casual Friday",
    "character": "",
    "audioUrl": "audio/the-office/030_casual_friday.mp3"
  },
  {
    "text": "Champagne celebration",
    "character": "",
    "audioUrl": "audio/the-office/032_champagne_celebration.mp3"
  },
  {
    "text": "Changes in martial arts",
    "character": "",
    "audioUrl": "audio/the-office/033_changes_in_martial_arts.mp3"
  },
  {
    "text": "Christmas prank on dwight",
    "character": "",
    "audioUrl": "audio/the-office/034_christmas_prank_on_dwight.mp3"
  },
  {
    "text": "Classic Dawhg",
    "character": "",
    "audioUrl": "audio/the-office/036_classic_dawhg.mp3"
  },
  {
    "text": "Could be one month, could be two months..",
    "character": "",
    "audioUrl": "audio/the-office/037_could_be_one_month_could_be_two_months.mp3"
  },
  {
    "text": "Creed plays hooky",
    "character": "",
    "audioUrl": "audio/the-office/040_creed_plays_hooky.mp3"
  },
  {
    "text": "Crunch those numbers",
    "character": "",
    "audioUrl": "audio/the-office/041_crunch_those_numbers.mp3"
  },
  {
    "text": "Crying and clapping",
    "character": "",
    "audioUrl": "audio/the-office/042_crying_and_clapping.mp3"
  },
  {
    "text": "Dance Party",
    "character": "",
    "audioUrl": "audio/the-office/043_dance_party.mp3"
  },
  {
    "text": "Darryl Kelly breakup",
    "character": "",
    "audioUrl": "audio/the-office/044_darryl_kelly_breakup.mp3"
  },
  {
    "text": "Depression?",
    "character": "",
    "audioUrl": "audio/the-office/045_depression.mp3"
  },
  {
    "text": "Did I stutter?",
    "character": "",
    "audioUrl": "audio/the-office/047_did_i_stutter.mp3"
  },
  {
    "text": "Did you hear that Michael?",
    "character": "",
    "audioUrl": "audio/the-office/048_did_you_hear_that_michael.mp3"
  },
  {
    "text": "Difference in our sizes",
    "character": "",
    "audioUrl": "audio/the-office/049_difference_in_our_sizes.mp3"
  },
  {
    "text": "Do I need to be liked?",
    "character": "",
    "audioUrl": "audio/the-office/051_do_i_need_to_be_liked.mp3"
  },
  {
    "text": "Doing alcohol",
    "character": "",
    "audioUrl": "audio/the-office/052_doing_alcohol.mp3"
  },
  {
    "text": "Don't thank me",
    "character": "",
    "audioUrl": "audio/the-office/053_don_t_thank_me.mp3"
  },
  {
    "text": "Drop a deuce",
    "character": "",
    "audioUrl": "audio/the-office/055_drop_a_deuce.mp3"
  },
  {
    "text": "Dundies Nominations",
    "character": "",
    "audioUrl": "audio/the-office/056_dundies_nominations.mp3"
  },
  {
    "text": "Dwight and Michael howling",
    "character": "",
    "audioUrl": "audio/the-office/057_dwight_and_michael_howling.mp3"
  },
  {
    "text": "Dwight CD intro",
    "character": "",
    "audioUrl": "audio/the-office/058_dwight_cd_intro.mp3"
  },
  {
    "text": "Dwight Horses",
    "character": "",
    "audioUrl": "audio/the-office/059_dwight_horses.mp3"
  },
  {
    "text": "Dwight idiot V2",
    "character": "",
    "audioUrl": "audio/the-office/061_dwight_idiot_v2.mp3"
  },
  {
    "text": "Dwight punches Michael",
    "character": "",
    "audioUrl": "audio/the-office/062_dwight_punches_michael.mp3"
  },
  {
    "text": "Dwight spills coffee on himself",
    "character": "",
    "audioUrl": "audio/the-office/063_dwight_spills_coffee_on_himself.mp3"
  },
  {
    "text": "Dwight tranquilizes Stanley",
    "character": "",
    "audioUrl": "audio/the-office/064_dwight_tranquilizes_stanley.mp3"
  },
  {
    "text": "Dwight yelling",
    "character": "",
    "audioUrl": "audio/the-office/065_dwight_yelling.mp3"
  },
  {
    "text": "Dwight's Promotion",
    "character": "",
    "audioUrl": "audio/the-office/066_dwight_s_promotion.mp3"
  },
  {
    "text": "Dwight's Speech",
    "character": "",
    "audioUrl": "audio/the-office/067_dwight_s_speech.mp3"
  },
  {
    "text": "Enablers",
    "character": "",
    "audioUrl": "audio/the-office/068_enablers.mp3"
  },
  {
    "text": "Even for the Internet it’s pretty shocking",
    "character": "",
    "audioUrl": "audio/the-office/069_even_for_the_internet_it_s_pretty_shocking.mp3"
  },
  {
    "text": "Ever banged an entire bachelorette party, baby?",
    "character": "",
    "audioUrl": "audio/the-office/070_ever_banged_an_entire_bachelorette_party_baby.mp3"
  },
  {
    "text": "Everybody dance now",
    "character": "",
    "audioUrl": "audio/the-office/071_everybody_dance_now.mp3"
  },
  {
    "text": "Everybody hurts Dwight",
    "character": "",
    "audioUrl": "audio/the-office/072_everybody_hurts_dwight.mp3"
  },
  {
    "text": "Everyone I work with is an idiot",
    "character": "",
    "audioUrl": "audio/the-office/073_everyone_i_work_with_is_an_idiot.mp3"
  },
  {
    "text": "Explain what you think that is",
    "character": "",
    "audioUrl": "audio/the-office/074_explain_what_you_think_that_is.mp3"
  },
  {
    "text": "Fail",
    "character": "",
    "audioUrl": "audio/the-office/075_fail.mp3"
  },
  {
    "text": "Favorite Flavor",
    "character": "",
    "audioUrl": "audio/the-office/077_favorite_flavor.mp3"
  },
  {
    "text": "Feared or loved?",
    "character": "",
    "audioUrl": "audio/the-office/078_feared_or_loved.mp3"
  },
  {
    "text": "Feelin hot hot hot",
    "character": "",
    "audioUrl": "audio/the-office/079_feelin_hot_hot_hot.mp3"
  },
  {
    "text": "Finger gun standoff",
    "character": "",
    "audioUrl": "audio/the-office/080_finger_gun_standoff.mp3"
  },
  {
    "text": "Fire Drill the office",
    "character": "",
    "audioUrl": "audio/the-office/082_fire_drill_the_office.mp3"
  },
  {
    "text": "Fool me once, strike one",
    "character": "",
    "audioUrl": "audio/the-office/084_fool_me_once_strike_one.mp3"
  },
  {
    "text": "Game On",
    "character": "",
    "audioUrl": "audio/the-office/085_game_on.mp3"
  },
  {
    "text": "Good for $5 at Dunkin’ Donuts",
    "character": "",
    "audioUrl": "audio/the-office/086_good_for_5_at_dunkin_donuts.mp3"
  },
  {
    "text": "Good Ideas",
    "character": "",
    "audioUrl": "audio/the-office/087_good_ideas.mp3"
  },
  {
    "text": "Good News",
    "character": "",
    "audioUrl": "audio/the-office/088_good_news.mp3"
  },
  {
    "text": "Goodbye Michael",
    "character": "",
    "audioUrl": "audio/the-office/089_goodbye_michael.mp3"
  },
  {
    "text": "Goodbye my lover",
    "character": "",
    "audioUrl": "audio/the-office/090_goodbye_my_lover.mp3"
  },
  {
    "text": "Goodbye Toby!",
    "character": "",
    "audioUrl": "audio/the-office/091_goodbye_toby.mp3"
  },
  {
    "text": "Goodbyes are a bitch",
    "character": "",
    "audioUrl": "audio/the-office/092_goodbyes_are_a_bitch.mp3"
  },
  {
    "text": "Hand desanitizer stations",
    "character": "",
    "audioUrl": "audio/the-office/093_hand_desanitizer_stations.mp3"
  },
  {
    "text": "Hanging brain",
    "character": "",
    "audioUrl": "audio/the-office/094_hanging_brain.mp3"
  },
  {
    "text": "Happy birthday to you!",
    "character": "",
    "audioUrl": "audio/the-office/095_happy_birthday_to_you.mp3"
  },
  {
    "text": "Hardcore Parkour",
    "character": "",
    "audioUrl": "audio/the-office/098_hardcore_parkour.mp3"
  },
  {
    "text": "Hates Blackberry",
    "character": "",
    "audioUrl": "audio/the-office/099_hates_blackberry.mp3"
  },
  {
    "text": "He's got potential",
    "character": "",
    "audioUrl": "audio/the-office/101_he_s_got_potential.mp3"
  },
  {
    "text": "He's totally gay",
    "character": "",
    "audioUrl": "audio/the-office/102_he_s_totally_gay.mp3"
  },
  {
    "text": "Headache preparation",
    "character": "",
    "audioUrl": "audio/the-office/103_headache_preparation.mp3"
  },
  {
    "text": "Hello Mother",
    "character": "",
    "audioUrl": "audio/the-office/104_hello_mother.mp3"
  },
  {
    "text": "Here's to good friends",
    "character": "",
    "audioUrl": "audio/the-office/105_here_s_to_good_friends.mp3"
  },
  {
    "text": "Hey, hey, hey, you idiot",
    "character": "",
    "audioUrl": "audio/the-office/106_hey_hey_hey_you_idiot.mp3"
  },
  {
    "text": "Hired Guy",
    "character": "",
    "audioUrl": "audio/the-office/107_hired_guy.mp3"
  },
  {
    "text": "How the turn tables",
    "character": "",
    "audioUrl": "audio/the-office/111_how_the_turn_tables.mp3"
  },
  {
    "text": "Hug it out, bitch",
    "character": "",
    "audioUrl": "audio/the-office/112_hug_it_out_bitch.mp3"
  },
  {
    "text": "Hygiene Day",
    "character": "",
    "audioUrl": "audio/the-office/113_hygiene_day.mp3"
  },
  {
    "text": "I already won the lottery",
    "character": "",
    "audioUrl": "audio/the-office/114_i_already_won_the_lottery.mp3"
  },
  {
    "text": "I am really proud of you",
    "character": "",
    "audioUrl": "audio/the-office/117_i_am_really_proud_of_you.mp3"
  },
  {
    "text": "I can take you out",
    "character": "",
    "audioUrl": "audio/the-office/118_i_brought_you_into_this_world_and_i_can_take_you_out.mp3"
  },
  {
    "text": "I can't do this forever",
    "character": "",
    "audioUrl": "audio/the-office/119_i_can_t_do_this_forever.mp3"
  },
  {
    "text": "I declare bankruptcy!",
    "character": "",
    "audioUrl": "audio/the-office/121_i_declare_bankruptcy.mp3"
  },
  {
    "text": "When people don't believe in me",
    "character": "",
    "audioUrl": "audio/the-office/122_i_do_my_best_work_when_people_don_t_believe_in_me.mp3"
  },
  {
    "text": "I don't wanna work",
    "character": "",
    "audioUrl": "audio/the-office/124_i_don_t_wanna_work.mp3"
  },
  {
    "text": "I don't wanna work",
    "character": "",
    "audioUrl": "audio/the-office/125_i_don_t_wanna_work.mp3"
  },
  {
    "text": "I feel so bad for Angela",
    "character": "",
    "audioUrl": "audio/the-office/128_i_feel_so_bad_for_angela.mp3"
  },
  {
    "text": "I forbid anybody to freak out",
    "character": "",
    "audioUrl": "audio/the-office/129_i_forbid_anybody_to_freak_out.mp3"
  },
  {
    "text": "I had no idea",
    "character": "",
    "audioUrl": "audio/the-office/131_i_had_no_idea.mp3"
  },
  {
    "text": "The things you choose to be",
    "character": "",
    "audioUrl": "audio/the-office/132_i_hate_so_much_about_the_things_you_choose_to_be.mp3"
  },
  {
    "text": "I heard a joke today",
    "character": "",
    "audioUrl": "audio/the-office/133_i_heard_a_joke_today.mp3"
  },
  {
    "text": "I know about Angela",
    "character": "",
    "audioUrl": "audio/the-office/135_i_know_about_angela.mp3"
  },
  {
    "text": "I like pretzel day",
    "character": "",
    "audioUrl": "audio/the-office/137_i_like_pretzel_day.mp3"
  },
  {
    "text": "I never smile",
    "character": "",
    "audioUrl": "audio/the-office/139_i_never_smile.mp3"
  },
  {
    "text": "I respond to strong leadership",
    "character": "",
    "audioUrl": "audio/the-office/140_i_respond_to_strong_leadership.mp3"
  },
  {
    "text": "I send it back",
    "character": "",
    "audioUrl": "audio/the-office/141_i_send_it_back.mp3"
  },
  {
    "text": "I should kick your f***ing ass",
    "character": "",
    "audioUrl": "audio/the-office/142_i_should_kick_your_f_ing_ass.mp3"
  },
  {
    "text": "I state my regret",
    "character": "",
    "audioUrl": "audio/the-office/143_i_state_my_regret.mp3"
  },
  {
    "text": "I state my regret",
    "character": "",
    "audioUrl": "audio/the-office/144_i_state_my_regret.mp3"
  },
  {
    "text": "I thought we had the same birthday",
    "character": "",
    "audioUrl": "audio/the-office/145_i_thought_we_had_the_same_birthday.mp3"
  },
  {
    "text": "I told you so",
    "character": "",
    "audioUrl": "audio/the-office/146_i_told_you_so.mp3"
  },
  {
    "text": "Ketchup fights and tickling",
    "character": "",
    "audioUrl": "audio/the-office/147_i_want_the_ketchup_fights_and_the_tickling_and_the_giggling.mp3"
  },
  {
    "text": "Ass out of my face",
    "character": "",
    "audioUrl": "audio/the-office/148_i_want_you_to_get_your_ass_out_of_my_face.mp3"
  },
  {
    "text": "I would shoot Toby twice",
    "character": "",
    "audioUrl": "audio/the-office/149_i_would_shoot_toby_twice.mp3"
  },
  {
    "text": "I'll catch you on the flippity flip",
    "character": "",
    "audioUrl": "audio/the-office/150_i_ll_catch_you_on_the_flippity_flip.mp3"
  },
  {
    "text": "I'm Awesome",
    "character": "",
    "audioUrl": "audio/the-office/152_i_m_awesome.mp3"
  },
  {
    "text": "I'm going wherever they value loyalty the most",
    "character": "",
    "audioUrl": "audio/the-office/153_i_m_going_wherever_they_value_loyalty_the_most.mp3"
  },
  {
    "text": "I'm gonna kill myself",
    "character": "",
    "audioUrl": "audio/the-office/154_i_m_gonna_kill_myself.mp3"
  },
  {
    "text": "I'm not superstitious, but I am a little stitious",
    "character": "",
    "audioUrl": "audio/the-office/157_i_m_not_superstitious_but_i_am_a_little_stitious.mp3"
  },
  {
    "text": "I'm not your father",
    "character": "",
    "audioUrl": "audio/the-office/158_i_m_not_your_father.mp3"
  },
  {
    "text": "Ideal party",
    "character": "",
    "audioUrl": "audio/the-office/161_ideal_party.mp3"
  },
  {
    "text": "Identity Theft",
    "character": "",
    "audioUrl": "audio/the-office/162_identity_theft.mp3"
  },
  {
    "text": "Identity theft is not a joke",
    "character": "",
    "audioUrl": "audio/the-office/163_identity_theft_is_not_a_joke.mp3"
  },
  {
    "text": "Idiot quote Dwight Schrute",
    "character": "",
    "audioUrl": "audio/the-office/164_idiot_quote_dwight_schrute.mp3"
  },
  {
    "text": "If onlys and justs were candies and nuts..",
    "character": "",
    "audioUrl": "audio/the-office/165_if_onlys_and_justs_were_candies_and_nuts.mp3"
  },
  {
    "text": "10,000 to 1, you take it",
    "character": "",
    "audioUrl": "audio/the-office/166_if_someone_gives_you_10_000_to_1_on_anything_you_take_it.mp3"
  },
  {
    "text": "If that’s flashing then lock me up",
    "character": "",
    "audioUrl": "audio/the-office/167_if_that_s_flashing_then_lock_me_up.mp3"
  },
  {
    "text": "It was inadvertent",
    "character": "",
    "audioUrl": "audio/the-office/168_if_we_did_something_to_upset_you_i_m_sure_it_was_inadvertent.mp3"
  },
  {
    "text": "I'm fine b***h",
    "character": "",
    "audioUrl": "audio/the-office/169_im_fine_b_h.mp3"
  },
  {
    "text": "In sales, ABC means..",
    "character": "",
    "audioUrl": "audio/the-office/170_in_sales_abc_means.mp3"
  },
  {
    "text": "Interrogating Oscar",
    "character": "",
    "audioUrl": "audio/the-office/171_interrogating_oscar.mp3"
  },
  {
    "text": "Irish Christmas",
    "character": "",
    "audioUrl": "audio/the-office/172_irish_christmas.mp3"
  },
  {
    "text": "It has been exquisite",
    "character": "",
    "audioUrl": "audio/the-office/173_it_has_been_exquisite.mp3"
  },
  {
    "text": "It is smells like throw up in here",
    "character": "",
    "audioUrl": "audio/the-office/174_it_is_smells_like_throw_up_in_here.mp3"
  },
  {
    "text": "It is your birthday",
    "character": "",
    "audioUrl": "audio/the-office/175_it_is_your_birthday.mp3"
  },
  {
    "text": "It's about to get all stupid up in here",
    "character": "",
    "audioUrl": "audio/the-office/177_it_s_about_to_get_all_stupid_up_in_here.mp3"
  },
  {
    "text": "It's happening!",
    "character": "",
    "audioUrl": "audio/the-office/179_it_s_happening.mp3"
  },
  {
    "text": "It’s Britney bitch",
    "character": "",
    "audioUrl": "audio/the-office/181_it_s_britney_bitch.mp3"
  },
  {
    "text": "Jan throws Dundee",
    "character": "",
    "audioUrl": "audio/the-office/183_jan_throws_dundee.mp3"
  },
  {
    "text": "Jessica did you just fart?",
    "character": "",
    "audioUrl": "audio/the-office/184_jessica_did_you_just_fart.mp3"
  },
  {
    "text": "Jim & Michael",
    "character": "",
    "audioUrl": "audio/the-office/185_jim_michael.mp3"
  },
  {
    "text": "Jim's Snowball",
    "character": "",
    "audioUrl": "audio/the-office/187_jim_s_snowball.mp3"
  },
  {
    "text": "Just made the list",
    "character": "",
    "audioUrl": "audio/the-office/188_just_made_the_list.mp3"
  },
  {
    "text": "Just Poopin",
    "character": "",
    "audioUrl": "audio/the-office/189_just_poopin.mp3"
  },
  {
    "text": "Just stop you’re going to drive me crazy",
    "character": "",
    "audioUrl": "audio/the-office/190_just_stop_you_re_going_to_drive_me_crazy.mp3"
  },
  {
    "text": "Keeping a list",
    "character": "",
    "audioUrl": "audio/the-office/191_keeping_a_list.mp3"
  },
  {
    "text": "Kelly loves Ryan",
    "character": "",
    "audioUrl": "audio/the-office/192_kelly_loves_ryan.mp3"
  },
  {
    "text": "Kevin",
    "character": "",
    "audioUrl": "audio/the-office/193_kevin.mp3"
  },
  {
    "text": "Kinda weirding me out",
    "character": "",
    "audioUrl": "audio/the-office/194_kinda_weirding_me_out.mp3"
  },
  {
    "text": "Lemon Head",
    "character": "",
    "audioUrl": "audio/the-office/195_lemon_head.mp3"
  },
  {
    "text": "Let's all start clapping",
    "character": "",
    "audioUrl": "audio/the-office/196_let_s_all_start_clapping.mp3"
  },
  {
    "text": "Let's assess the situation",
    "character": "",
    "audioUrl": "audio/the-office/197_let_s_assess_the_situation.mp3"
  },
  {
    "text": "Let's Party",
    "character": "",
    "audioUrl": "audio/the-office/198_let_s_party.mp3"
  },
  {
    "text": "Magic magic magic magic magic",
    "character": "",
    "audioUrl": "audio/the-office/200_magic_magic_magic_magic_magic.mp3"
  },
  {
    "text": "Meredith drinks a lot",
    "character": "",
    "audioUrl": "audio/the-office/201_meredith_drinks_a_lot.mp3"
  },
  {
    "text": "Michael dance off",
    "character": "",
    "audioUrl": "audio/the-office/202_michael_dance_off.mp3"
  },
  {
    "text": "Michael Scott drives into a lake",
    "character": "",
    "audioUrl": "audio/the-office/205_michael_scott_drives_into_a_lake.mp3"
  },
  {
    "text": "Michael Scott happy birthday",
    "character": "",
    "audioUrl": "audio/the-office/206_michael_scott_happy_birthday.mp3"
  },
  {
    "text": "Michael Scott in Victoria’s Secret",
    "character": "",
    "audioUrl": "audio/the-office/207_michael_scott_in_victoria_s_secret.mp3"
  },
  {
    "text": "Michael Scott's toast",
    "character": "",
    "audioUrl": "audio/the-office/208_michael_scott_s_toast.mp3"
  },
  {
    "text": "Michael Scott's toast part II",
    "character": "",
    "audioUrl": "audio/the-office/209_michael_scott_s_toast_part_ii.mp3"
  },
  {
    "text": "Michael's colonoscopy",
    "character": "",
    "audioUrl": "audio/the-office/212_michael_s_colonoscopy.mp3"
  },
  {
    "text": "Monkey see, monkey do..",
    "character": "",
    "audioUrl": "audio/the-office/213_monkey_see_monkey_do.mp3"
  },
  {
    "text": "Motel Art",
    "character": "",
    "audioUrl": "audio/the-office/214_motel_art.mp3"
  },
  {
    "text": "My heart soars",
    "character": "",
    "audioUrl": "audio/the-office/216_my_heart_soars.mp3"
  },
  {
    "text": "My horn can pierce the sky",
    "character": "",
    "audioUrl": "audio/the-office/217_my_horn_can_pierce_the_sky.mp3"
  },
  {
    "text": "My Humps Micheal",
    "character": "",
    "audioUrl": "audio/the-office/218_my_humps_micheal.mp3"
  },
  {
    "text": "Narc",
    "character": "",
    "audioUrl": "audio/the-office/220_narc.mp3"
  },
  {
    "text": "No",
    "character": "",
    "audioUrl": "audio/the-office/222_no.mp3"
  },
  {
    "text": "No Billy Michael Sc",
    "character": "",
    "audioUrl": "audio/the-office/223_no_billy_michael_sc.mp3"
  },
  {
    "text": "No God no God please no no no nooooooo",
    "character": "",
    "audioUrl": "audio/the-office/225_no_god_no_god_please_no_no_no_nooooooo.mp3"
  },
  {
    "text": "No god please",
    "character": "",
    "audioUrl": "audio/the-office/226_no_god_please.mp3"
  },
  {
    "text": "No God please no",
    "character": "",
    "audioUrl": "audio/the-office/227_no_god_please_no.mp3"
  },
  {
    "text": "No God please no noo",
    "character": "",
    "audioUrl": "audio/the-office/228_no_god_please_no_noo.mp3"
  },
  {
    "text": "No god please no the office",
    "character": "",
    "audioUrl": "audio/the-office/229_no_god_please_no_the_office.mp3"
  },
  {
    "text": "No I don’t want to do any of that",
    "character": "",
    "audioUrl": "audio/the-office/230_no_i_don_t_want_to_do_any_of_that.mp3"
  },
  {
    "text": "No! God! No God please no",
    "character": "",
    "audioUrl": "audio/the-office/231_no_god_no_god_please_no.mp3"
  },
  {
    "text": "Nobody cares",
    "character": "",
    "audioUrl": "audio/the-office/232_nobody_cares.mp3"
  },
  {
    "text": "Nooo the office",
    "character": "",
    "audioUrl": "audio/the-office/233_nooo_the_office.mp3"
  },
  {
    "text": "Dancer",
    "character": "",
    "audioUrl": "audio/the-office/234_office_dancer.mp3"
  },
  {
    "text": "Parkour",
    "character": "",
    "audioUrl": "audio/the-office/235_office_parkour.mp3"
  },
  {
    "text": "Why are you the way",
    "character": "",
    "audioUrl": "audio/the-office/237_office_why_are_you_the_way.mp3"
  },
  {
    "text": "Ogodno",
    "character": "",
    "audioUrl": "audio/the-office/238_ogodno.mp3"
  },
  {
    "text": "Oh my god",
    "character": "",
    "audioUrl": "audio/the-office/242_oh_my_god.mp3"
  },
  {
    "text": "Oh my god!",
    "character": "",
    "audioUrl": "audio/the-office/243_oh_my_god.mp3"
  },
  {
    "text": "Oscar",
    "character": "",
    "audioUrl": "audio/the-office/248_oscar.mp3"
  },
  {
    "text": "Our balls are in your court",
    "character": "",
    "audioUrl": "audio/the-office/249_our_balls_are_in_your_court.mp3"
  },
  {
    "text": "Our prices have never been lower",
    "character": "",
    "audioUrl": "audio/the-office/250_our_prices_have_never_been_lower.mp3"
  },
  {
    "text": "Pam helping Dwight",
    "character": "",
    "audioUrl": "audio/the-office/252_pam_helping_dwight.mp3"
  },
  {
    "text": "Parkour parkour!",
    "character": "",
    "audioUrl": "audio/the-office/255_parkour_parkour.mp3"
  },
  {
    "text": "Pee Corner",
    "character": "",
    "audioUrl": "audio/the-office/256_pee_corner.mp3"
  },
  {
    "text": "People have been filtering in and out",
    "character": "",
    "audioUrl": "audio/the-office/257_people_have_been_filtering_in_and_out.mp3"
  },
  {
    "text": "People have been filtering in and out",
    "character": "",
    "audioUrl": "audio/the-office/258_people_have_been_filtering_in_and_out.mp3"
  },
  {
    "text": "Please no",
    "character": "",
    "audioUrl": "audio/the-office/259_please_no.mp3"
  },
  {
    "text": "Pranking Dwight",
    "character": "",
    "audioUrl": "audio/the-office/260_pranking_dwight.mp3"
  },
  {
    "text": "Prison Mike",
    "character": "",
    "audioUrl": "audio/the-office/261_prison_mike.mp3"
  },
  {
    "text": "Punctuality",
    "character": "",
    "audioUrl": "audio/the-office/262_punctuality.mp3"
  },
  {
    "text": "Punish",
    "character": "",
    "audioUrl": "audio/the-office/263_punish.mp3"
  },
  {
    "text": "Pyramid Scheme",
    "character": "",
    "audioUrl": "audio/the-office/264_pyramid_scheme.mp3"
  },
  {
    "text": "Raise your hand if you want to get rich",
    "character": "",
    "audioUrl": "audio/the-office/265_raise_your_hand_if_you_want_to_get_rich.mp3"
  },
  {
    "text": "Reaching Michael Scott",
    "character": "",
    "audioUrl": "audio/the-office/266_reaching_michael_scott.mp3"
  },
  {
    "text": "Remember to call",
    "character": "",
    "audioUrl": "audio/the-office/267_remember_to_call.mp3"
  },
  {
    "text": "Report",
    "character": "",
    "audioUrl": "audio/the-office/268_report.mp3"
  },
  {
    "text": "Russian Roulette",
    "character": "",
    "audioUrl": "audio/the-office/270_russian_roulette.mp3"
  },
  {
    "text": "Ryan and Kelly",
    "character": "",
    "audioUrl": "audio/the-office/271_ryan_and_kelly.mp3"
  },
  {
    "text": "Ryan does pushups",
    "character": "",
    "audioUrl": "audio/the-office/272_ryan_does_pushups.mp3"
  },
  {
    "text": "Ryan is being a little bitch again",
    "character": "",
    "audioUrl": "audio/the-office/273_ryan_is_being_a_little_bitch_again.mp3"
  },
  {
    "text": "Saboteur",
    "character": "",
    "audioUrl": "audio/the-office/275_saboteur.mp3"
  },
  {
    "text": "Savannah Standoff",
    "character": "",
    "audioUrl": "audio/the-office/276_savannah_standoff.mp3"
  },
  {
    "text": "Saying fewer words",
    "character": "",
    "audioUrl": "audio/the-office/277_saying_fewer_words.mp3"
  },
  {
    "text": "Schrute Farms bed and breakfast",
    "character": "",
    "audioUrl": "audio/the-office/278_schrute_farms_bed_and_breakfast.mp3"
  },
  {
    "text": "Screen Calls",
    "character": "",
    "audioUrl": "audio/the-office/279_screen_calls.mp3"
  },
  {
    "text": "Sex Doll",
    "character": "",
    "audioUrl": "audio/the-office/280_sex_doll.mp3"
  },
  {
    "text": "Sex Doll",
    "character": "",
    "audioUrl": "audio/the-office/281_sex_doll.mp3"
  },
  {
    "text": "She is prettier than you though",
    "character": "",
    "audioUrl": "audio/the-office/282_she_is_prettier_than_you_though.mp3"
  },
  {
    "text": "She’ll Do",
    "character": "",
    "audioUrl": "audio/the-office/283_she_ll_do.mp3"
  },
  {
    "text": "Shut up about the sun",
    "character": "",
    "audioUrl": "audio/the-office/284_shut_up_about_the_sun.mp3"
  },
  {
    "text": "Smiling through the blinds",
    "character": "",
    "audioUrl": "audio/the-office/286_smiling_through_the_blinds.mp3"
  },
  {
    "text": "So suck on that",
    "character": "",
    "audioUrl": "audio/the-office/287_so_suck_on_that.mp3"
  },
  {
    "text": "Sometimes I'll start a sentence..",
    "character": "",
    "audioUrl": "audio/the-office/289_sometimes_i_ll_start_a_sentence.mp3"
  },
  {
    "text": "Sorry I annoyed you with my friendship",
    "character": "",
    "audioUrl": "audio/the-office/291_sorry_i_annoyed_you_with_my_friendship.mp3"
  },
  {
    "text": "Sprinkles",
    "character": "",
    "audioUrl": "audio/the-office/292_sprinkles.mp3"
  },
  {
    "text": "Stanley",
    "character": "",
    "audioUrl": "audio/the-office/293_stanley.mp3"
  },
  {
    "text": "Stanley Hudson jury duty",
    "character": "",
    "audioUrl": "audio/the-office/294_stanley_hudson_jury_duty.mp3"
  },
  {
    "text": "Stanley Hudson not pleased",
    "character": "",
    "audioUrl": "audio/the-office/295_stanley_hudson_not_pleased.mp3"
  },
  {
    "text": "Stanley laughing",
    "character": "",
    "audioUrl": "audio/the-office/296_stanley_laughing.mp3"
  },
  {
    "text": "Stanley yelled at me today",
    "character": "",
    "audioUrl": "audio/the-office/297_stanley_yelled_at_me_today.mp3"
  },
  {
    "text": "Stanley's view on jury duty",
    "character": "",
    "audioUrl": "audio/the-office/298_stanley_s_view_on_jury_duty.mp3"
  },
  {
    "text": "Stay Calm",
    "character": "",
    "audioUrl": "audio/the-office/299_stay_calm.mp3"
  },
  {
    "text": "Staying alive",
    "character": "",
    "audioUrl": "audio/the-office/300_staying_alive.mp3"
  },
  {
    "text": "Strike, scream, run",
    "character": "",
    "audioUrl": "audio/the-office/301_strike_scream_run.mp3"
  },
  {
    "text": "Strike, scream, run",
    "character": "",
    "audioUrl": "audio/the-office/302_strike_scream_run.mp3"
  },
  {
    "text": "Take me home, country roads",
    "character": "",
    "audioUrl": "audio/the-office/305_take_me_home_country_roads.mp3"
  },
  {
    "text": "Thank you sir, I don't think you will regret it",
    "character": "",
    "audioUrl": "audio/the-office/307_thank_you_sir_i_don_t_think_you_will_regret_it.mp3"
  },
  {
    "text": "That was an overreaction",
    "character": "",
    "audioUrl": "audio/the-office/309_that_was_an_overreaction.mp3"
  },
  {
    "text": "That's right",
    "character": "",
    "audioUrl": "audio/the-office/310_that_s_right.mp3"
  },
  {
    "text": "That's what she said the office",
    "character": "",
    "audioUrl": "audio/the-office/311_that_s_what_she_said_the_office.mp3"
  },
  {
    "text": "That's a very rude thing to say Kevin",
    "character": "",
    "audioUrl": "audio/the-office/317_thats_a_very_rude_thing_to_say_kevin.mp3"
  },
  {
    "text": "That's what she said",
    "character": "",
    "audioUrl": "audio/the-office/319_thats_what_she_said.mp3"
  },
  {
    "text": "That's what she said",
    "character": "",
    "audioUrl": "audio/the-office/321_thats_what_she_said.mp3"
  },
  {
    "text": "The hospital will provide dictionaries",
    "character": "",
    "audioUrl": "audio/the-office/325_the_hospital_will_provide_dictionaries.mp3"
  },
  {
    "text": "The inner circle",
    "character": "",
    "audioUrl": "audio/the-office/326_the_inner_circle.mp3"
  },
  {
    "text": "The Office",
    "character": "",
    "audioUrl": "audio/the-office/328_the_office.mp3"
  },
  {
    "text": "That's what she said",
    "character": "",
    "audioUrl": "audio/the-office/329_the_office_thats_what_she_said.mp3"
  },
  {
    "text": "Aaaa I’m gonna kill my self",
    "character": "",
    "audioUrl": "audio/the-office/330_the_office_aaaa_i_m_gonna_kill_my_self.mp3"
  },
  {
    "text": "I understand nothing",
    "character": "",
    "audioUrl": "audio/the-office/332_the_office_i_understand_nothing.mp3"
  },
  {
    "text": "Identity theft is not a joke",
    "character": "",
    "audioUrl": "audio/the-office/333_the_office_identity_theft_is_not_a_joke.mp3"
  },
  {
    "text": "No God please nooo",
    "character": "",
    "audioUrl": "audio/the-office/334_the_office_no_god_please_nooo.mp3"
  },
  {
    "text": "Oh no it's bad. It's 'real' bad.",
    "character": "",
    "audioUrl": "audio/the-office/335_the_office_oh_no_its_bad_it_s_real_bad.mp3"
  },
  {
    "text": "Oh my god! Ok, it's happening!",
    "character": "",
    "audioUrl": "audio/the-office/336_the_office_omg_ok_it_s_happening.mp3"
  },
  {
    "text": "Bathroom",
    "character": "",
    "audioUrl": "audio/the-office/340_the_office_bathroom.mp3"
  },
  {
    "text": "Birthday",
    "character": "",
    "audioUrl": "audio/the-office/341_the_office_birthday.mp3"
  },
  {
    "text": "Jim",
    "character": "",
    "audioUrl": "audio/the-office/342_the_office_jim.mp3"
  },
  {
    "text": "Stay calm",
    "character": "",
    "audioUrl": "audio/the-office/343_the_office_stay_calm.mp3"
  },
  {
    "text": "Stay calm",
    "character": "",
    "audioUrl": "audio/the-office/344_the_office_stay_calm.mp3"
  },
  {
    "text": "Theme",
    "character": "",
    "audioUrl": "audio/the-office/346_the_office_theme.mp3"
  },
  {
    "text": "Theme",
    "character": "",
    "audioUrl": "audio/the-office/347_the_office_theme.mp3"
  },
  {
    "text": "Theme remix",
    "character": "",
    "audioUrl": "audio/the-office/348_the_office_theme_remix.mp3"
  },
  {
    "text": "Theme son",
    "character": "",
    "audioUrl": "audio/the-office/349_the_office_theme_son.mp3"
  },
  {
    "text": "Theme song",
    "character": "",
    "audioUrl": "audio/the-office/350_the_office_theme_song.mp3"
  },
  {
    "text": "Trap mix",
    "character": "",
    "audioUrl": "audio/the-office/351_the_office_trap_mix.mp3"
  },
  {
    "text": "Twins",
    "character": "",
    "audioUrl": "audio/the-office/352_the_office_twins.mp3"
  },
  {
    "text": "Ugly",
    "character": "",
    "audioUrl": "audio/the-office/353_the_office_ugly.mp3"
  },
  {
    "text": "UK theme",
    "character": "",
    "audioUrl": "audio/the-office/354_the_office_uk_theme.mp3"
  },
  {
    "text": "The Office: Andy's ringtone",
    "character": "",
    "audioUrl": "audio/the-office/355_the_office_andy_s_ringtone.mp3"
  },
  {
    "text": "The Password",
    "character": "",
    "audioUrl": "audio/the-office/356_the_password.mp3"
  },
  {
    "text": "The prodigal son returns",
    "character": "",
    "audioUrl": "audio/the-office/357_the_prodigal_son_returns.mp3"
  },
  {
    "text": "The Scarn",
    "character": "",
    "audioUrl": "audio/the-office/358_the_scarn.mp3"
  },
  {
    "text": "The Scarn",
    "character": "",
    "audioUrl": "audio/the-office/359_the_scarn.mp3"
  },
  {
    "text": "The Scarn dance",
    "character": "",
    "audioUrl": "audio/the-office/360_the_scarn_dance.mp3"
  },
  {
    "text": "Stress of my modern office",
    "character": "",
    "audioUrl": "audio/the-office/361_the_stress_of_my_modern_office_has_caused_me_to_go_into_depr.mp3"
  },
  {
    "text": "These are our demands",
    "character": "",
    "audioUrl": "audio/the-office/363_these_are_our_demands.mp3"
  },
  {
    "text": "Worst day of my life",
    "character": "",
    "audioUrl": "audio/the-office/364_this_has_been_the_worst_most_backwards_day_of_my_life.mp3"
  },
  {
    "text": "This is Christmas",
    "character": "",
    "audioUrl": "audio/the-office/366_this_is_christmas.mp3"
  },
  {
    "text": "This is the worst",
    "character": "",
    "audioUrl": "audio/the-office/368_this_is_the_worst.mp3"
  },
  {
    "text": "This plantation",
    "character": "",
    "audioUrl": "audio/the-office/370_this_plantation.mp3"
  },
  {
    "text": "Tickets to the gun show",
    "character": "",
    "audioUrl": "audio/the-office/371_tickets_to_the_gun_show.mp3"
  },
  {
    "text": "Time to carbo load",
    "character": "",
    "audioUrl": "audio/the-office/373_time_to_carbo_load.mp3"
  },
  {
    "text": "Try my gookie",
    "character": "",
    "audioUrl": "audio/the-office/374_try_my_gookie.mp3"
  },
  {
    "text": "Tube City",
    "character": "",
    "audioUrl": "audio/the-office/375_tube_city.mp3"
  },
  {
    "text": "Two thumbs down",
    "character": "",
    "audioUrl": "audio/the-office/376_two_thumbs_down.mp3"
  },
  {
    "text": "Ugh",
    "character": "",
    "audioUrl": "audio/the-office/377_ugh.mp3"
  },
  {
    "text": "We are screwed",
    "character": "",
    "audioUrl": "audio/the-office/379_we_are_screwed.mp3"
  },
  {
    "text": "We can no longer be friends",
    "character": "",
    "audioUrl": "audio/the-office/380_we_can_no_longer_be_friends.mp3"
  },
  {
    "text": "We could make things very difficult for you",
    "character": "",
    "audioUrl": "audio/the-office/381_we_could_make_things_very_difficult_for_you.mp3"
  },
  {
    "text": "We need to talk",
    "character": "",
    "audioUrl": "audio/the-office/384_we_need_to_talk.mp3"
  },
  {
    "text": "We're screwed (short)",
    "character": "",
    "audioUrl": "audio/the-office/388_we_re_screwed_short.mp3"
  },
  {
    "text": "Well, happy birthday Jesus..",
    "character": "",
    "audioUrl": "audio/the-office/389_well_happy_birthday_jesus.mp3"
  },
  {
    "text": "What a great boss you turned out to be",
    "character": "",
    "audioUrl": "audio/the-office/390_what_a_great_boss_you_turned_out_to_be.mp3"
  },
  {
    "text": "What is wrong with me today",
    "character": "",
    "audioUrl": "audio/the-office/393_what_is_wrong_with_me_today.mp3"
  },
  {
    "text": "What is wrong with me today?",
    "character": "",
    "audioUrl": "audio/the-office/394_what_is_wrong_with_me_today.mp3"
  },
  {
    "text": "Where are the turtles?!",
    "character": "",
    "audioUrl": "audio/the-office/399_where_are_the_turtles.mp3"
  },
  {
    "text": "Where, Dwight",
    "character": "",
    "audioUrl": "audio/the-office/400_where_dwight.mp3"
  },
  {
    "text": "Why am I so sad?",
    "character": "",
    "audioUrl": "audio/the-office/401_why_am_i_so_sad.mp3"
  },
  {
    "text": "Why are you the way you are? (long)",
    "character": "",
    "audioUrl": "audio/the-office/402_why_are_you_the_way_that_you_are_long.mp3"
  },
  {
    "text": "Why are you the way that you are?",
    "character": "",
    "audioUrl": "audio/the-office/403_why_are_you_the_way_that_you_are.mp3"
  },
  {
    "text": "Why are you the way you are?",
    "character": "",
    "audioUrl": "audio/the-office/404_why_are_you_the_way_you_are.mp3"
  },
  {
    "text": "Why waste time",
    "character": "",
    "audioUrl": "audio/the-office/405_why_waste_time.mp3"
  },
  {
    "text": "Wine dip",
    "character": "",
    "audioUrl": "audio/the-office/406_wine_dip.mp3"
  },
  {
    "text": "Women in the Workplace",
    "character": "",
    "audioUrl": "audio/the-office/407_women_in_the_workplace.mp3"
  },
  {
    "text": "Women in the Workplace",
    "character": "",
    "audioUrl": "audio/the-office/408_women_in_the_workplace.mp3"
  },
  {
    "text": "Women should dress the way that they want",
    "character": "",
    "audioUrl": "audio/the-office/409_women_should_dress_the_way_that_they_want.mp3"
  },
  {
    "text": "Ya. Okay",
    "character": "",
    "audioUrl": "audio/the-office/411_ya_okay.mp3"
  },
  {
    "text": "You encouraged it",
    "character": "",
    "audioUrl": "audio/the-office/416_you_encouraged_it.mp3"
  },
  {
    "text": "You gotta be kidding me",
    "character": "",
    "audioUrl": "audio/the-office/417_you_gotta_be_kidding_me.mp3"
  },
  {
    "text": "You have a lot to learn about this town, sweetie",
    "character": "",
    "audioUrl": "audio/the-office/419_you_have_a_lot_to_learn_about_this_town_sweetie.mp3"
  },
  {
    "text": "You know I have to do this",
    "character": "",
    "audioUrl": "audio/the-office/420_you_know_i_have_to_do_this.mp3"
  },
  {
    "text": "You owe me one",
    "character": "",
    "audioUrl": "audio/the-office/421_you_owe_me_one.mp3"
  },
  {
    "text": "You were in the parking lot earleir!",
    "character": "",
    "audioUrl": "audio/the-office/422_you_were_in_the_parking_lot_earleir.mp3"
  },
  {
    "text": "You, me, bars, beers, buzzed",
    "character": "",
    "audioUrl": "audio/the-office/423_you_me_bars_beers_buzzed.mp3"
  },
  {
    "text": "You're Ali Larter, I'm Beyonce",
    "character": "",
    "audioUrl": "audio/the-office/424_you_re_ali_larter_i_m_beyonce.mp3"
  },
  {
    "text": "You're being misogynistic",
    "character": "",
    "audioUrl": "audio/the-office/425_you_re_being_misogynistic.mp3"
  },
  {
    "text": "You're so f in smart",
    "character": "",
    "audioUrl": "audio/the-office/426_you_re_so_f_in_smart.mp3"
  },
  {
    "text": "You’re a Jerk",
    "character": "",
    "audioUrl": "audio/the-office/427_you_re_a_jerk.mp3"
  },
  {
    "text": "You’re on Facebook",
    "character": "",
    "audioUrl": "audio/the-office/428_you_re_on_facebook.mp3"
  },
  {
    "text": "Your company cannot be worth that much",
    "character": "",
    "audioUrl": "audio/the-office/429_your_company_cannot_be_worth_that_much.mp3"
  },
  {
    "text": "Yummy yummy, thank you",
    "character": "",
    "audioUrl": "audio/the-office/430_yummy_yummy_thank_you.mp3"
  }
];
