// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "After 2 AM",
    "character": "",
    "audioUrl": "audio/himym/003_after_2_am.mp3"
  },
  {
    "text": "Bang bang bangity bang",
    "character": "",
    "audioUrl": "audio/himym/006_bang_bang_bangity_bang.mp3"
  },
  {
    "text": "Barney meets his daughter",
    "character": "",
    "audioUrl": "audio/himym/007_barney_meets_his_daughter.mp3"
  },
  {
    "text": "Barney shoots himself",
    "character": "",
    "audioUrl": "audio/himym/009_barney_shoots_himself.mp3"
  },
  {
    "text": "Basketball",
    "character": "",
    "audioUrl": "audio/himym/011_basketball.mp3"
  },
  {
    "text": "Beercules",
    "character": "",
    "audioUrl": "audio/himym/012_beercules.mp3"
  },
  {
    "text": "Being friends with me is hard, I'm awesome",
    "character": "",
    "audioUrl": "audio/himym/013_being_friends_with_me_is_hard_i_m_awesome.mp3"
  },
  {
    "text": "Blackout orgasms",
    "character": "",
    "audioUrl": "audio/himym/016_blackout_orgasms.mp3"
  },
  {
    "text": "Boats boats boats",
    "character": "",
    "audioUrl": "audio/himym/017_boats_boats_boats.mp3"
  },
  {
    "text": "Calling people names is hurtful, ass face",
    "character": "",
    "audioUrl": "audio/himym/021_calling_people_names_is_hurtful_ass_face.mp3"
  },
  {
    "text": "Car alarm",
    "character": "",
    "audioUrl": "audio/himym/024_car_alarm.mp3"
  },
  {
    "text": "Come on",
    "character": "",
    "audioUrl": "audio/himym/030_come_on.mp3"
  },
  {
    "text": "Damnit Patrice, stop smothering me!",
    "character": "",
    "audioUrl": "audio/himym/031_damnit_patrice_stop_smothering_me.mp3"
  },
  {
    "text": "Dead squirrel",
    "character": "",
    "audioUrl": "audio/himym/033_dead_squirrel.mp3"
  },
  {
    "text": "Friendship Over",
    "character": "",
    "audioUrl": "audio/himym/036_friendship_over.mp3"
  },
  {
    "text": "Have you met Ted?",
    "character": "",
    "audioUrl": "audio/himym/038_have_you_met_ted.mp3"
  },
  {
    "text": "Hee ya! Move along!",
    "character": "",
    "audioUrl": "audio/himym/039_hee_ya_move_along.mp3"
  },
  {
    "text": "TV tone",
    "character": "",
    "audioUrl": "audio/himym/041_himym_tv_tone.mp3"
  },
  {
    "text": "Hot crazy scale",
    "character": "",
    "audioUrl": "audio/himym/043_hot_crazy_scale.mp3"
  },
  {
    "text": "Husband's condoms",
    "character": "",
    "audioUrl": "audio/himym/044_husband_s_condoms.mp3"
  },
  {
    "text": "I am sick of being smarter than everyone else",
    "character": "",
    "audioUrl": "audio/himym/046_i_am_sick_of_being_smarter_than_everyone_else.mp3"
  },
  {
    "text": "I can woo",
    "character": "",
    "audioUrl": "audio/himym/047_i_can_woo.mp3"
  },
  {
    "text": "I dare you guys to dare us to makeout",
    "character": "",
    "audioUrl": "audio/himym/048_i_dare_you_guys_to_dare_us_to_makeout.mp3"
  },
  {
    "text": "I forbid you from calling her",
    "character": "",
    "audioUrl": "audio/himym/049_i_forbid_you_from_calling_her.mp3"
  },
  {
    "text": "Reevaluate my life decisions",
    "character": "",
    "audioUrl": "audio/himym/050_i_need_to_go_home_reevaluate_how_i_make_life_decisions.mp3"
  },
  {
    "text": "I said good day!",
    "character": "",
    "audioUrl": "audio/himym/052_i_said_good_day.mp3"
  },
  {
    "text": "I was a teenage pop star in Canada",
    "character": "",
    "audioUrl": "audio/himym/053_i_was_a_teenage_pop_star_in_canada.mp3"
  },
  {
    "text": "I'm awesome",
    "character": "",
    "audioUrl": "audio/himym/054_i_m_awesome.mp3"
  },
  {
    "text": "Ice cream! Air guitar",
    "character": "",
    "audioUrl": "audio/himym/058_ice_cream_air_guitar.mp3"
  },
  {
    "text": "It's gonna be legen..",
    "character": "",
    "audioUrl": "audio/himym/061_it_s_gonna_be_legen.mp3"
  },
  {
    "text": "Legend..",
    "character": "",
    "audioUrl": "audio/himym/064_legend.mp3"
  },
  {
    "text": "Living in America",
    "character": "",
    "audioUrl": "audio/himym/066_living_in_america_barney_stinson.mp3"
  },
  {
    "text": "Marshall vs the Machines",
    "character": "",
    "audioUrl": "audio/himym/067_marshall_vs_the_machines.mp3"
  },
  {
    "text": "Mermaid becomes manatee",
    "character": "",
    "audioUrl": "audio/himym/068_mermaid_becomes_manatee.mp3"
  },
  {
    "text": "My chair is reasonably comfortable",
    "character": "",
    "audioUrl": "audio/himym/070_my_chair_is_reasonably_comfortable.mp3"
  },
  {
    "text": "New is always better",
    "character": "",
    "audioUrl": "audio/himym/072_new_is_always_better.mp3"
  },
  {
    "text": "Oh my god can you just be cool",
    "character": "",
    "audioUrl": "audio/himym/073_oh_my_god_can_you_just_be_cool.mp3"
  },
  {
    "text": "Pain montage",
    "character": "",
    "audioUrl": "audio/himym/074_pain_montage.mp3"
  },
  {
    "text": "Peace out, hombres",
    "character": "",
    "audioUrl": "audio/himym/075_peace_out_hombres.mp3"
  },
  {
    "text": "Robin's birthday lesson",
    "character": "",
    "audioUrl": "audio/himym/079_robin_s_birthday_lesson.mp3"
  },
  {
    "text": "Rock you til Canada Day",
    "character": "",
    "audioUrl": "audio/himym/080_rock_u_til_canada_day.mp3"
  },
  {
    "text": "Sisters fight, Ted!",
    "character": "",
    "audioUrl": "audio/himym/081_sisters_fight_ted.mp3"
  },
  {
    "text": "Slap countdown",
    "character": "",
    "audioUrl": "audio/himym/082_slap_countdown.mp3"
  },
  {
    "text": "Spinter sized splinter",
    "character": "",
    "audioUrl": "audio/himym/085_spinter_sized_splinter.mp3"
  },
  {
    "text": "Thank you",
    "character": "",
    "audioUrl": "audio/himym/087_thank_you.mp3"
  },
  {
    "text": "Thank you Linus",
    "character": "",
    "audioUrl": "audio/himym/088_thank_you_linus.mp3"
  },
  {
    "text": "That's what your mom said",
    "character": "",
    "audioUrl": "audio/himym/094_thats_what_your_mom_said.mp3"
  },
  {
    "text": "No slap today",
    "character": "",
    "audioUrl": "audio/himym/095_there_will_be_no_slap_today_slapsgiving.mp3"
  },
  {
    "text": "Think of me like Yoda, instead of..",
    "character": "",
    "audioUrl": "audio/himym/096_think_of_me_like_yoda_instead_of.mp3"
  },
  {
    "text": "Two out of three times, guaranteed",
    "character": "",
    "audioUrl": "audio/himym/099_two_out_of_three_times_guaranteed.mp3"
  },
  {
    "text": "Wait for it..",
    "character": "",
    "audioUrl": "audio/himym/101_wait_for_it.mp3"
  },
  {
    "text": "Walk of shame",
    "character": "",
    "audioUrl": "audio/himym/102_walk_of_shame.mp3"
  },
  {
    "text": "We will be what is up New York",
    "character": "",
    "audioUrl": "audio/himym/103_we_will_be_what_is_up_new_york.mp3"
  },
  {
    "text": "Well that's not what you want",
    "character": "",
    "audioUrl": "audio/himym/104_well_that_s_not_what_you_want.mp3"
  },
  {
    "text": "What I love about halloween",
    "character": "",
    "audioUrl": "audio/himym/106_what_i_love_about_halloween.mp3"
  },
  {
    "text": "What No",
    "character": "",
    "audioUrl": "audio/himym/107_what_no.mp3"
  },
  {
    "text": "What's in the Box",
    "character": "",
    "audioUrl": "audio/himym/109_what_s_in_the_box.mp3"
  },
  {
    "text": "You can slap him",
    "character": "",
    "audioUrl": "audio/himym/112_you_can_slap_him_slapsgiving.mp3"
  },
  {
    "text": "You just got slapped",
    "character": "",
    "audioUrl": "audio/himym/113_you_just_got_slapped_chorus.mp3"
  }
];
