// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "A sailor",
    "character": "",
    "audioUrl": "audio/wedding-crashers/002_a_sailor.mp3"
  },
  {
    "text": "Boo yah! That’s what we call a sack lunch!",
    "character": "",
    "audioUrl": "audio/wedding-crashers/004_boo_yah_that_s_what_we_call_a_sack_lunch.mp3"
  },
  {
    "text": "Call me Kitty Cat",
    "character": "",
    "audioUrl": "audio/wedding-crashers/005_call_me_kitty_cat.mp3"
  },
  {
    "text": "Cause I'd find you",
    "character": "",
    "audioUrl": "audio/wedding-crashers/007_cause_i_d_find_you.mp3"
  },
  {
    "text": "Congress Shortsided",
    "character": "",
    "audioUrl": "audio/wedding-crashers/008_congress_shortsided.mp3"
  },
  {
    "text": "Crab cakes",
    "character": "",
    "audioUrl": "audio/wedding-crashers/009_crab_cakes.mp3"
  },
  {
    "text": "Erroneous!!",
    "character": "",
    "audioUrl": "audio/wedding-crashers/011_erroneous.mp3"
  },
  {
    "text": "Fried",
    "character": "",
    "audioUrl": "audio/wedding-crashers/012_fried.mp3"
  },
  {
    "text": "He's joking around",
    "character": "",
    "audioUrl": "audio/wedding-crashers/014_he_s_joking_around.mp3"
  },
  {
    "text": "Her name is chastity, she is whitetrash",
    "character": "",
    "audioUrl": "audio/wedding-crashers/015_her_name_is_chastity_she_is_whitetrash.mp3"
  },
  {
    "text": "Hey ma!? Can we get some meatloaf?",
    "character": "",
    "audioUrl": "audio/wedding-crashers/016_hey_ma_can_we_get_some_meatloaf.mp3"
  },
  {
    "text": "I almost nunchucked you",
    "character": "",
    "audioUrl": "audio/wedding-crashers/017_i_almost_nunchucked_you.mp3"
  },
  {
    "text": "I'll be in my room painting",
    "character": "",
    "audioUrl": "audio/wedding-crashers/022_i_ll_be_in_my_room_painting.mp3"
  },
  {
    "text": "I'm diggin talking with ya",
    "character": "",
    "audioUrl": "audio/wedding-crashers/023_i_m_diggin_talking_with_ya.mp3"
  },
  {
    "text": "I've got a stage 5 clinger",
    "character": "",
    "audioUrl": "audio/wedding-crashers/026_i_ve_got_a_stage_5_clinger.mp3"
  },
  {
    "text": "I’m great I’m going",
    "character": "",
    "audioUrl": "audio/wedding-crashers/027_i_m_great_i_m_going.mp3"
  },
  {
    "text": "Interested",
    "character": "",
    "audioUrl": "audio/wedding-crashers/028_interested.mp3"
  },
  {
    "text": "It's gonna be so much fun!",
    "character": "",
    "audioUrl": "audio/wedding-crashers/029_it_s_gonna_be_so_much_fun.mp3"
  },
  {
    "text": "A couple kids who like to fuck",
    "character": "",
    "audioUrl": "audio/wedding-crashers/031_just_a_couple_kids_who_like_to_fuck_trying_to_make_it_honest.mp3"
  },
  {
    "text": "Let's play tummy sticks",
    "character": "",
    "audioUrl": "audio/wedding-crashers/033_let_s_play_tummy_sticks.mp3"
  },
  {
    "text": "Light up cigars",
    "character": "",
    "audioUrl": "audio/wedding-crashers/034_light_up_cigars.mp3"
  },
  {
    "text": "Ma, the meatloaf! Fuck!",
    "character": "",
    "audioUrl": "audio/wedding-crashers/035_ma_the_meatloaf_fuck.mp3"
  },
  {
    "text": "Maple",
    "character": "",
    "audioUrl": "audio/wedding-crashers/036_maple.mp3"
  },
  {
    "text": "Meatloaf",
    "character": "",
    "audioUrl": "audio/wedding-crashers/037_meatloaf.mp3"
  },
  {
    "text": "Motor Boat",
    "character": "",
    "audioUrl": "audio/wedding-crashers/038_motor_boat.mp3"
  },
  {
    "text": "Rule",
    "character": "",
    "audioUrl": "audio/wedding-crashers/042_rule.mp3"
  },
  {
    "text": "She's not just another notch in your belt",
    "character": "",
    "audioUrl": "audio/wedding-crashers/043_she_s_not_just_another_notch_in_your_belt.mp3"
  },
  {
    "text": "Shut your mouth funny guy",
    "character": "",
    "audioUrl": "audio/wedding-crashers/045_shut_your_mouth_funny_guy.mp3"
  },
  {
    "text": "Sock gag",
    "character": "",
    "audioUrl": "audio/wedding-crashers/047_sock_gag.mp3"
  },
  {
    "text": "Taking grenades",
    "character": "",
    "audioUrl": "audio/wedding-crashers/049_taking_grenades.mp3"
  },
  {
    "text": "Tattoo on the lower back",
    "character": "",
    "audioUrl": "audio/wedding-crashers/050_tattoo_on_the_lower_back.mp3"
  },
  {
    "text": "This feels borderline inappropriate",
    "character": "",
    "audioUrl": "audio/wedding-crashers/051_this_feels_borderline_inappropriate.mp3"
  },
  {
    "text": "We only use 10 percent of our hearts",
    "character": "",
    "audioUrl": "audio/wedding-crashers/053_we_only_use_10_percent_of_our_hearts.mp3"
  },
  {
    "text": "We've rocked them all",
    "character": "",
    "audioUrl": "audio/wedding-crashers/054_we_ve_rocked_them_all.mp3"
  },
  {
    "text": "We’re making progress",
    "character": "",
    "audioUrl": "audio/wedding-crashers/055_we_re_making_progress.mp3"
  },
  {
    "text": "What an idiot",
    "character": "",
    "audioUrl": "audio/wedding-crashers/056_what_an_idiot.mp3"
  },
  {
    "text": "What an idiot",
    "character": "",
    "audioUrl": "audio/wedding-crashers/057_what_an_idiot.mp3"
  },
  {
    "text": "What an idiot",
    "character": "",
    "audioUrl": "audio/wedding-crashers/058_what_an_idiot.mp3"
  },
  {
    "text": "What is she doing",
    "character": "",
    "audioUrl": "audio/wedding-crashers/059_what_is_she_doing.mp3"
  },
  {
    "text": "What is she doing?",
    "character": "",
    "audioUrl": "audio/wedding-crashers/060_what_is_she_doing.mp3"
  },
  {
    "text": "What the fuck do you want?",
    "character": "",
    "audioUrl": "audio/wedding-crashers/061_what_the_fuck_do_you_want.mp3"
  },
  {
    "text": "Whatever clown",
    "character": "",
    "audioUrl": "audio/wedding-crashers/062_whatever_clown.mp3"
  },
  {
    "text": "Why are you yelling?",
    "character": "",
    "audioUrl": "audio/wedding-crashers/063_why_are_you_yelling.mp3"
  },
  {
    "text": "'Cause I'd find you",
    "character": "",
    "audioUrl": "audio/wedding-crashers/065_cause_i_d_find_you.mp3"
  }
];
