// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "All about you",
    "character": "",
    "audioUrl": "audio/bojack-horseman/001_all_about_you.mp3"
  },
  {
    "text": "Am I dying?",
    "character": "",
    "audioUrl": "audio/bojack-horseman/003_am_i_dying.mp3"
  },
  {
    "text": "Are you drunk?",
    "character": "",
    "audioUrl": "audio/bojack-horseman/004_are_you_drunk.mp3"
  },
  {
    "text": "Breaking and entering",
    "character": "",
    "audioUrl": "audio/bojack-horseman/012_breaking_and_entering.mp3"
  },
  {
    "text": "Child labor",
    "character": "",
    "audioUrl": "audio/bojack-horseman/018_child_labor.mp3"
  },
  {
    "text": "Cookies for breakfast",
    "character": "",
    "audioUrl": "audio/bojack-horseman/019_cookies_for_breakfast.mp3"
  },
  {
    "text": "Could have gone worse",
    "character": "",
    "audioUrl": "audio/bojack-horseman/020_could_have_gone_worse.mp3"
  },
  {
    "text": "Enough of being a great mom",
    "character": "",
    "audioUrl": "audio/bojack-horseman/025_enough_of_being_a_great_mom.mp3"
  },
  {
    "text": "First day in prison",
    "character": "",
    "audioUrl": "audio/bojack-horseman/028_first_day_in_prison.mp3"
  },
  {
    "text": "Get me a beer",
    "character": "",
    "audioUrl": "audio/bojack-horseman/029_get_me_a_beer.mp3"
  },
  {
    "text": "Horsing Around ring",
    "character": "",
    "audioUrl": "audio/bojack-horseman/039_horsing_around_ring.mp3"
  },
  {
    "text": "How can I offend Alaskans",
    "character": "",
    "audioUrl": "audio/bojack-horseman/040_how_can_i_offend_alaskans.mp3"
  },
  {
    "text": "I didn't think of that",
    "character": "",
    "audioUrl": "audio/bojack-horseman/044_i_didn_t_think_of_that.mp3"
  },
  {
    "text": "I don't care",
    "character": "",
    "audioUrl": "audio/bojack-horseman/046_i_don_t_care.mp3"
  },
  {
    "text": "I don't remember things",
    "character": "",
    "audioUrl": "audio/bojack-horseman/048_i_don_t_remember_things.mp3"
  },
  {
    "text": "I hate honeydew",
    "character": "",
    "audioUrl": "audio/bojack-horseman/052_i_hate_honeydew.mp3"
  },
  {
    "text": "I need you to like me",
    "character": "",
    "audioUrl": "audio/bojack-horseman/055_i_need_you_to_like_me.mp3"
  },
  {
    "text": "I parked in a handicap spot",
    "character": "",
    "audioUrl": "audio/bojack-horseman/056_i_parked_in_a_handicap_spot.mp3"
  },
  {
    "text": "I'll listen",
    "character": "",
    "audioUrl": "audio/bojack-horseman/060_i_ll_listen.mp3"
  },
  {
    "text": "I'm not a good person",
    "character": "",
    "audioUrl": "audio/bojack-horseman/065_i_m_not_a_good_person.mp3"
  },
  {
    "text": "It's society's fault",
    "character": "",
    "audioUrl": "audio/bojack-horseman/071_it_s_societies_fault.mp3"
  },
  {
    "text": "Leave more quietly",
    "character": "",
    "audioUrl": "audio/bojack-horseman/079_leave_more_quietly.mp3"
  },
  {
    "text": "Love you",
    "character": "",
    "audioUrl": "audio/bojack-horseman/080_love_you.mp3"
  },
  {
    "text": "Mr. Peanutbutter",
    "character": "",
    "audioUrl": "audio/bojack-horseman/081_mr_peanut_butter.mp3"
  },
  {
    "text": "My addiction didn't pull a knife",
    "character": "",
    "audioUrl": "audio/bojack-horseman/083_my_addiction_didn_t_pull_a_knife_on_me_and_say_hey_bob_drink.mp3"
  },
  {
    "text": "Internalized self-hatred of horses",
    "character": "",
    "audioUrl": "audio/bojack-horseman/084_my_parents_gave_me_an_internalized_self_hatred_of_horses_so.mp3"
  },
  {
    "text": "Need more flasks",
    "character": "",
    "audioUrl": "audio/bojack-horseman/085_need_more_flasks.mp3"
  },
  {
    "text": "Direct me to my room, dipshit",
    "character": "",
    "audioUrl": "audio/bojack-horseman/091_now_if_you_ll_kindly_direct_me_to_my_room_i_would_like_to_be.mp3"
  },
  {
    "text": "Officer Fuzzyface",
    "character": "",
    "audioUrl": "audio/bojack-horseman/092_officer_fuzzyface.mp3"
  },
  {
    "text": "PC's ringtone",
    "character": "",
    "audioUrl": "audio/bojack-horseman/095_pcs_ringtone.mp3"
  },
  {
    "text": "Regrettable life choices",
    "character": "",
    "audioUrl": "audio/bojack-horseman/097_regrettable_life_choices.mp3"
  },
  {
    "text": "Your sayings don't do that",
    "character": "",
    "audioUrl": "audio/bojack-horseman/099_see_usually_the_point_of_sayings_is_they_illustrate_complica.mp3"
  },
  {
    "text": "Shut the hell up",
    "character": "",
    "audioUrl": "audio/bojack-horseman/100_shut_the_hell_up.mp3"
  },
  {
    "text": "Skip ad button",
    "character": "",
    "audioUrl": "audio/bojack-horseman/103_skip_ad_button.mp3"
  },
  {
    "text": "Is this what therapy is?",
    "character": "",
    "audioUrl": "audio/bojack-horseman/105_so_the_only_way_i_can_progress_is_to_return_to_my_life_as_a.mp3"
  },
  {
    "text": "Trying to make me vomit",
    "character": "",
    "audioUrl": "audio/bojack-horseman/115_trying_to_make_me_vomit.mp3"
  },
  {
    "text": "We are gonna bond",
    "character": "",
    "audioUrl": "audio/bojack-horseman/116_we_are_gonna_bond.mp3"
  },
  {
    "text": "Who's that dog",
    "character": "",
    "audioUrl": "audio/bojack-horseman/120_whos_that_dog.mp3"
  },
  {
    "text": "Why bother doing anything?",
    "character": "",
    "audioUrl": "audio/bojack-horseman/122_why_bother_doing_anything.mp3"
  },
  {
    "text": "Why bother talking",
    "character": "",
    "audioUrl": "audio/bojack-horseman/123_why_bother_talking.mp3"
  },
  {
    "text": "You are my house guest",
    "character": "",
    "audioUrl": "audio/bojack-horseman/125_you_are_my_house_guest.mp3"
  },
  {
    "text": "Is that what you really want?",
    "character": "",
    "audioUrl": "audio/bojack-horseman/126_you_get_sneak_out_the_upstairs_window_after_midnight_bed_che.mp3"
  },
  {
    "text": "You're a horrible person",
    "character": "",
    "audioUrl": "audio/bojack-horseman/127_you_re_a_horrible_person.mp3"
  }
];
