// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "Ah! That hurt!",
    "character": "",
    "audioUrl": "audio/nathan-for-you/001_ah_that_hurt.mp3"
  },
  {
    "text": "Are you hungry?",
    "character": "",
    "audioUrl": "audio/nathan-for-you/002_are_you_hungry.mp3"
  },
  {
    "text": "Are you serious?",
    "character": "",
    "audioUrl": "audio/nathan-for-you/003_are_you_serious.mp3"
  },
  {
    "text": "But, maybe though, right?",
    "character": "",
    "audioUrl": "audio/nathan-for-you/004_but_maybe_though_right.mp3"
  },
  {
    "text": "Cursed with too much love",
    "character": "",
    "audioUrl": "audio/nathan-for-you/005_cursed_with_too_much_love.mp3"
  },
  {
    "text": "Daddy's no longer around",
    "character": "",
    "audioUrl": "audio/nathan-for-you/006_daddy_s_no_longer_around.mp3"
  },
  {
    "text": "Delete the video!",
    "character": "",
    "audioUrl": "audio/nathan-for-you/007_delete_the_video.mp3"
  },
  {
    "text": "Do not answer to nobody",
    "character": "",
    "audioUrl": "audio/nathan-for-you/008_do_not_answer_to_nobody.mp3"
  },
  {
    "text": "Fire danger",
    "character": "",
    "audioUrl": "audio/nathan-for-you/009_fire_danger.mp3"
  },
  {
    "text": "Gotta pull out",
    "character": "",
    "audioUrl": "audio/nathan-for-you/010_gotta_pull_out.mp3"
  },
  {
    "text": "I am so sad",
    "character": "",
    "audioUrl": "audio/nathan-for-you/011_i_am_so_sad.mp3"
  },
  {
    "text": "I Feel Like a Beer",
    "character": "",
    "audioUrl": "audio/nathan-for-you/012_i_feel_like_a_beer.mp3"
  },
  {
    "text": "I have a doctor's appointment",
    "character": "",
    "audioUrl": "audio/nathan-for-you/013_i_have_a_doctor_s_appointment.mp3"
  },
  {
    "text": "I hope you're hungry",
    "character": "",
    "audioUrl": "audio/nathan-for-you/014_i_hope_you_re_hungry.mp3"
  },
  {
    "text": "I love you",
    "character": "",
    "audioUrl": "audio/nathan-for-you/015_i_love_you.mp3"
  },
  {
    "text": "I Love You..",
    "character": "",
    "audioUrl": "audio/nathan-for-you/016_i_love_you.mp3"
  },
  {
    "text": "I Should've Married Her",
    "character": "",
    "audioUrl": "audio/nathan-for-you/017_i_should_ve_married_her.mp3"
  },
  {
    "text": "I suppose so!",
    "character": "",
    "audioUrl": "audio/nathan-for-you/018_i_suppose_so.mp3"
  },
  {
    "text": "I'd love to be in your will",
    "character": "",
    "audioUrl": "audio/nathan-for-you/019_i_d_love_to_be_in_your_will.mp3"
  },
  {
    "text": "I'm truly sorry",
    "character": "",
    "audioUrl": "audio/nathan-for-you/020_i_m_truly_sorry.mp3"
  },
  {
    "text": "In between relationships",
    "character": "",
    "audioUrl": "audio/nathan-for-you/021_in_between_relationships.mp3"
  },
  {
    "text": "Knowledge to help businesses",
    "character": "",
    "audioUrl": "audio/nathan-for-you/022_knowledge_to_help_businesses.mp3"
  },
  {
    "text": "Liar and cool guy",
    "character": "",
    "audioUrl": "audio/nathan-for-you/023_liar_and_cool_guy.mp3"
  },
  {
    "text": "Nathan Fielder Asian Accent",
    "character": "",
    "audioUrl": "audio/nathan-for-you/024_nathan_fielder_asian_accent.mp3"
  },
  {
    "text": "Nathan Likes Sex",
    "character": "",
    "audioUrl": "audio/nathan-for-you/025_nathan_likes_sex.mp3"
  },
  {
    "text": "Nobody Listens When You Speak",
    "character": "",
    "audioUrl": "audio/nathan-for-you/026_nobody_listens_when_you_speak.mp3"
  },
  {
    "text": "Not a negotiation",
    "character": "",
    "audioUrl": "audio/nathan-for-you/027_not_a_negotiation.mp3"
  },
  {
    "text": "Oh my god, are you serious?",
    "character": "",
    "audioUrl": "audio/nathan-for-you/028_oh_my_god_are_you_serious.mp3"
  },
  {
    "text": "Oh my lord, okay",
    "character": "",
    "audioUrl": "audio/nathan-for-you/029_oh_my_lord_okay.mp3"
  },
  {
    "text": "Oh, crap",
    "character": "",
    "audioUrl": "audio/nathan-for-you/030_oh_crap.mp3"
  },
  {
    "text": "Ordinary pack of gum",
    "character": "",
    "audioUrl": "audio/nathan-for-you/031_ordinary_pack_of_gum.mp3"
  },
  {
    "text": "Strange giggle",
    "character": "",
    "audioUrl": "audio/nathan-for-you/032_strange_giggle.mp3"
  },
  {
    "text": "Teach him a lesson",
    "character": "",
    "audioUrl": "audio/nathan-for-you/033_teach_him_a_lesson.mp3"
  },
  {
    "text": "Thinking about superheroes",
    "character": "",
    "audioUrl": "audio/nathan-for-you/034_thinking_about_superheroes.mp3"
  },
  {
    "text": "This Is So Sad song",
    "character": "",
    "audioUrl": "audio/nathan-for-you/035_this_is_so_sad_song.mp3"
  },
  {
    "text": "Today is very good",
    "character": "",
    "audioUrl": "audio/nathan-for-you/036_today_is_very_good.mp3"
  },
  {
    "text": "Tuck you in bed",
    "character": "",
    "audioUrl": "audio/nathan-for-you/037_tuck_you_in_bed.mp3"
  },
  {
    "text": "TURN OFF THE MUSIC",
    "character": "",
    "audioUrl": "audio/nathan-for-you/038_turn_off_the_music.mp3"
  },
  {
    "text": "Weak handshake",
    "character": "",
    "audioUrl": "audio/nathan-for-you/039_weak_handshake.mp3"
  },
  {
    "text": "Yes",
    "character": "",
    "audioUrl": "audio/nathan-for-you/040_yes.mp3"
  },
  {
    "text": "You are a little shit!",
    "character": "",
    "audioUrl": "audio/nathan-for-you/041_you_are_a_little_shit.mp3"
  },
  {
    "text": "You Have To Go",
    "character": "",
    "audioUrl": "audio/nathan-for-you/042_you_have_to_go.mp3"
  },
  {
    "text": "You seem unsure",
    "character": "",
    "audioUrl": "audio/nathan-for-you/043_you_seem_unsure.mp3"
  },
  {
    "text": "You're so weird",
    "character": "",
    "audioUrl": "audio/nathan-for-you/044_you_re_so_weird.mp3"
  },
  {
    "text": "You're very manipulative",
    "character": "",
    "audioUrl": "audio/nathan-for-you/045_you_re_very_manipulative.mp3"
  }
];
