#!/usr/bin/env python3
"""
Aggregate every per-show audio/<id>/quotes.js into shows.js at the project root.

Reads metadata (name, theme) from scripts/shows.yaml. Each show's quotes are
extracted from its quotes.js by stripping the wrapper and parsing the array.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
AUDIO_ROOT = REPO_ROOT / "audio"
SHOWS_YAML = REPO_ROOT / "scripts" / "shows.yaml"
OUT_PATH = REPO_ROOT / "shows.js"

sys.path.insert(0, str(REPO_ROOT / "scripts"))
from scrape_soundboard import load_shows_yaml  # type: ignore


_ARRAY_RE = re.compile(r"const\s+quotes\s*=\s*(\[[\s\S]*?\])\s*;?\s*$", re.MULTILINE)


def parse_quotes_js(path: Path) -> list[dict]:
    text = path.read_text(encoding="utf-8")
    m = _ARRAY_RE.search(text)
    if not m:
        raise ValueError(f"Could not find `const quotes = [...]` in {path}")
    return json.loads(m.group(1))


def main() -> None:
    if not SHOWS_YAML.exists():
        print(f"shows.yaml not found at {SHOWS_YAML}", file=sys.stderr)
        sys.exit(1)

    registry = load_shows_yaml(SHOWS_YAML)
    out_shows: list[dict] = []

    for s in registry:
        sid = s.get("id")
        if not sid:
            continue
        quotes_path = AUDIO_ROOT / sid / "quotes.js"
        if not quotes_path.exists():
            print(f"skip {sid}: no audio/{sid}/quotes.js yet")
            continue
        try:
            quotes = parse_quotes_js(quotes_path)
        except Exception as e:
            print(f"skip {sid}: failed to parse quotes.js ({e})", file=sys.stderr)
            continue

        out_shows.append({
            "id": sid,
            "name": s.get("name", sid),
            "theme": s.get("theme", {}),
            "text_style": s.get("text_style", "caption"),
            "quotes": quotes,
        })
        print(f"included {sid}: {len(quotes)} quotes")

    body = json.dumps(out_shows, indent=2, ensure_ascii=False)
    OUT_PATH.write_text(
        f"// Auto-generated by build_shows.py. Do not edit by hand.\n"
        f"const shows = {body};\n",
        encoding="utf-8",
    )
    print(f"\nWrote {OUT_PATH} ({len(out_shows)} shows)")


if __name__ == "__main__":
    main()
