// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "All right, well... Everybody grab a box. Let's go.",
    "character": "",
    "audioUrl": "audio/ozark/001_all_right_well_everybody_grab_a_box_let_s_go.mp3"
  },
  {
    "text": "Answer's the same as it was five minutes ago. She's been in there for hours. You don't say. Can you at least check to see what's going on? Nope.",
    "character": "",
    "audioUrl": "audio/ozark/003_answer_s_the_same_as_it_was_five_minutes_ago_she_s_been_in_t.mp3"
  },
  {
    "text": "Are you ready to tell me where you are? [Wendy] No.",
    "character": "",
    "audioUrl": "audio/ozark/004_are_you_ready_to_tell_me_where_you_are_wendy_no.mp3"
  },
  {
    "text": "Buddy told me he wanted to die at home in his bed. Do you think he'd be upset that he died in his car? No, sweetheart, I don't think he'd be upset about that.",
    "character": "",
    "audioUrl": "audio/ozark/005_buddy_told_me_he_wanted_to_die_at_home_in_his_bed_do_you_thi.mp3"
  },
  {
    "text": "Can you do me a favor and get the fuck out and close the door? I take my orders from Sam. -Oh, is that right? Well... -Mm hmm. Well, how 'bout I pop those tits and squeeze out the silicone? -How do you feel about that? -[gasps]",
    "character": "",
    "audioUrl": "audio/ozark/006_can_you_do_me_a_favor_and_get_the_fuck_out_and_close_the_doo.mp3"
  },
  {
    "text": "Do you have his ashes? [sniffles]. Yeah. [sobs] Are they heavy?",
    "character": "",
    "audioUrl": "audio/ozark/007_do_you_have_his_ashes_sniffles_yeah_sobs_are_they_heavy.mp3"
  },
  {
    "text": "Enlighten my eyes... or I shall sleep the sleep of death.",
    "character": "",
    "audioUrl": "audio/ozark/008_enlighten_my_eyes_or_i_shall_sleep_the_sleep_of_death.mp3"
  },
  {
    "text": "Great. Get the fuck out. Do it. -I don't need you. -[door opens] -I don't even fucking know you anymore. -[door shuts] [sighs]",
    "character": "",
    "audioUrl": "audio/ozark/010_great_get_the_fuck_out_do_it_i_don_t_need_you_door_opens_i_d.mp3"
  },
  {
    "text": "He just sits there. [Charlotte] Who is he? Is he dangerous? Uh, no. He's not dangerous. He's a colleague. -Why don't you wave to him? -[engine starts]",
    "character": "",
    "audioUrl": "audio/ozark/011_he_just_sits_there_charlotte_who_is_he_is_he_dangerous_uh_no.mp3"
  },
  {
    "text": "He loses it. Another day goes by, I'll lie in my bed... cry about... killing the kid on the scooter or... the homeless marine... or my father dying. And my father was not a good person, but... I imagine him there at the end.",
    "character": "",
    "audioUrl": "audio/ozark/012_he_loses_it_another_day_goes_by_i_ll_lie_in_my_bed_cry_about.mp3"
  },
  {
    "text": "Hey, Eddie, you got any Oxy? No Oxy. Got some H, though. -I don't want that shit. -Well, suit yourself. Wait.",
    "character": "",
    "audioUrl": "audio/ozark/013_hey_eddie_you_got_any_oxy_no_oxy_got_some_h_though_i_don_t_w.mp3"
  },
  {
    "text": "Hey. Can I take a look at this?",
    "character": "",
    "audioUrl": "audio/ozark/014_hey_can_i_take_a_look_at_this.mp3"
  },
  {
    "text": "Hi. What? You don't recognize me without my tits in your face? How's it going, Raven? Actually, my name's Margaret. -You got that pay stub? -[softly] Yeah. Great.",
    "character": "",
    "audioUrl": "audio/ozark/015_hi_what_you_don_t_recognize_me_without_my_tits_in_your_face.mp3"
  },
  {
    "text": "How is this any different from the power company. flooding out our forebears a hundred years ago? We entered into it by choice. We did, Darlene. Not without reservation, but for the benefit of the family. And our family will benefit. -The family? -Uh huh. What family?",
    "character": "",
    "audioUrl": "audio/ozark/016_how_is_this_any_different_from_the_power_company_flooding_ou.mp3"
  },
  {
    "text": "Jacob. Oh, God. Don't you go and die on me, baby. Oh, God, don't you die on me.",
    "character": "",
    "audioUrl": "audio/ozark/018_jacob_oh_god_don_t_you_go_and_die_on_me_baby_oh_god_don_t_yo.mp3"
  },
  {
    "text": "Marty! Welcome to our home, Martin Byrde.",
    "character": "",
    "audioUrl": "audio/ozark/019_marty_welcome_to_our_home_martin_byrde.mp3"
  },
  {
    "text": "Morning, ladies. -We ready? -Mm hmm. Looking good. Call the Mexicans.",
    "character": "",
    "audioUrl": "audio/ozark/020_morning_ladies_we_ready_mm_hmm_looking_good_call_the_mexican.mp3"
  },
  {
    "text": "Not very. [sniffling]",
    "character": "",
    "audioUrl": "audio/ozark/021_not_very_sniffling.mp3"
  },
  {
    "text": "Off you go. [Erin] Hi, guys.",
    "character": "",
    "audioUrl": "audio/ozark/022_off_you_go_erin_hi_guys.mp3"
  },
  {
    "text": "Oh. Mmm. [inhales deeply] -I'm so sorry you feel that way. Hmm. -Hmm. Hmm.",
    "character": "",
    "audioUrl": "audio/ozark/023_oh_mmm_inhales_deeply_i_m_so_sorry_you_feel_that_way_hmm_hmm.mp3"
  },
  {
    "text": "Okay. I got the rest of this. Thank you.",
    "character": "",
    "audioUrl": "audio/ozark/024_okay_i_got_the_rest_of_this_thank_you.mp3"
  },
  {
    "text": "Open the goddamn door! ReEncoded By Dr.XJ | PSA www.PSArips.com.",
    "character": "",
    "audioUrl": "audio/ozark/025_open_the_goddamn_door_reencoded_by_dr_xj_psa_www_psarips_com.mp3"
  },
  {
    "text": "Sue? Sue, are you here? It's Marty.",
    "character": "",
    "audioUrl": "audio/ozark/026_sue_sue_are_you_here_it_s_marty.mp3"
  },
  {
    "text": "The kids love you. And I love you.",
    "character": "",
    "audioUrl": "audio/ozark/027_the_kids_love_you_and_i_love_you.mp3"
  },
  {
    "text": "Things happen. You apologize and you move on. She blew a man's head off. For which she is contrite. Am I supposed to believe that? -The woman brought you fresh honey. -Mm hmm.",
    "character": "",
    "audioUrl": "audio/ozark/028_things_happen_you_apologize_and_you_move_on_she_blew_a_man_s.mp3"
  },
  {
    "text": "Took it the night we were putting it in the wall. I don't even know why I did it. -How much is it? -Ten thousand. You think I should tell Mom and Dad? No. We might need it. [Charlotte sighs]",
    "character": "",
    "audioUrl": "audio/ozark/029_took_it_the_night_we_were_putting_it_in_the_wall_i_don_t_eve.mp3"
  },
  {
    "text": "What are you doing in the safe? Looking for the ham sandwich I left.",
    "character": "",
    "audioUrl": "audio/ozark/030_what_are_you_doing_in_the_safe_looking_for_the_ham_sandwich.mp3"
  },
  {
    "text": "What are you doing? [gunshots] ♪ Oh, don't you know It's time for me to fly ♪ -♪ Oh, I've got to set myself free ♪ -♪ Time for me to fly ♪ ♪ Oh, baby, that's just how It's got to be ♪ [soft moan]",
    "character": "",
    "audioUrl": "audio/ozark/031_what_are_you_doing_gunshots_oh_don_t_you_know_it_s_time_for.mp3"
  },
  {
    "text": "Would you die without that oxygen? Hey, I don't know. Am I dead yet? Hmm? [chuckles] Yeah. Wanna try?",
    "character": "",
    "audioUrl": "audio/ozark/032_would_you_die_without_that_oxygen_hey_i_don_t_know_am_i_dead.mp3"
  },
  {
    "text": "You like your fucking job? Just shut the door, please.",
    "character": "",
    "audioUrl": "audio/ozark/033_you_like_your_fucking_job_just_shut_the_door_please.mp3"
  },
  {
    "text": "You sound like your brother. Hmm. I just gotta get myself re socialized, I guess. There is no excuse. -Hmm. -Can you forgive me?",
    "character": "",
    "audioUrl": "audio/ozark/034_you_sound_like_your_brother_hmm_i_just_gotta_get_myself_re_s.mp3"
  },
  {
    "text": "You think I should say something? No, it'll just give them something else to fight about.",
    "character": "",
    "audioUrl": "audio/ozark/035_you_think_i_should_say_something_no_it_ll_just_give_them_som.mp3"
  },
  {
    "text": "You understand punitive interest, don't you, Marty? $200,000.",
    "character": "",
    "audioUrl": "audio/ozark/036_you_understand_punitive_interest_don_t_you_marty_200_000.mp3"
  },
  {
    "text": "You wanna talk about a house, all that shit? I'll listen. No. You're right. That's not for us.",
    "character": "",
    "audioUrl": "audio/ozark/037_you_wanna_talk_about_a_house_all_that_shit_i_ll_listen_no_yo.mp3"
  },
  {
    "text": "You're gonna walk home? Home is a 43 minute walk from here. By the time I get there, I want you out.",
    "character": "",
    "audioUrl": "audio/ozark/038_you_re_gonna_walk_home_home_is_a_43_minute_walk_from_here_by.mp3"
  },
  {
    "text": "-[\"Besame Mucho\" playing] -[trembling breaths]",
    "character": "",
    "audioUrl": "audio/ozark/039_besame_mucho_playing_trembling_breaths.mp3"
  },
  {
    "text": "-[birds twittering] -[water laps softly]",
    "character": "",
    "audioUrl": "audio/ozark/040_birds_twittering_water_laps_softly.mp3"
  },
  {
    "text": "-[grunts] -[screaming] [shouting in Spanish] [screams] -[gags] -[grunts]",
    "character": "",
    "audioUrl": "audio/ozark/041_grunts_screaming_shouting_in_spanish_screams_gags_grunts.mp3"
  },
  {
    "text": "-[hammering] -[saw whirring] ReEncoded By Dr.XJ | PSA www.PSArips.com.",
    "character": "",
    "audioUrl": "audio/ozark/042_hammering_saw_whirring_reencoded_by_dr_xj_psa_www_psarips_c.mp3"
  },
  {
    "text": "-[indistinct chatter on police radio] -[camera clicking]",
    "character": "",
    "audioUrl": "audio/ozark/043_indistinct_chatter_on_police_radio_camera_clicking.mp3"
  },
  {
    "text": "-[keys jangling] -[footsteps approaching] -[panting] -[doors open] Who's that? ¿Quién es ese? [grunting]",
    "character": "",
    "audioUrl": "audio/ozark/044_keys_jangling_footsteps_approaching_panting_doors_open_who.mp3"
  },
  {
    "text": "-[man] Yeah, baby! -[cheering] -It's party time! -[man] Hit it!",
    "character": "",
    "audioUrl": "audio/ozark/045_man_yeah_baby_cheering_it_s_party_time_man_hit_it.mp3"
  },
  {
    "text": "-[Muzak plays softly over speakers] -[door bell jingling] ReEncoded By Dr.XJ | PSA www.PSArips.com.",
    "character": "",
    "audioUrl": "audio/ozark/046_muzak_plays_softly_over_speakers_door_bell_jingling_reencod.mp3"
  },
  {
    "text": "-[Wilkes] I know. It's a lot. -Please. -In Chicago, this would be baby steps. -[Wilkes chuckles] They're all gonna be at the prayer luncheon today.",
    "character": "",
    "audioUrl": "audio/ozark/047_wilkes_i_know_it_s_a_lot_please_in_chicago_this_would_be_ba.mp3"
  },
  {
    "text": "-Fuck, yeah. -What? My broker told me to short Weight Watchers, and it just went down 12%. [chuckles] You got a broker? You gotta clean your money somehow, man. -Hey, look, I'll send you his email. -Okay.",
    "character": "",
    "audioUrl": "audio/ozark/048_fuck_yeah_what_my_broker_told_me_to_short_weight_watchers_a.mp3"
  },
  {
    "text": "-iVamos! -[handcuffs ratchet] [opens box]",
    "character": "",
    "audioUrl": "audio/ozark/049_ivamos_handcuffs_ratchet_opens_box.mp3"
  },
  {
    "text": "-Ma'am. Ma'am? -What's wrong with her? We don't know yet, son. Pinpoint pupils. Do you know what kind of drugs she was taking? -Resp in the toilet. You wanna intubate? -No, let's bag her first.",
    "character": "",
    "audioUrl": "audio/ozark/050_ma_am_ma_am_what_s_wrong_with_her_we_don_t_know_yet_son_pin.mp3"
  },
  {
    "text": "-Yeah? -People are complaining. [Petty] You mean the one other person that's here? There's people in here yappin' all night. Well, look, there's no one here but me. Keep it down, okay?",
    "character": "",
    "audioUrl": "audio/ozark/051_yeah_people_are_complaining_petty_you_mean_the_one_other_pe.mp3"
  },
  {
    "text": "-You want a do over? -Uh, no. -Are you sure? -Yep. If I was going on a trip, I'd be smiling. Well, it's a white background, no shadow, eyes open, neutral expression. That's a TSA checklist right there. -So, where are you headed? -Abroad.",
    "character": "",
    "audioUrl": "audio/ozark/052_you_want_a_do_over_uh_no_are_you_sure_yep_if_i_was_going_on.mp3"
  },
  {
    "text": "[beeping] Adiós, pendejo.",
    "character": "",
    "audioUrl": "audio/ozark/053_beeping_adi_s_pendejo.mp3"
  },
  {
    "text": "[bugs chirring] [mourning dove calls]",
    "character": "",
    "audioUrl": "audio/ozark/054_bugs_chirring_mourning_dove_calls.mp3"
  },
  {
    "text": "[Cade chuckles] Don't mind if I do. We'll come back after dark, Ruthie. [chuckles]",
    "character": "",
    "audioUrl": "audio/ozark/055_cade_chuckles_don_t_mind_if_i_do_we_ll_come_back_after_dark.mp3"
  },
  {
    "text": "[captured man whispers prayer in Spanish]",
    "character": "",
    "audioUrl": "audio/ozark/056_captured_man_whispers_prayer_in_spanish.mp3"
  },
  {
    "text": "[Darlene] Hold on, baby. Please, please, please, just hold on. [rapid gunfire] Drive, you idiot. [tires screeching]",
    "character": "",
    "audioUrl": "audio/ozark/058_darlene_hold_on_baby_please_please_please_just_hold_on_rapi.mp3"
  },
  {
    "text": "[Darlene] Jacob's angry with me. I can tell. [sighs] Just feels different.",
    "character": "",
    "audioUrl": "audio/ozark/059_darlene_jacob_s_angry_with_me_i_can_tell_sighs_just_feels_d.mp3"
  },
  {
    "text": "[dialing] -What the fuck are you doing? -Calling the cops. Stop! Don't! Who the hell are those people? Ask your fucking sister.",
    "character": "",
    "audioUrl": "audio/ozark/060_dialing_what_the_fuck_are_you_doing_calling_the_cops_stop_d.mp3"
  },
  {
    "text": "[dials] [crickets chirping ringtone]",
    "character": "",
    "audioUrl": "audio/ozark/061_dials_crickets_chirping_ringtone.mp3"
  },
  {
    "text": "[door opens] [door shuts] [clicks]",
    "character": "",
    "audioUrl": "audio/ozark/062_door_opens_door_shuts_clicks.mp3"
  },
  {
    "text": "[door opens] You can't just walk in here like this. What if I was dressing? [Cade] You really think I'm gonna see something that shocks me? And you got a fucking job to see about. [breathes deeply] I'm sorry I laid hands on you.",
    "character": "",
    "audioUrl": "audio/ozark/063_door_opens_you_can_t_just_walk_in_here_like_this_what_if_i.mp3"
  },
  {
    "text": "[groans softly] [sirens wailing in the distance] [breathing shakily]",
    "character": "",
    "audioUrl": "audio/ozark/064_groans_softly_sirens_wailing_in_the_distance_breathing_shak.mp3"
  },
  {
    "text": "[Jacob] Busy morning looks like. Not a thing to worry about. This is Jonah's, just back from the taxiderm. What the hell's that? Boy's first kill.",
    "character": "",
    "audioUrl": "audio/ozark/065_jacob_busy_morning_looks_like_not_a_thing_to_worry_about_th.mp3"
  },
  {
    "text": "[Junior Walker & The All Stars' \"Shotgun\" playing on radio] [Buddy laughing] Oh, man. Now this takes me way back.",
    "character": "",
    "audioUrl": "audio/ozark/066_junior_walker_the_all_stars_shotgun_playing_on_radio_buddy.mp3"
  },
  {
    "text": "[knocks] Sue? [rings doorbell] It's Marty. [knocks]",
    "character": "",
    "audioUrl": "audio/ozark/067_knocks_sue_rings_doorbell_it_s_marty_knocks.mp3"
  },
  {
    "text": "[men and women chattering in Spanish] -[Mariachi music playing] -[chatter, laughter continuing]",
    "character": "",
    "audioUrl": "audio/ozark/068_men_and_women_chattering_in_spanish_mariachi_music_playing.mp3"
  },
  {
    "text": "[men and women screaming] [device beeping] [clamoring]",
    "character": "",
    "audioUrl": "audio/ozark/069_men_and_women_screaming_device_beeping_clamoring.mp3"
  },
  {
    "text": "[men murmuring in Spanish]",
    "character": "",
    "audioUrl": "audio/ozark/070_men_murmuring_in_spanish.mp3"
  },
  {
    "text": "[music plays in Spanish over radio] [speaking Spanish]",
    "character": "",
    "audioUrl": "audio/ozark/071_music_plays_in_spanish_over_radio_speaking_spanish.mp3"
  },
  {
    "text": "[rock music playing over speakers] [sales associate over speakers] Attention, Superstore shoppers. Stock up on cold weather gear, now ten percent off with our September Super Savings Sale. Hey, sport. How can I help? -Hi. -Hi.",
    "character": "",
    "audioUrl": "audio/ozark/073_rock_music_playing_over_speakers_sales_associate_over_speak.mp3"
  },
  {
    "text": "[Ruth] I only saw the one who pointed the gun at me. [Ben] Uh, there were four. Uh, the driver, and the three who threw Marty in the backseat. -And the man in charge. Describe him. -Um... Little guy. Uh, he had mean eyes, uh, and balding, balding. Shit.",
    "character": "",
    "audioUrl": "audio/ozark/075_ruth_i_only_saw_the_one_who_pointed_the_gun_at_me_ben_uh_th.mp3"
  },
  {
    "text": "[shouts] [theme music playing]",
    "character": "",
    "audioUrl": "audio/ozark/076_shouts_theme_music_playing.mp3"
  },
  {
    "text": "[sliding door opens] [Charlotte] I'm ready. Hon, I know we said yes, but I don't think this is a good idea. Was last night really an accident? -[bell tolling continues] -Yeah. [Charlotte] Well, then I wanna go.",
    "character": "",
    "audioUrl": "audio/ozark/077_sliding_door_opens_charlotte_i_m_ready_hon_i_know_we_said_y.mp3"
  },
  {
    "text": "[slurps] We're here, whenever you want to come home, okay?",
    "character": "",
    "audioUrl": "audio/ozark/078_slurps_we_re_here_whenever_you_want_to_come_home_okay.mp3"
  },
  {
    "text": "[snoring] [theme music playing]",
    "character": "",
    "audioUrl": "audio/ozark/079_snoring_theme_music_playing.mp3"
  },
  {
    "text": "[snorting] [sniffles]",
    "character": "",
    "audioUrl": "audio/ozark/080_snorting_sniffles.mp3"
  },
  {
    "text": "[speaking Spanish]",
    "character": "",
    "audioUrl": "audio/ozark/081_speaking_spanish.mp3"
  },
  {
    "text": "[ticking] [festive music continues playing] [explosion] [theme music playing]",
    "character": "",
    "audioUrl": "audio/ozark/082_ticking_festive_music_continues_playing_explosion_theme_mus.mp3"
  },
  {
    "text": "[tires screech] [Helen] I'm telling you, I had nothing to do with this. -You wouldn't tell me if you did. -I didn't do this. But I was afraid it would happen.",
    "character": "",
    "audioUrl": "audio/ozark/083_tires_screech_helen_i_m_telling_you_i_had_nothing_to_do_wit.mp3"
  },
  {
    "text": "[tires screeching] [grunting] Get the fuck away from me. -[Ash] Get up. -Get the fuck away from me! -Get the fuck up! -What's your problem? -Get the... -[man grunts] Okay, all right! Get in the truck! [all grunting] -Get in the fucking truck. Get-- -[grunting]",
    "character": "",
    "audioUrl": "audio/ozark/084_tires_screeching_grunting_get_the_fuck_away_from_me_ash_get.mp3"
  },
  {
    "text": "[Tuck] Over here! Help! Quick, hurry! Hurry up! This way! Hurry!",
    "character": "",
    "audioUrl": "audio/ozark/085_tuck_over_here_help_quick_hurry_hurry_up_this_way_hurry.mp3"
  },
  {
    "text": "[vultures screeching] ReEncoded By Dr.XJ | PSA www.PSArips.com.",
    "character": "",
    "audioUrl": "audio/ozark/086_vultures_screeching_reencoded_by_dr_xj_psa_www_psarips_com.mp3"
  },
  {
    "text": "[woman] Go ahead. Give it to her. [Tuck sobbing] Is she dead?",
    "character": "",
    "audioUrl": "audio/ozark/088_woman_go_ahead_give_it_to_her_tuck_sobbing_is_she_dead.mp3"
  },
  {
    "text": "[woman] Mason! Ash is here to help with the boat. [Mason] I'll be in in a second.",
    "character": "",
    "audioUrl": "audio/ozark/089_woman_mason_ash_is_here_to_help_with_the_boat_mason_i_ll_be.mp3"
  },
  {
    "text": "$724,000 is all I've got and it's earmarked. All you got sounds about right. [scoffs]",
    "character": "",
    "audioUrl": "audio/ozark/090_724_000_is_all_i_ve_got_and_it_s_earmarked_all_you_got_soun.mp3"
  }
];
