// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "Ah shit",
    "character": "",
    "audioUrl": "audio/f-is-for-family/001_ah_shit_overlapping_chatter.mp3"
  },
  {
    "text": "Fucking Charlie Brown",
    "character": "",
    "audioUrl": "audio/f-is-for-family/002_ah_a_person_pussy_god_damn_it_stop_ripping_fucking_charlie_b.mp3"
  },
  {
    "text": "You fucking turncoat",
    "character": "",
    "audioUrl": "audio/f-is-for-family/003_ah_what_the_hell_are_you_doing_here_back_off_bob_just_trying.mp3"
  },
  {
    "text": "Through that fuckin' wall",
    "character": "",
    "audioUrl": "audio/f-is-for-family/004_and_i_will_put_you_through_that_fuckin_wall.mp3"
  },
  {
    "text": "Four feets, don't fail me",
    "character": "",
    "audioUrl": "audio/f-is-for-family/005_and_now_back_to_the_watts_world_travelers_and_the_haunted_di.mp3"
  },
  {
    "text": "Right through the fucking wall",
    "character": "",
    "audioUrl": "audio/f-is-for-family/006_and_put_you_right_through_the_fucking_wall.mp3"
  },
  {
    "text": "Put you through that wall",
    "character": "",
    "audioUrl": "audio/f-is-for-family/007_and_put_you_through_that_fucking_wall.mp3"
  },
  {
    "text": "Told a nun: fuck herself",
    "character": "",
    "audioUrl": "audio/f-is-for-family/008_bless_me_father_for_i_have_sinned_i_just_told_a_nun_to_go_fu.mp3"
  },
  {
    "text": "Bridget? Bridget?",
    "character": "",
    "audioUrl": "audio/f-is-for-family/011_bridget_bridget_huh.mp3"
  },
  {
    "text": "I'm dead! I'm dead!",
    "character": "",
    "audioUrl": "audio/f-is-for-family/012_can_i_get_the_check_i_m_dead_i_m_dead_i_m_dead.mp3"
  },
  {
    "text": "Make it the last night",
    "character": "",
    "audioUrl": "audio/f-is-for-family/013_come_on_charlie_make_it_the_last_night_make_it_the_last_nigh.mp3"
  },
  {
    "text": "Dada? Dada?",
    "character": "",
    "audioUrl": "audio/f-is-for-family/014_dada_dada_dada_dada_dada.mp3"
  },
  {
    "text": "You remember nothing!",
    "character": "",
    "audioUrl": "audio/f-is-for-family/015_daddy_wawa_daddy_wawa_oh_my_god_is_that_where_i_almost_drown.mp3"
  },
  {
    "text": "Christmas in July in December",
    "character": "",
    "audioUrl": "audio/f-is-for-family/017_dinner_and_a_hat_it_s_christmas_in_july_in_december_come_and.mp3"
  },
  {
    "text": "Forced me to eat candy",
    "character": "",
    "audioUrl": "audio/f-is-for-family/018_dolores_a_puerto_rican_kidnapped_me_and_forced_me_to_eat_can.mp3"
  },
  {
    "text": "Don't you father me",
    "character": "",
    "audioUrl": "audio/f-is-for-family/019_frank_don_t_you_father_me_i_ll_put_you_through_that_fucking.mp3"
  },
  {
    "text": "Frank Murphy, you handsome devil",
    "character": "",
    "audioUrl": "audio/f-is-for-family/020_frank_murphy_you_handsome_devil_you_got_all_the_answers_don.mp3"
  },
  {
    "text": "Just spoke from the heart",
    "character": "",
    "audioUrl": "audio/f-is-for-family/022_frank_no_one_s_talked_to_me_like_that_in_30_years_just_spoke.mp3"
  },
  {
    "text": "I never tasted blue before",
    "character": "",
    "audioUrl": "audio/f-is-for-family/023_gentiles_with_clubs_but_i_m_still_having_fun_i_never_tasted.mp3"
  },
  {
    "text": "Too bad everybody hates you",
    "character": "",
    "audioUrl": "audio/f-is-for-family/024_good_luck_at_the_auditions_too_bad_everybody_hates_you_cause.mp3"
  },
  {
    "text": "A man's gotta do",
    "character": "",
    "audioUrl": "audio/f-is-for-family/025_here_s_my_chance_but_we_were_in_the_middle_of_a_game_what_ab.mp3"
  },
  {
    "text": "Give me my bean juice",
    "character": "",
    "audioUrl": "audio/f-is-for-family/026_here_s_the_coffee_you_wanted_i_didn_t_ask_for_no_bean_juice.mp3"
  },
  {
    "text": "Wuv You Waffles",
    "character": "",
    "audioUrl": "audio/f-is-for-family/027_hey_phillip_my_girlfriend_s_in_the_paper_bridget_fitzsimmons.mp3"
  },
  {
    "text": "Try this here electric lasso",
    "character": "",
    "audioUrl": "audio/f-is-for-family/029_i_can_t_reach_it_hey_ben_try_this_here_electric_lasso_oh_shi.mp3"
  },
  {
    "text": "Screw a First Lady",
    "character": "",
    "audioUrl": "audio/f-is-for-family/030_i_have_a_question_if_you_had_to_screw_a_first_lady_who_would.mp3"
  },
  {
    "text": "I never missed a day",
    "character": "",
    "audioUrl": "audio/f-is-for-family/031_i_never_missed_a_day_once_i_came_in_when_kennedy_was_shot_wh.mp3"
  },
  {
    "text": "I swear to God",
    "character": "",
    "audioUrl": "audio/f-is-for-family/032_i_swear_to_god_i_will_put_you_through_that_fucking_wall.mp3"
  },
  {
    "text": "Through that divider curtain",
    "character": "",
    "audioUrl": "audio/f-is-for-family/033_i_will_put_you_through_that_fucking_divider_curtain.mp3"
  },
  {
    "text": "Kiss me, you splooge socket",
    "character": "",
    "audioUrl": "audio/f-is-for-family/034_i_like_like_you_bridget_kiss_me_you_splooge_socket_what_is_w.mp3"
  },
  {
    "text": "I'll put you through",
    "character": "",
    "audioUrl": "audio/f-is-for-family/035_i_ll_put_you_through_that_fucking_wall.mp3"
  },
  {
    "text": "Locked out of the house",
    "character": "",
    "audioUrl": "audio/f-is-for-family/036_i_m_gonna_go_back_inside_now_okay_i_m_locked_out_of_the_hous.mp3"
  },
  {
    "text": "I'm good with dogs",
    "character": "",
    "audioUrl": "audio/f-is-for-family/037_i_m_good_with_dogs_i_ll_put_you_through_that_fucking_wall_ou.mp3"
  },
  {
    "text": "I was only kidding, water",
    "character": "",
    "audioUrl": "audio/f-is-for-family/039_i_m_not_gonna_let_you_ruin_my_life_anymore_tonight_i_un_drow.mp3"
  },
  {
    "text": "Hunky dory from down here",
    "character": "",
    "audioUrl": "audio/f-is-for-family/041_i_m_not_sleeping_well_i_feel_so_stressed_frank_s_overworked.mp3"
  },
  {
    "text": "Come on up, Bob",
    "character": "",
    "audioUrl": "audio/f-is-for-family/042_i_m_proud_to_introduce_our_new_vice_president_of_operations.mp3"
  },
  {
    "text": "Taking you down with me",
    "character": "",
    "audioUrl": "audio/f-is-for-family/043_i_m_taking_you_down_with_me_i_should_ve_driven_over_you_when.mp3"
  },
  {
    "text": "Don't let me wake up",
    "character": "",
    "audioUrl": "audio/f-is-for-family/044_i_ve_never_seen_anything_so_beautiful_please_don_t_let_me_wa.mp3"
  },
  {
    "text": "Is everybody a loser?",
    "character": "",
    "audioUrl": "audio/f-is-for-family/045_is_everybody_in_your_family_a_loser_chuckles_get_the_fuck_ou.mp3"
  },
  {
    "text": "Morphine suppositories",
    "character": "",
    "audioUrl": "audio/f-is-for-family/046_it_s_brilliant_that_s_it_that_s_my_new_invention_yes_yes_oh.mp3"
  },
  {
    "text": "Don't wanna go to Pittsburgh",
    "character": "",
    "audioUrl": "audio/f-is-for-family/047_let_me_out_i_don_t_want_to_go_to_pittsburgh.mp3"
  },
  {
    "text": "That flashing fuel light",
    "character": "",
    "audioUrl": "audio/f-is-for-family/048_look_that_s_bill_vic_you_found_him_oh_thank_god_i_can_get_ou.mp3"
  },
  {
    "text": "My witness, that fuckin' wall",
    "character": "",
    "audioUrl": "audio/f-is-for-family/049_my_witness_i_will_put_you_through_that_fuckin_wall.mp3"
  },
  {
    "text": "Whippoorwill will dine in you",
    "character": "",
    "audioUrl": "audio/f-is-for-family/050_nice_work_jimmy_bell_rings_what_whippoorwill_will_dine_in_yo.mp3"
  },
  {
    "text": "Now that's cold blooded",
    "character": "",
    "audioUrl": "audio/f-is-for-family/051_now_that_s_cold_blooded_ah.mp3"
  },
  {
    "text": "Oh shit, she's so beautiful",
    "character": "",
    "audioUrl": "audio/f-is-for-family/052_oh_shit_oh_shit_she_s_so_beautiful.mp3"
  },
  {
    "text": "Oh yeah, oh yeah",
    "character": "",
    "audioUrl": "audio/f-is-for-family/053_oh_yeah_oh_yeah.mp3"
  },
  {
    "text": "A ring and a bottle",
    "character": "",
    "audioUrl": "audio/f-is-for-family/054_ooh_come_on_you_re_a_ring_and_a_bottle_why_do_you_hate_each.mp3"
  },
  {
    "text": "Two day anniversary cake",
    "character": "",
    "audioUrl": "audio/f-is-for-family/056_otto_it_s_ginny_from_the_softball_game_i_made_you_a_two_day.mp3"
  },
  {
    "text": "Take that dance with you",
    "character": "",
    "audioUrl": "audio/f-is-for-family/058_people_in_this_part_of_town_sure_like_to_stare_at_cars_funk.mp3"
  },
  {
    "text": "All the meat sauce",
    "character": "",
    "audioUrl": "audio/f-is-for-family/059_pretty_soon_we_ll_have_all_the_meat_sauce_we_can_drink_lock.mp3"
  },
  {
    "text": "Since I'm your father",
    "character": "",
    "audioUrl": "audio/f-is-for-family/060_since_i_m_your_father_and_i_ll_put_you_through_that_fucking.mp3"
  },
  {
    "text": "Everybody's a winner, except her",
    "character": "",
    "audioUrl": "audio/f-is-for-family/061_step_right_up_everybody_s_a_winner_except_her.mp3"
  },
  {
    "text": "They're fucking morons",
    "character": "",
    "audioUrl": "audio/f-is-for-family/064_thanks_a_million_chet_i_was_about_to_lose_my_mind_with_those.mp3"
  },
  {
    "text": "That's my Maureen",
    "character": "",
    "audioUrl": "audio/f-is-for-family/066_that_s_two_well_look_who_s_on_a_roll_that_s_my_maureen_that.mp3"
  },
  {
    "text": "You scared me half to...",
    "character": "",
    "audioUrl": "audio/f-is-for-family/067_there_you_are_maureen_you_scared_me_half_to.mp3"
  },
  {
    "text": "Free to enjoy my day",
    "character": "",
    "audioUrl": "audio/f-is-for-family/068_there_all_done_sighs_now_i_m_free_to_enjoy_the_rest_of_my_da.mp3"
  },
  {
    "text": "Bear shit in the woods",
    "character": "",
    "audioUrl": "audio/f-is-for-family/069_vic_we_need_music_when_are_you_gonna_start_playing_some_reco.mp3"
  },
  {
    "text": "Well, shine my shoes",
    "character": "",
    "audioUrl": "audio/f-is-for-family/070_well_shine_my_shoes_at_least_the_spin_cycle_works_now_we_sho.mp3"
  },
  {
    "text": "Shit cock! Fuck that guy",
    "character": "",
    "audioUrl": "audio/f-is-for-family/071_what_a_dick_shit_cock_ugh_fuck_that_guy_bullshit_hey_move_it.mp3"
  },
  {
    "text": "How to rearrange a face",
    "character": "",
    "audioUrl": "audio/f-is-for-family/072_what_the_fuck_is_wrong_with_you_maybe_if_you_didn_t_cut_clas.mp3"
  },
  {
    "text": "I grew it myself",
    "character": "",
    "audioUrl": "audio/f-is-for-family/073_you_have_beautiful_hair_thank_you_i_grew_it_myself_oh_you_re.mp3"
  },
  {
    "text": "Bath in your own blood",
    "character": "",
    "audioUrl": "audio/f-is-for-family/074_1x01_the_bleedin_in_sweden_crickets_chirring_man_on_tv_and_n.mp3"
  },
  {
    "text": "I'm not killing anybody today",
    "character": "",
    "audioUrl": "audio/f-is-for-family/075_heya_rosie_frank_murphy_if_you_re_here_to_shoot_up_the_plac.mp3"
  },
  {
    "text": "Supposed to watch me",
    "character": "",
    "audioUrl": "audio/f-is-for-family/076_i_m_gonna_crash_stick_that_landing_oh_i_m_gonna_crash_maure.mp3"
  },
  {
    "text": "It's vanilla extract",
    "character": "",
    "audioUrl": "audio/f-is-for-family/077_mm_your_cologne_smells_sweet_it_s_vanilla_extract_bob_pogo.mp3"
  },
  {
    "text": "My prisoner in the dungeon",
    "character": "",
    "audioUrl": "audio/f-is-for-family/078_where_the_hell_have_you_been_nowhere_what_dinner_s_ready_oh.mp3"
  },
  {
    "text": "Don't know what you saw",
    "character": "",
    "audioUrl": "audio/f-is-for-family/079_both_screaming_leave_leave_leave_kevin_i_don_t_know_what_yo.mp3"
  },
  {
    "text": "I will blow a horse",
    "character": "",
    "audioUrl": "audio/f-is-for-family/080_chanting_murphy_murphy_murphy_murphy_man_on_tv_there_you_ha.mp3"
  },
  {
    "text": "The shit outta the ropes",
    "character": "",
    "audioUrl": "audio/f-is-for-family/081_clattering_jesus_jesus_sorry_lord_man_that_s_ok_no_biggie_w.mp3"
  },
  {
    "text": "They'll try, Sweet Cakes",
    "character": "",
    "audioUrl": "audio/f-is-for-family/082_clicking_frank_oh_he_s_out_of_bullets_woman_on_tv_colt_they.mp3"
  },
  {
    "text": "Keep your head up",
    "character": "",
    "audioUrl": "audio/f-is-for-family/083_grunts_remember_to_keep_your_head_up_you_redheaded_fag_that.mp3"
  },
  {
    "text": "Eeny Meeny Meiny Dead",
    "character": "",
    "audioUrl": "audio/f-is-for-family/084_man_colt_luger_starring_reid_harrison_with_edison_hurrell_j.mp3"
  },
  {
    "text": "Sobbing: oh God",
    "character": "",
    "audioUrl": "audio/f-is-for-family/085_wailing_muffled_sobs_whining_sobbing_oh_god.mp3"
  }
];
