// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "We signed a new recruit",
    "character": "",
    "audioUrl": "audio/atlanta/001_all_right_all_right_we_just_signed_a_new_recruit_so_i_m_gonn.mp3"
  },
  {
    "text": "FX promo: The Americans",
    "character": "",
    "audioUrl": "audio/atlanta/002_an_fx_original_series_the_americans_the_riveting_final_seaso.mp3"
  },
  {
    "text": "Are you coming back tonight?",
    "character": "",
    "audioUrl": "audio/atlanta/003_are_you_coming_back_tonight_um_no.mp3"
  },
  {
    "text": "Are you high? Not really",
    "character": "",
    "audioUrl": "audio/atlanta/004_are_you_high_not_really_jesus.mp3"
  },
  {
    "text": "Can you hand me those?",
    "character": "",
    "audioUrl": "audio/atlanta/005_can_you_hand_me_those_um_this_yeah_thank_you_no_problem.mp3"
  },
  {
    "text": "Jewish dude, man",
    "character": "",
    "audioUrl": "audio/atlanta/006_come_on_jewish_yeah_jewish_dude_man_yeah_i_got_you.mp3"
  },
  {
    "text": "I've never seen a parlor",
    "character": "",
    "audioUrl": "audio/atlanta/007_come_on_please_come_sit_in_the_parlor_oh_cool_i_ve_never_bee.mp3"
  },
  {
    "text": "Fuck, go, go!",
    "character": "",
    "audioUrl": "audio/atlanta/008_curtis_fuck_go_go_fuck_it_fuck_man_go.mp3"
  },
  {
    "text": "Where's my underwear?",
    "character": "",
    "audioUrl": "audio/atlanta/009_do_you_know_where_um_my_underwear_or_my_belt_is_uh_do_you_sp.mp3"
  },
  {
    "text": "No moving around the bus",
    "character": "",
    "audioUrl": "audio/atlanta/010_driver_no_moving_around_the_bus.mp3"
  },
  {
    "text": "Copy it during lunch",
    "character": "",
    "audioUrl": "audio/atlanta/012_earn_what_s_up_chillin_cool_shirt_thanks_you_do_the_math_hom.mp3"
  },
  {
    "text": "Spring Fling, $60K guaranteed",
    "character": "",
    "audioUrl": "audio/atlanta/013_earn_yo_we_should_probably_get_moving_you_know_the_75_about.mp3"
  },
  {
    "text": "Everything is gonna be okay",
    "character": "",
    "audioUrl": "audio/atlanta/014_everything_is_gonna_be_okay_hugs.mp3"
  },
  {
    "text": "I lost my belt and underwear",
    "character": "",
    "audioUrl": "audio/atlanta/015_excuse_me_sir_i_have_to_pat_you_down_lift_up_your_hands_plea.mp3"
  },
  {
    "text": "FX promo: AHS NYC",
    "character": "",
    "audioUrl": "audio/atlanta/016_fx_s_american_horror_story_nyc_ll_new_a_ednesdays_at_10_00_o.mp3"
  },
  {
    "text": "This place is a mess",
    "character": "",
    "audioUrl": "audio/atlanta/017_geez_this_place_is_a_mess_mm_you_ever_hear_of_a_trash_can_an.mp3"
  },
  {
    "text": "You better be up",
    "character": "",
    "audioUrl": "audio/atlanta/018_gloria_earn_you_better_be_up_in_there_i_am_here_comes_the_br.mp3"
  },
  {
    "text": "Paranoid, finger on the trigger",
    "character": "",
    "audioUrl": "audio/atlanta/019_got_dang_whoo_at_night_i_can_t_sleep_i_toss_and_turn_candles.mp3"
  },
  {
    "text": "Here for the pickup",
    "character": "",
    "audioUrl": "audio/atlanta/020_hello_um_i_m_here_for_the_the_uh_pick_was_that_mr_wonder.mp3"
  },
  {
    "text": "I love you very much",
    "character": "",
    "audioUrl": "audio/atlanta/021_hey_al_whatever_happens_just_know_that_i_love_you_very_much.mp3"
  },
  {
    "text": "I'm a take y'all home",
    "character": "",
    "audioUrl": "audio/atlanta/022_hey_are_you_okay_i_m_just_so_happy_y_all_pretty_i_m_a_take_y.mp3"
  },
  {
    "text": "You threw the yogurt out?",
    "character": "",
    "audioUrl": "audio/atlanta/024_hey_man_i_m_sorry_though_i_didn_t_mean_to_yo_you_threw_that.mp3"
  },
  {
    "text": "Who did that?",
    "character": "",
    "audioUrl": "audio/atlanta/025_hey_who_did_that_huh_i_said_who_did_that_aw.mp3"
  },
  {
    "text": "Come on, Gizmo, we're late",
    "character": "",
    "audioUrl": "audio/atlanta/026_hi_morning_come_on_gizmo_we_re_gonna_be_late.mp3"
  },
  {
    "text": "How much for that hat?",
    "character": "",
    "audioUrl": "audio/atlanta/028_how_much_for_that_hat_and_this_ten_dollars_bet.mp3"
  },
  {
    "text": "You're paying rent",
    "character": "",
    "audioUrl": "audio/atlanta/029_i_do_know_one_thing_though_if_you_re_still_in_my_house_when.mp3"
  },
  {
    "text": "I've thought about it a lot",
    "character": "",
    "audioUrl": "audio/atlanta/030_i_mean_yeah_i_ve_thought_about_it_a_lot_actually.mp3"
  },
  {
    "text": "Thank you, fate",
    "character": "",
    "audioUrl": "audio/atlanta/031_i_ll_pay_for_it_man_damn_just_move_thank_you_fate_i_ll_have.mp3"
  },
  {
    "text": "Call me Teddy",
    "character": "",
    "audioUrl": "audio/atlanta/032_i_m_darius_apologies_i_m_theodore_perkins_please_call_me_ted.mp3"
  },
  {
    "text": "I've been inconsiderate",
    "character": "",
    "audioUrl": "audio/atlanta/033_i_ve_been_inconsiderate_i_get_it_i_m_sorry.mp3"
  },
  {
    "text": "I love Stevie",
    "character": "",
    "audioUrl": "audio/atlanta/034_in_the_car_oh_yeah_music_of_my_mind_masterpiece_i_love_stevi.mp3"
  },
  {
    "text": "That made me hungry",
    "character": "",
    "audioUrl": "audio/atlanta/035_is_it_weird_that_made_me_hungry_you_too.mp3"
  },
  {
    "text": "You help me, Earn?",
    "character": "",
    "audioUrl": "audio/atlanta/037_let_me_get_daddy_over_here_ooh_you_help_me_earn.mp3"
  },
  {
    "text": "This is my truth (FX promo)",
    "character": "",
    "audioUrl": "audio/atlanta/038_man_this_is_who_i_am_this_is_my_truth_announcer_fx_presents.mp3"
  },
  {
    "text": "Fuck with me",
    "character": "",
    "audioUrl": "audio/atlanta/039_mm_hmm_fuck_with_me_mm_hmm.mp3"
  },
  {
    "text": "Oh, look at you",
    "character": "",
    "audioUrl": "audio/atlanta/041_oh_look_at_you.mp3"
  },
  {
    "text": "Oh, shit",
    "character": "",
    "audioUrl": "audio/atlanta/042_oh_coughing_shit_sighs.mp3"
  },
  {
    "text": "Everything's made up, stay woke",
    "character": "",
    "audioUrl": "audio/atlanta/043_paper_mail_paper_mail_all_about_my_paper_mail_chewing_mm_mm.mp3"
  },
  {
    "text": "Dehydrated mango, ginger?",
    "character": "",
    "audioUrl": "audio/atlanta/044_sh_sorry_do_you_got_any_dehydrated_mango_ginger_jicama_perha.mp3"
  },
  {
    "text": "Thought more about L.A.?",
    "character": "",
    "audioUrl": "audio/atlanta/045_so_have_you_thought_more_about_l_a.mp3"
  },
  {
    "text": "Sorry, coming through",
    "character": "",
    "audioUrl": "audio/atlanta/046_sorry_coming_through_sorry_sorry_miss_i_m_gonna_let_him_thro.mp3"
  },
  {
    "text": "Where was I?",
    "character": "",
    "audioUrl": "audio/atlanta/047_sorry_um_where_where_was_i_i_don_t_probation_princeton_right.mp3"
  },
  {
    "text": "Thanks",
    "character": "",
    "audioUrl": "audio/atlanta/049_thanks_piano_music.mp3"
  },
  {
    "text": "We made it",
    "character": "",
    "audioUrl": "audio/atlanta/050_this_it_yeah_we_made_it.mp3"
  },
  {
    "text": "This thing kills everyone",
    "character": "",
    "audioUrl": "audio/atlanta/051_this_thing_kills_everyone.mp3"
  },
  {
    "text": "Are we missing a pole?",
    "character": "",
    "audioUrl": "audio/atlanta/052_those_ones_i_think_go_by_the_door_hmm_are_we_missing_a_pole.mp3"
  },
  {
    "text": "Told ya",
    "character": "",
    "audioUrl": "audio/atlanta/053_told_ya_music_playing_inside.mp3"
  },
  {
    "text": "It's me, Candice",
    "character": "",
    "audioUrl": "audio/atlanta/054_van_it_s_me_it_s_candice_non_non_no_d_sol_e_candice_i_m_so_s.mp3"
  },
  {
    "text": "Whenever you want",
    "character": "",
    "audioUrl": "audio/atlanta/055_we_were_gonna_talk_about_it_a_little_later_yeah_whenever_you.mp3"
  },
  {
    "text": "FX promo: Archer",
    "character": "",
    "audioUrl": "audio/atlanta/057_whoo_hoo_hoo_announcer_archer_danger_island_all_new_wednesda.mp3"
  },
  {
    "text": "Paul's having a difficult time",
    "character": "",
    "audioUrl": "audio/atlanta/058_woman_paul_s_been_having_a_difficult_time_of_late.mp3"
  },
  {
    "text": "A glass of water",
    "character": "",
    "audioUrl": "audio/atlanta/059_would_you_like_a_glass_of_water_yeah_kind_of_parched_darius.mp3"
  },
  {
    "text": "I should probably... yeah",
    "character": "",
    "audioUrl": "audio/atlanta/060_wow_i_should_probably_yeah_okay.mp3"
  },
  {
    "text": "My favorite, that's real nice",
    "character": "",
    "audioUrl": "audio/atlanta/061_yeah_all_right_okay_my_favorite_that_s_real_nice.mp3"
  },
  {
    "text": "I love you. I know.",
    "character": "",
    "audioUrl": "audio/atlanta/063_aaron_what_i_love_you_oh_my_god_i_know_jesus.mp3"
  },
  {
    "text": "Let me see that bag",
    "character": "",
    "audioUrl": "audio/atlanta/065_here_you_go_thank_you_all_right_now_let_me_see_that_bag_too.mp3"
  },
  {
    "text": "I need to see your bag",
    "character": "",
    "audioUrl": "audio/atlanta/066_hi_morning_hey_good_morning_can_i_see_your_license_uh_yes_h.mp3"
  },
  {
    "text": "Probation ended",
    "character": "",
    "audioUrl": "audio/atlanta/067_how_was_your_week_fine_uh_probation_ended_uh_my_alma_mater.mp3"
  },
  {
    "text": "Is this your first time?",
    "character": "",
    "audioUrl": "audio/atlanta/068_is_this_your_first_time_here_oh_yeah_it_s_great_isn_t_it_ye.mp3"
  },
  {
    "text": "Tell me you love me",
    "character": "",
    "audioUrl": "audio/atlanta/069_mm_tell_me_you_love_me_laughs_why_did_you_just_laugh_cause.mp3"
  },
  {
    "text": "Sylvia walks me to class",
    "character": "",
    "audioUrl": "audio/atlanta/070_mommy_yes_bash_sylvia_walks_me_to_my_class_oh_okay.mp3"
  },
  {
    "text": "She's got a knife!",
    "character": "",
    "audioUrl": "audio/atlanta/071_oh_shit_she_s_got_a_knife_oh_shit_oh_oh_shit_shit_oh_oh.mp3"
  },
  {
    "text": "Sylvia died",
    "character": "",
    "audioUrl": "audio/atlanta/072_sylvia_died_w_what_what_happened_how_they_don_t_know.mp3"
  },
  {
    "text": "That was Nando's",
    "character": "",
    "audioUrl": "audio/atlanta/073_that_was_nando_s_yeah.mp3"
  },
  {
    "text": "Whoa! Dope!",
    "character": "",
    "audioUrl": "audio/atlanta/074_whoa_dope.mp3"
  },
  {
    "text": "Keep eating, please",
    "character": "",
    "audioUrl": "audio/atlanta/075_yeah_okay_keep_eating_please.mp3"
  },
  {
    "text": "Where's the storage closet?",
    "character": "",
    "audioUrl": "audio/atlanta/077_anita_i_need_you_on_the_register_after_this_i_i_i_m_lil_tay.mp3"
  },
  {
    "text": "FX promo: Legion",
    "character": "",
    "audioUrl": "audio/atlanta/078_david_david_syd_announcer_legion_all_new_tuesdays_at_10_00.mp3"
  },
  {
    "text": "I'm a pay you back",
    "character": "",
    "audioUrl": "audio/atlanta/079_hey_man_nigga_i_m_i_m_sorry_about_this_shit_man_i_m_a_pay_y.mp3"
  },
  {
    "text": "This place kind of stinks",
    "character": "",
    "audioUrl": "audio/atlanta/081_this_place_kind_of_stinks_damn_alfred_the_fuck_yeah_man_shi.mp3"
  },
  {
    "text": "A drink while you wait?",
    "character": "",
    "audioUrl": "audio/atlanta/082_it_s_forever_by_the_ebonys_would_you_like_a_drink_while_you.mp3"
  },
  {
    "text": "Muffled music",
    "character": "",
    "audioUrl": "audio/atlanta/083_muffled_music_playing_through_headphones_oh.mp3"
  },
  {
    "text": "Hip-hop instrumental",
    "character": "",
    "audioUrl": "audio/atlanta/084_music_continues_upbeat_hip_hop_instrumental_music.mp3"
  },
  {
    "text": "Paper Boi verse",
    "character": "",
    "audioUrl": "audio/atlanta/085_eat_sleep_everybody_wanna_be_a_nigga_but_nobody_wanna_be_a.mp3"
  },
  {
    "text": "Here for the pickup",
    "character": "",
    "audioUrl": "audio/atlanta/086_girl_i_m_in_love_hello_hey_yeah_um_i_m_here_for_the_pickup.mp3"
  },
  {
    "text": "Warrior, warrior",
    "character": "",
    "audioUrl": "audio/atlanta/087_keed_talk_to_em_warrior_warrior_warrior_warrior_warrior_ah.mp3"
  },
  {
    "text": "Sweet little girl",
    "character": "",
    "audioUrl": "audio/atlanta/088_sweet_little_girl_you_know_your_baby_loves_you_your_love_is.mp3"
  },
  {
    "text": "We're almost there, Lottie",
    "character": "",
    "audioUrl": "audio/atlanta/090_your_heart_has_called_me_closer_to_you_i_will_be_all_that_y.mp3"
  }
];
