// Auto-generated by scrape_soundboard.py. Edit transcripts.txt and re-run.
const quotes = [
  {
    "text": "Just email it, EOD",
    "character": "",
    "audioUrl": "audio/barbie/001_aaron_dinkins_i_think_you_re_gonna_want_to_hear_this_sir_mat.mp3"
  },
  {
    "text": "You healed",
    "character": "",
    "audioUrl": "audio/barbie/002_actually_in_the_time_that_it_took_for_me_to_say_that_sentenc.mp3"
  },
  {
    "text": "Depression Barbie",
    "character": "",
    "audioUrl": "audio/barbie/003_advertising_voice_okay_kids_it_s_time_to_run_out_and_get_the.mp3"
  },
  {
    "text": "These women are Barbie",
    "character": "",
    "audioUrl": "audio/barbie/004_all_of_these_women_are_barbie_and_barbie_is_all_of_these_wom.mp3"
  },
  {
    "text": "Let's beach off",
    "character": "",
    "audioUrl": "audio/barbie/005_all_right_ken_you_re_on_let_s_beach_off.mp3"
  },
  {
    "text": "It expands my powers",
    "character": "",
    "audioUrl": "audio/barbie/006_and_it_does_not_diminish_my_powers_it_expands_them.mp3"
  },
  {
    "text": "It's not lifeguard",
    "character": "",
    "audioUrl": "audio/barbie/007_and_it_is_not_lifeguard_which_is_a_common_misconception.mp3"
  },
  {
    "text": "And so is yesterday",
    "character": "",
    "audioUrl": "audio/barbie/008_and_so_is_yesterday_and_so_is_tomorrow_and_so_is_the_day_aft.mp3"
  },
  {
    "text": "Nobel Prize for Literature",
    "character": "",
    "audioUrl": "audio/barbie/009_and_the_nobel_prize_for_literature_goes_to_barbie.mp3"
  },
  {
    "text": "Beach me off first",
    "character": "",
    "audioUrl": "audio/barbie/010_anyone_who_wants_to_beach_him_off_has_to_beach_me_off_first.mp3"
  },
  {
    "text": "If Barbie looks at him",
    "character": "",
    "audioUrl": "audio/barbie/011_barbie_has_a_great_day_every_day_but_ken_only_has_a_great_da.mp3"
  },
  {
    "text": "You don't need my permission",
    "character": "",
    "audioUrl": "audio/barbie/012_barbie_do_you_give_me_permission_to_become_human_ruth_you_do.mp3"
  },
  {
    "text": "Stereotypical Barbie's bad day",
    "character": "",
    "audioUrl": "audio/barbie/013_barbie_i_know_i_m_stereotypical_barbie_and_therefore_don_t_f.mp3"
  },
  {
    "text": "I've never wanted change",
    "character": "",
    "audioUrl": "audio/barbie/014_barbie_i_ve_never_wanted_anything_to_change_gloria_oh_honey.mp3"
  },
  {
    "text": "It's okay if you're crying",
    "character": "",
    "audioUrl": "audio/barbie/015_barbie_it_s_okay_if_you_re_crying_you_know_i_cried_too_it_s.mp3"
  },
  {
    "text": "Roll with it, tiny baby",
    "character": "",
    "audioUrl": "audio/barbie/016_barbie_ken_what_have_you_done_what_are_you_wearing_ken_don_t.mp3"
  },
  {
    "text": "Ken's Mojo Dojo Casa House",
    "character": "",
    "audioUrl": "audio/barbie/017_barbie_no_ken_this_is_my_dreamhouse_it_is_my_dreamhouse_it_s.mp3"
  },
  {
    "text": "That's cellulite",
    "character": "",
    "audioUrl": "audio/barbie/018_barbie_oh_you_ve_done_it_you_ve_opened_a_portal_barbie_i_did.mp3"
  },
  {
    "text": "You're not even beach",
    "character": "",
    "audioUrl": "audio/barbie/019_barbie_okay_ken_you_have_to_figure_out_who_you_are_without_m.mp3"
  },
  {
    "text": "Nice looking little protein pot",
    "character": "",
    "audioUrl": "audio/barbie/020_barbie_that_ken_of_yours_he_is_one_nice_looking_little_prote.mp3"
  },
  {
    "text": "Literally and figuratively, watch me",
    "character": "",
    "audioUrl": "audio/barbie/021_barbie_wow_and_now_you_re_making_it_permanent_with_a_special.mp3"
  },
  {
    "text": "We take back Barbie Land",
    "character": "",
    "audioUrl": "audio/barbie/022_barbie_you_play_on_their_egos_and_their_petty_jealousies_and.mp3"
  },
  {
    "text": "Barbie can be anything",
    "character": "",
    "audioUrl": "audio/barbie/023_because_barbie_can_be_anything_women_can_be_anything.mp3"
  },
  {
    "text": "Beach both of us off",
    "character": "",
    "audioUrl": "audio/barbie/024_but_you_don_t_even_know_how_to_beach_yourself_off_how_you_go.mp3"
  },
  {
    "text": "Nobody's gonna beach anyone off",
    "character": "",
    "audioUrl": "audio/barbie/025_come_on_kens_nobody_s_gonna_beach_anyone_off.mp3"
  },
  {
    "text": "Compliment your fellow Barbie",
    "character": "",
    "audioUrl": "audio/barbie/026_everybody_turn_to_the_barbie_next_to_you_tell_her_how_much_y.mp3"
  },
  {
    "text": "Girls can grow into women",
    "character": "",
    "audioUrl": "audio/barbie/027_girls_can_grow_into_women_who_can_achieve_everything_and_any.mp3"
  },
  {
    "text": "You've never seen The Godfather",
    "character": "",
    "audioUrl": "audio/barbie/028_gloria_you_can_tell_him_that_you_ve_never_seen_the_godfather.mp3"
  },
  {
    "text": "Make them believe you're complacent",
    "character": "",
    "audioUrl": "audio/barbie/029_gloria_you_have_to_make_them_believe_that_you_re_complacent.mp3"
  },
  {
    "text": "Hi Barbie, oh hi Allan",
    "character": "",
    "audioUrl": "audio/barbie/030_hi_barbie_hi_barbie_hi_barbies_bye_barbies_bye_barbie_hi_bar.mp3"
  },
  {
    "text": "I'm just dying to dance",
    "character": "",
    "audioUrl": "audio/barbie/031_i_don_t_know_why_i_just_said_that_i_m_just_dying_to_dance.mp3"
  },
  {
    "text": "Both logic and feeling",
    "character": "",
    "audioUrl": "audio/barbie/032_i_have_no_difficulty_holding_both_logic_and_feeling_at_the_s.mp3"
  },
  {
    "text": "Because we're girlfriend boyfriend",
    "character": "",
    "audioUrl": "audio/barbie/033_i_thought_i_might_stay_over_tonight_why_because_we_re_girlfr.mp3"
  },
  {
    "text": "Beach you both at once",
    "character": "",
    "audioUrl": "audio/barbie/034_i_will_beach_both_of_you_off_at_the_same_time.mp3"
  },
  {
    "text": "If I wasn't severely injured",
    "character": "",
    "audioUrl": "audio/barbie/036_if_i_wasn_t_severely_injured_i_would_beach_you_off_right_now.mp3"
  },
  {
    "text": "Money is not speech",
    "character": "",
    "audioUrl": "audio/barbie/037_in_our_assessment_money_is_not_speech_and_corporations_have.mp3"
  },
  {
    "text": "Corporations have no free speech",
    "character": "",
    "audioUrl": "audio/barbie/038_in_our_assessment_money_is_not_speech_and_corporations_have.mp3"
  },
  {
    "text": "Choreography and a bespoke song",
    "character": "",
    "audioUrl": "audio/barbie/039_just_a_giant_blowout_party_with_all_the_barbies_and_planned.mp3"
  },
  {
    "text": "I'm just Ken",
    "character": "",
    "audioUrl": "audio/barbie/040_ken_singing_i_m_just_ken_anywhere_else_i_d_be_a_ten_is_it_my.mp3"
  },
  {
    "text": "Nobel Prize for horses",
    "character": "",
    "audioUrl": "audio/barbie/041_ken_and_the_nobel_prize_for_horses_goes_to_ken.mp3"
  },
  {
    "text": "Not the Palazzos!",
    "character": "",
    "audioUrl": "audio/barbie/042_ken_barbie_take_your_lady_fashions_with_you_take_your_celebr.mp3"
  },
  {
    "text": "Can I come over tonight?",
    "character": "",
    "audioUrl": "audio/barbie/043_ken_can_i_come_to_your_house_tonight_barbie_sure_i_don_t_hav.mp3"
  },
  {
    "text": "Every night is girls' night",
    "character": "",
    "audioUrl": "audio/barbie/044_ken_every_night_is_girls_night.mp3"
  },
  {
    "text": "Hi Barbie, hi Ken",
    "character": "",
    "audioUrl": "audio/barbie/045_ken_hi_barbie_barbie_hi_ken_barbie_hi_barbie_barbie_hi_barbi.mp3"
  },
  {
    "text": "I'm a liberated man",
    "character": "",
    "audioUrl": "audio/barbie/046_ken_i_m_a_liberated_man_i_know_crying_is_not_weak.mp3"
  },
  {
    "text": "Here, I'm just a dude",
    "character": "",
    "audioUrl": "audio/barbie/047_ken_out_there_i_was_somebody_and_when_i_walked_down_the_stre.mp3"
  },
  {
    "text": "Talk singing of Lou Reed",
    "character": "",
    "audioUrl": "audio/barbie/048_ken_stephen_malkamus_really_harnessed_the_acerbic_talk_singi.mp3"
  },
  {
    "text": "No, we go to war",
    "character": "",
    "audioUrl": "audio/barbie/049_ken_what_do_we_do_ken_we_beach_every_individual_one_of_them.mp3"
  },
  {
    "text": "Too much beach for you",
    "character": "",
    "audioUrl": "audio/barbie/050_looks_like_this_beach_was_a_little_too_much_beach_for_you_ke.mp3"
  },
  {
    "text": "Let's just tickle each other",
    "character": "",
    "audioUrl": "audio/barbie/051_mattel_ceo_let_s_have_a_company_retreat_and_just_tickle_each.mp3"
  },
  {
    "text": "They've gone to Barbie Land",
    "character": "",
    "audioUrl": "audio/barbie/052_mattel_ceo_they_ve_gone_to_barbie_land_aaron_dinkins_oh_no_m.mp3"
  },
  {
    "text": "Get in the box, Jezebel",
    "character": "",
    "audioUrl": "audio/barbie/053_mattel_ceo_what_i_m_trying_to_say_is_get_in_the_box_you_jeze.mp3"
  },
  {
    "text": "Midge, the pregnant doll",
    "character": "",
    "audioUrl": "audio/barbie/055_narrator_midge_was_barbie_s_pregnant_friend_let_s_not_show_m.mp3"
  },
  {
    "text": "Kens have to start somewhere",
    "character": "",
    "audioUrl": "audio/barbie/056_narrator_well_the_kens_have_to_start_somewhere_and_one_day_t.mp3"
  },
  {
    "text": "Barbie changed everything",
    "character": "",
    "audioUrl": "audio/barbie/057_narrator_yes_barbie_changed_everything_then_she_changed_it_a.mp3"
  },
  {
    "text": "Just a boring mom",
    "character": "",
    "audioUrl": "audio/barbie/059_sasha_are_you_shining_with_a_real_barbie_gloria_no_i_mean_ma.mp3"
  },
  {
    "text": "Kens can't resist a damsel",
    "character": "",
    "audioUrl": "audio/barbie/060_sasha_distract_them_by_appearing_helpless_and_confused_kens.mp3"
  },
  {
    "text": "I don't have an ending",
    "character": "",
    "audioUrl": "audio/barbie/061_sasha_hey_what_about_barbie_mattel_ceo_what_do_you_mean_sash.mp3"
  },
  {
    "text": "The old standby: wearing glasses",
    "character": "",
    "audioUrl": "audio/barbie/062_sasha_or_distract_them_with_the_old_standby_wearing_glasses.mp3"
  },
  {
    "text": "Exactly what I thought",
    "character": "",
    "audioUrl": "audio/barbie/063_sasha_you_know_i_almost_feel_bad_for_you_but_you_are_exactly.mp3"
  },
  {
    "text": "Shredding waves is dangerous",
    "character": "",
    "audioUrl": "audio/barbie/064_shredding_waves_is_much_more_dangerous_than_people_realize.mp3"
  },
  {
    "text": "Since the beginning of time",
    "character": "",
    "audioUrl": "audio/barbie/065_since_the_beginning_of_time_since_the_first_little_girl_ever.mp3"
  },
  {
    "text": "Always and forever baby dolls",
    "character": "",
    "audioUrl": "audio/barbie/066_since_the_beginning_of_time_since_the_first_little_girl_ever.mp3"
  },
  {
    "text": "Democracy into a plutocracy",
    "character": "",
    "audioUrl": "audio/barbie/067_so_any_claim_on_their_part_to_be_exercising_a_right_is_just.mp3"
  },
  {
    "text": "Best day ever",
    "character": "",
    "audioUrl": "audio/barbie/068_so_do_i_this_is_the_best_day_ever_it_is_the_best_day_ever_an.mp3"
  },
  {
    "text": "All problems of feminism solved",
    "character": "",
    "audioUrl": "audio/barbie/069_thanks_to_barbie_all_problems_of_feminism_and_equal_rights_h.mp3"
  },
  {
    "text": "This night is just perfect",
    "character": "",
    "audioUrl": "audio/barbie/070_thanks_barbie_gosh_this_night_is_just_perfect.mp3"
  },
  {
    "text": "Nobel Prize for Journalism",
    "character": "",
    "audioUrl": "audio/barbie/071_the_nobel_prize_for_journalism_goes_to_barbie.mp3"
  },
  {
    "text": "No multiples of Allan",
    "character": "",
    "audioUrl": "audio/barbie/072_there_are_no_multiples_of_allan_he_s_just_allan_yeah_i_m_i_c.mp3"
  },
  {
    "text": "This makes me emotional",
    "character": "",
    "audioUrl": "audio/barbie/073_this_makes_me_emotional_and_i_m_expressing_it_i_have_no_diff.mp3"
  },
  {
    "text": "My job, it's just beach",
    "character": "",
    "audioUrl": "audio/barbie/074_very_common_because_actually_my_job_it_s_just_beach_right_an.mp3"
  },
  {
    "text": "You use your imagination",
    "character": "",
    "audioUrl": "audio/barbie/075_when_you_re_playing_with_barbies_hi_barbie_nobody_bothers_to.mp3"
  },
  {
    "text": "Ever think about dying?",
    "character": "",
    "audioUrl": "audio/barbie/076_you_guys_ever_think_about_dying.mp3"
  },
  {
    "text": "You should heal up",
    "character": "",
    "audioUrl": "audio/barbie/077_you_should_heal_up_in_no_time_actually_in_the_time_that_it_t.mp3"
  },
  {
    "text": "Every night, forever",
    "character": "",
    "audioUrl": "audio/barbie/078_every_night_is_girls_night_mm_hmm_every_night_forever.mp3"
  }
];
